[코비] 1, 2단계 영화 티켓 예매 제출합니다.
woowacourse/android-movie-ticket pull request #15
Opened 2023-04-13 08:13 UTC by rhkrwngud445

2023-04-13 21:54 UTC, galcyurio requested changes
1, 2 단계 잘 구현해주셨네요 👏
몇 가지 피드백을 남겨두었으니 확인 후 다시 요청해주세요.

2023-04-13 21:54 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/IntentExtension.kt
> +internal inline fun <reified T : Serializable> Intent.customGetSerializable(key: String): T? {
이런 형태의 이름들은 안드로이드에서 보통 Compat을 붙이므로 `getSerializableCompat()`과 같이 지어주면 좋습니다.

2023-04-13 21:54 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/BookCompleteActivity.kt
> +            )
`findViewById()`를 한 번만 해두고 캐시를 하거나 ViewBinding을 활용해보세요.

2023-04-13 21:54 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/BookCompleteActivity.kt
> +        }
onCreate() 함수가 길어지지 않도록 별도의 함수로 분리해보세요.

2023-04-13 21:54 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/Movie.kt
> +) : Serializable
Parcelable을 활용하는 방법을 찾아보고 적용해보세요. 
Serializable과는 어떤 차이점이 있는지도 공부해보면 좋겠습니다.

2023-04-13 21:54 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/MovieListAdapter.kt
> +        return view
convertView를 이용하여 기존 View를 잘 활용해주셨네요.
다만 여전히 `findViewById()`는 매번 호출하게 됩니다. 
ViewHolder와 같은 객체를 만들고 그곳에 View를 캐시해두는 방법을 써보세요.

2023-04-13 21:54 UTC, galcyurio commented on app/src/main/res/layout/activity_book_complete.xml
> +    </androidx.constraintlayout.widget.ConstraintLayout>
ConstraintLayout을 또 다시 ConstraintLayout가 감싸고 있네요.
이런 패턴은 대부분의 경우 바깥의 ConstraintLayout만으로도 충분합니다.
현재의 경우에는 TextView 자체의 크기를 키우고 background를 설정하면 가능해보여요.

2023-04-13 21:54 UTC, galcyurio commented on app/src/main/res/layout/activity_movie_detail.xml
> +        android:layout_height="211dp"
대부분의 높이, 너비를 하드코딩 해주셨는데 디자이너의 의도가 들어가지 않는 한 `wrap_content`, `match_parent`로 설정해주셔야 여러 해상도의 기기에서 보았을 때 자연스러워집니다.

2023-04-13 21:54 UTC, galcyurio commented on app/src/main/res/layout/activity_movie_detail.xml
> +            android:text="예매완료"
Android Studio에서 경고를 띄워주고 있네요. 문자열들을 `strings.xml`로 이동시켜보세요.

2023-04-15 09:56 UTC, rhkrwngud445 commented on app/src/main/java/woowacourse/movie/MovieListAdapter.kt
> +        return view
binding의 root tag를 통해 재활용 할 수 있도록 하였습니다!

2023-04-16 07:57 UTC, galcyurio approved these changes
피드백 잘 반영해주셨네요 👍 
각 피드백별로 커밋도 잘 나누어주셔서 보기 편했습니다.
추가로 몇 가지 피드백을 남겨두었는데 다음 단계에서 같이 반영해주시면 됩니다!

2023-04-16 07:57 UTC, galcyurio commented on app/src/main/res/values/intent_key.xml
> +    <string name="MOVIE_DATA_INTENT_KEY">"MOVIE_DATA_KEY"</string>
intent key의 경우에는 번역이 필요하지 않고 단순히 개발단에서 unique하기 하면 됩니다.
따라서 `strings.xml`로 까지 분리하기보다는 상수로 분리하시는게 개발에 편리합니다.

그 이유는 `strings.xml`에서 가져오려면 Context가 필요하지만 상수인 경우에는 그러한 조건이 불필요하기 때문이에요.

2023-04-16 07:57 UTC, galcyurio commented on app/src/main/java/woowacourse/movie/MainActivity.kt
> +        )
데이터를 가져오는 책임을 별도로 분리해보세요.
그렇게 하면 가짜 데이터들을 실제 데이터로 변경할 때에도 Activity의 코드는 건드리지 않고 수정할 수 있습니다.

2023-04-16 07:58 UTC, merged