[써니] 1,2 단계 영화 티켓 예매 제출합니다.
woowacourse/android-movie-ticket pull request #23
Opened 2023-04-13 08:48 UTC by inseonyun

안녕하세요 리뷰어님, 영화 티켓 예매 미션 잘 부탁드립니다.

2023-04-13 13:58 UTC, laco-dev requested changes
안녕하세요, 영화 티켓 예매 미션동안 잘 부탁드립니다.

우선은 도메인 관점에서의 설계를 위주로 리뷰를 진행 했습니다.
데이터바인딩이나 프래그먼트 등 어려운 개념을 일부 적용 해 주신 것 같습니다.

다만 미션 단계에 따라 기본적인 구현 방식을 충분히 이해하고 사용했는지 확인이 어렵기 때문에, 
미션에서 필요한 의사소통이나 구현 과정에서 불필요한 맥락이 생겨나게 됩니다.

충분히 이해하고 학습하신 뒤에 도전 해보셔도 문제 없습니다.
아직은 욕심을 부리기 보다는 기본기를 충분히 다질 수 있도록 하는 것을 권장드립니다.

2023-04-13 13:58 UTC, laco-dev commented on README.md
> +- [ ] 화면이 회전되어도 입력한 정보를 유지한다.
- [x] ???

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/data/Movie.kt
> +) : Serializable {
MovieData와 Movie 객체가 어떤 차이를 가지고 있는지 모르겠습니다.

누가 도메인 모델의 역할에 가까운 것일까요?
MovieData는 왜 위 정보들을 가지고 있지 않고 시간 정보만 가지고 있을까요?

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +import java.io.Serializable
도메인 모델에서는 Serializable을 직접적으로 사용하는 것은 좋지 않습니다.

화면 단위로 데이터를 넘겨주기 위해 사용한 것으로 생각되는데,
UI의 관심사로 인해 도메인 코드에 영향을 주어서는 안되겠습니다.

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +        if (isDiscountDay()) (money - money * DISCOUNT_PERCENT).toInt() else money
할인 정책과 할인 조건은 상황에 따라 변경이 될 수 있습니다.
그렇다면 지금 구현에서는 어떻게 수정을 해야 할까요?

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +    }
data class같은 방법을 사용하면 해시 코드나 equals()구현을 생략할 수 있는데요.

혹시 이전의 다른 미션에서 사용한 적이 있으신가요?

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/domain/MovieTime.kt
> +        hour < AM_DISCOUNT_CLOSE_TIME || hour >= PM_DISCOUNT_OPEN_TIME
MovieTime 객체가 할인이라는 관심사를 알 필요가 있을까요?

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/domain/Ticket.kt
> +    @JvmOverloads
자바를 같이 구현하지 않기 때문에 `@JvmOverloads` 어노테이션은 불필요합니다.

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/domain/Ticket.kt
> +        discountables.forEach { discountedPrice = it.discount(discountedPrice) }
DiscountedPrice가 각각의 할인 조건들에 대해 덮어 씌워지는 것 같습니다.

의도된 할인 동작이 맞을까요?

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/domain/Ticket.kt
> +    }
`Int.coerceAtLeast(...)` 함수를 활용 해보세요

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/activities/MainActivity.kt
> +                val c = getFragment(this, TicketingResultFragment::class.java.name)
영화 티켓 예메의 경우 기본적으로 각각 서로 다른 역할을 하는 화면으로 이루어져 있습니다.
그렇기 떄문에 액티비티를 사용한 구현을 기대했는데요.

프래그먼트를 사용한 이유를 알려주세요.
써니의 의견 외에도 다른 크루와 코치분들에게도 한번 의견을 물어보시면 좋겠습니다.

그에 따라 이후의 프래그먼트 관련 리뷰를 진행하려고 합니다.

개인적으로는 미션을 구현하기 위해 지나친 오버 엔지니어링은 피드백을 진행하는데 불필요한 의사소통이 많이 필요해서 권장드리지 않는 편입니다.

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/adapter/MovieListAdapter.kt
> +    private inner class ViewHolder(private val binding: ItemMovieBinding) {
코틀린은 기본적으로 클래스 내부에 선언하면 정적 클래스로 만들어집니다.
즉 inner 클래스를 사용하지 않는 것을 권장한다는 의미인데요.

왜 inner 클래스를 사용하면 안될까요?
관련해서 레퍼런스를 한번 찾아보세요

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/fragments/MovieListFragment.kt
> +        binding.lvMovies.adapter = listAdapter
indent가 많이 깊게 만들어졌습니다.

적절한 함수 분리를 통해 가독성을 올려주세요

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/fragments/TicketingFragment.kt
> +    private val selectedTime: MovieTime? get() = _selectedTime
Backing Property라고 부르는 이 전략은 Mutable 타입을 클래스 외부에 노출할 경우 안전하게 처리하는 전략입니다.

private으로만 사용되는 경우는 사용하지 않아도 됩니다.
https://kotlinlang.org/docs/properties.html#backing-properties

2023-04-13 13:58 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/fragments/TicketingFragment.kt
> +        super.onViewCreated(view, savedInstanceState)
레벨 1에서 함수의 코드를 줄이는 것은 레벨 2에, 안드로이드 코드에서도 동일합니다.

onViewCreated 함수를 다이어트 해주세요

2023-04-14 09:58 UTC, inseonyun commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +    }
로또 미션에서 Lotto class의 생성자를 private 으로 두고, equals와 hashCode를  팩토리 함수로  Lotto를 생성하도록 했었습니다!
이때도 data class가 아닌 일반 class로 구현한 이유에 대해 비슷한 피드백을 받았었습니다!
제가 data class를 택하지 않은 이유는 생성자를 private으로 두었기에 그랬었는데,
항상 이와 관련해서 data class와 일반 class를 두고 고민하게 되는데 조언을 구할 수 있을까요!?

2023-04-15 06:06 UTC, inseonyun commented on app/src/main/java/woowacourse/movie/view/adapter/MovieListAdapter.kt
> +    private inner class ViewHolder(private val binding: ItemMovieBinding) {
inner class에서 outer class의 프로퍼티를 참조하게 됐을 때, 값을 항상 참조하기 때문에 outer class를 사용하지 않는 순간에도 inner class로 인해 메모리를 제 때 해제하지 못해 메모리 누수가 발생할 수 있는 문제가 있습니다.
이 외에도 직렬화와 같은 문제로 inner class 사용을 지양한다고 알 게 되었습니다.
추가적으로 '그럼 inner class는 무조건 사용하면 안 되는걸까?' 를 생각하게 되었고, 알아보니 위 문제점, 특히 현재 구현한 viewHolder는 메모리 누수를 야기하는 문제에 해당하므로, inner, outer의 참조를 명시적으로 해제해줘서 사용할 수 있는 방법을 알게 되었습니다.
이 문제점을 적절히 잘 해결해서 사용한다면 inner class에서 outer class를 참조할 수 있는 유용한 기능이기에 Kotlin에서도 default로는 중첩 class를 두었지만 inner 키워드로 inner class를 사용할 수 있게 한 점도 이러한 이유이지 않을까 생각하게 되었습니다 !    : )

2023-04-15 15:14 UTC, inseonyun commented on app/src/main/java/woowacourse/movie/domain/Ticket.kt
> +        discountables.forEach { discountedPrice = it.discount(discountedPrice) }
할인 조건들을 돌면서 그 결과를 받고 결과를 토대로 다른 할인 조건을 탐색하여 새 결과를 만들어내도록 했습니다!
방법이 맘에 들진 않지만 별다른 방법이 떠오르지 않아 이와같이 처리를 하였습니다...!

2023-04-17 00:13 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/Extensions.kt
> +inline fun <reified T : Parcelable> Bundle.customGetParcelable(key: String): T? =
확장함수로 반복되는 동작을 잘 포장 해주셨습니다. 👍🏻 

하지만, 이 코드를 사용하는 개발자가 Bundle.customGetParcelable()을 어떤 동작을 의도하고 사용할지 예측이 쉬울까요?

custom이 무엇을 의미하는지? 실제 동작을 모두 이해하기 전까지는 모릅니다.
안드로이드에서는 하위 호환성을 유지하면서 동일한 인터페이스를 지원하기 위해 XXXCompat 이라는 개념을 사용합니다.

ContextCompat, ResourceCompat 등 관련 코드랑 비슷하게 만들어봐도 재밌을 것 같아요.

2023-04-17 00:13 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/model/mapper/MovieMapper.kt
> +fun Movie.toDomain(): MovieDomain = MovieDomain(title, startDate, endDate, runningTime, introduce, thumbnail)
도메인과 1:1 대응되는 UI 레이어의 모델이네요.

아마 이름을 어떻게 만들어야 하지? 라는 고민이 필요했을 것 같습니다.
도메인과 똑같이 해야하나?
다르게 지어야 하나?

모듈이 4개라면 Reservation 클래스가 4개가 될 수도 있으니까요.

Alias를 사용하는 방법도 있지만 이름이 완전 동일하면 확장 함수를 정의하거나 할 때 살짝 불편할 수도 있어요!

다른 크루분들이 UI 레이어의 모델 이름을 어떻게 짓는지 한번 논의 해보세요.

---

우선은 도메인 모델을 가장 기본 형태로 짓는게 일반적입니다.

2023-04-17 00:13 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/model/Movie.kt
> +                R.drawable.img_default_movie_thumbnail1
타입이 Int라고 해서 안드로이드 의존성이 빠져 나간 것은 아닙니다.
쉽게 Movie 클래스를 도메인 에서 만들어서 반환해야 한다면 어떻게 해야 할까요?

일반적으로 이미지와 같은 내용은 서버에서 String으로 된 네트워크 URL을 받지만,
현재는 리소스로 사용해야 하기 때문에 살짝 곤란할 수 있습니다.

---

이미지 저장소를 캐시해서 가져오거나,,, 여러가지 방법을 사용해서
Movie 더미 데이터를 도메인 모듈에서 만들도록 해주세요

2023-04-17 00:13 UTC, laco-dev commented on domain/src/main/java/com/woowacourse/movie/domain/Ticket.kt
> +value class Ticket(val count: Int = MIN_TICKET_COUNT) : Serializable {
Parcelable로 UI 모듈에서 사용되기 때문에 Serializable은 제거 해주셔도 됩니다.

2023-04-17 00:13 UTC, laco-dev commented on domain/src/main/java/com/woowacourse/movie/domain/RunningTime.kt
> +    private fun isToday(date: LocalDate): Boolean = date.compareTo(LocalDate.now()) == 0
코드를 읽을 때에는 위에서 아래부터 자연스럽게 읽고는 합니다.
그렇기 때문에 함수의 순서도 호출하는 순서대로 위치를 해주시면 좋습니다.

가령 isWeekend() 함수와 isToday() 함수는 runningTimes()함수의 아래에 위치합니다.

2023-04-17 01:04 UTC, laco-dev requested changes
어려운 피드백을 드렸는데, 잘 고민하고 변경 해주셔서 좋았습니다.

현재 도메인 모델이 아무런 역할을 하고 있지 않은 경우가 있어서 관련된 피드백을 몇가지 드렸습니다.
다음 3, 4단계에서 도메인 변경을 줄이기 위해 이번 단계에서 잘 잡고 넘어가면 좋을 것 같아요. 🙏🏻

2023-04-17 01:04 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/adapter/MovieListViewHolder.kt
> +    private val btnBook: Button = view.findViewById(R.id.btn_book)
뷰홀더를 이용해 반복된 findViewById를 피하고 역할을 잘 만들어 주셨습니다. 💯

2023-04-17 01:04 UTC, laco-dev commented on app/src/main/res/layout-land/activity_ticketing_result.xml
> +        android:textStyle="bold"
다음에 기회가 된다면 뷰의 스타일을 이용해서 텍스트 스타일을 정의하는 방법에 대해 공부 해보시면 좋습니다.
이 동작은 반복되는 여러가지 속성을 묶는 방법입니다.

```xml
<TextView
   style="@style/TextAppearance_XXX"
   /> 
```

2023-04-17 01:04 UTC, laco-dev commented on app/src/main/res/layout/activity_ticketing_result.xml
> +        app:layout_constraintStart_toStartOf="@id/ticketing_header_container" />
어떠한 뷰 영역을 지정할 때 고정된 높이를 사용하는 것은 지양되는 편입니다.
정말 디자인이 고정된 경우를 제외하고는 잘 사용하지 않아요.

이런 경우에는 TextView를 감싸는 뷰 그룹이 있고, 해당하는 뷰 그룹에 여백을 주는 방식을 주로 사용합니다.

그렇기 때문에 반드시 모든 뷰그룹이 ConstraintLayout으로 만들 필요는 없어요.

2023-04-17 01:07 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +    }
트레이드 오프로 볼 수도 있고, 개발자 자존심!? 이라고 볼 수도 있기는한데요.
기본적으로 data class는 값을 표현하기 위한 객체에 가깝기 때문에 private 생성자로 만들어 지는 경우가 잘 없습니다.

그냥 class가 되어야 하는게 아닌가? 라고 생각을 해보는게 맞을 수도 있습니다.

하지만 그럼에도 data class가 지원해주는 기능이 막강하기 때문에 코틀린 개발에 있어서는 상당히 유용하게 사용이 되고 있습니다.

또한 private 생성하는게 아닌 객체간의 협력을 통해 객체를 생성하는 것이 오히려 맞는 방법이 될 수도 있습니다.

이러한 충분한 고민을 한 뒤에 마지막에 나오는 결론은 앞으로 작성하는 모든 클래스에 equals(), hashCode()를 구현하시고 버그를 안만들어 낼 자신이 있으실지 여쭙고 싶군요.. 😓

2023-04-17 15:44 UTC, inseonyun commented on app/src/main/java/woowacourse/movie/Extensions.kt
> +inline fun <reified T : Parcelable> Bundle.customGetParcelable(key: String): T? =
Activity에 붙어있는 AppCompatActivity의 "Compat"이 무슨 의미인지 고민해본적이 없었는데 이번 기회에 알 게 되었네요 ㅎㅎ 이런 네이밍 하나하나 다 의미가 있었군요...
[https://medium.com/@waltzforash/android-compat-class-viewcompat-appcompatactivity-5926950a3a2e](참고 자료) 이 것은 그냥 제가 라코님이 알려주신 내용 찾아보다 발견한 내용입니당
알려주셔서 감사합니다 :)

2023-04-18 07:54 UTC, inseonyun commented on app/src/main/java/woowacourse/movie/view/activities/TicketingActivity.kt
> +                )
Movie 객체에서 reserve 함수를 통해 Reservation을 만들어 반환하도록 수정하였습니다!

2023-04-18 15:13 UTC, inseonyun commented on domain/src/main/java/com/woowacourse/movie/domain/policy/EarlyAndLatePolicy.kt
> +    private fun calculateTime(localTime: LocalTime): Int = localTime.hour * HOUR_TO_MIN + localTime.minute
조조, 야간 할인 적용 시간이 정각 x시로 정책 되어있지만 분 단위로도 바뀔 수 있을 거란 생각에 시간을 분으로 계산하고 해당 로직을 구성해줬습니다!
그런데 지금 보니 isDiscount()에서 선언한 상수의 시간은 totalTime을 구하지 않는 구조네요 : (

2023-04-18 15:31 UTC, inseonyun commented on domain/src/main/java/com/woowacourse/movie/domain/RunningDate.kt
> +    }
오,, 그렇네요,,, 쓸데없이 start, endDate를 받을 필요도 없어지네요! : )

2023-04-18 16:57 UTC, inseonyun commented on app/src/main/java/woowacourse/movie/view/activities/TicketingActivity.kt
> +    }
로직 작성 시 계속 신경쓰였던 부분이네요!!
위와 같이 구성하여 당연히 넘어와야 한다고 생각되는 값을 못 가져왔을 때 어떻게 할 지 고민했던 부분이에요!!
못 가져온 값을 뷰 요소에 넣어주지 않은 채 화면에 출력하는 것보다 
위와 같은 방식이 더 나을 거 같단 생각에 동일한 느낌으로 TicketingResultActivity도 수정하였습니다 : )

2023-04-18 23:47 UTC, laco-dev approved these changes
피드백 잘 반영 해주셨습니다.
전반적으로 구조가 많이 좋아지는 모습이 보여서 좋았습니다.

3, 4 단계 미션 진행을 위해 이번 단계는 마무리 하도록 하겠습니다.
몇가지 의견을 추가로 남겨드렸는데, 다음 단계의 요구사항을 구현하기 위해 필요한 내용일 수 있습니다.

시작하기에 앞서 충분히 고민 해보시면 좋겠습니다.
마지막 까지 화이팅입니다. 💪🏻

2023-04-18 23:47 UTC, laco-dev commented on app/src/main/AndroidManifest.xml
> +            android:name=".activities.movielist.MovieListActivity"
제가 드린 패키지의 기준은 `.movieList.MovieListActivity` 입니다!
activies라는 것 자체가 액티비티들만 모아두었다 라는 기준이 됩니다.

2023-04-18 23:47 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activities/movielist/MovieListActivity.kt
> +    private fun setMovieData() {
setter라는 이름의 함수는 어떠한 파라미터를 받아서 업데이트 하는 동작을 수행합니다.
그렇기 때문에 현재 값을 기준으로 변경하는 것과는 이름이 맞지 않습니다.

적절한 이름으로 변경하거나 setter의 역할에 맞게 동작을 수정 해보세요

2023-04-18 23:47 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activities/ticketing/TicketingActivity.kt
> +        }
값을 초기화 하는 것이 분리되는 것보다는 반환하는 함수를 작성해서 하는것이 흐름을 만드는데 더욱 좋은 편입니다
```kotlin
val movie = getMovieFromIntent() ?: return
this.movie = movie

setMovieInfo(movie)
setMovie(movie)
```

2023-04-18 23:47 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activities/ticketing/TicketingActivity.kt
> +        setTicketCount(movieTicket.toTicket().run { inc().toTicketUI() })
코틀린의 Scope Functions인 run의 올바른 사용방법이 아닙니다.
단순히 변수랑 코드를 줄이는데 사용되는 것이 아닌 적절한 상황에 맞게 사용하는 것이 좋습니다.

```kotlin
private fun plusTicketCount() {
   val newTicketCount = movieTicket.plus()
   setTicketCount(newTicketCount)
}

```

2023-04-18 23:47 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activities/ticketing/TicketingActivity.kt
> +            movie,
onSaveInstganceState()에서는 Bundle에 저장하는 과정을 수행하는데요.
가지고 있는 reservation 멤버 프로퍼티를 업데이트 하는 과정이 필요할까요?

2023-04-18 23:47 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/model/MovieUI.kt
> +        get() = this.format(DateTimeFormatter.ofPattern(MOVIE_DATE_PATTERN))
UI의 관심사를 UI 모델에 잘 만들어주셨네요. 👍🏻

2023-04-18 23:47 UTC, laco-dev commented on domain/src/main/java/com/woowacourse/movie/domain/Movie.kt
> +            .takeWhile { it <= endDate }
takeWhile대신에 filter가 적절한 선택이 될 수 있습니다.

2023-04-18 23:47 UTC, laco-dev commented on domain/src/test/java/com/woowacourse/movie/domain/MovieTest.kt
> +        )
테스트를 작성하면서 상영일과 관련없는 정보는 불필요할 수 있습니다.
이에 따라 테스트 코드에서는 Fake 생성자 등의 여러가지 전략을 사용하고는 합니다.

https://blog.kotlin-academy.com/item-30-consider-factory-functions-instead-of-constructors-e1c747fc475

2023-04-18 23:47 UTC, laco-dev commented on domain/src/main/java/com/woowacourse/movie/domain/Reservation.kt
> +    val totalPrice: Int
예약이라는 객체가 알고 있는 것에 대해서 ::
- 영화 정보
- 티켓 정보

티켓이라는 객체가 알고 있는 것에 대해서 ::
- 예매 인원 수


전체 가격은 누가 알고 있는 정보가 되어야 할까요?

2023-04-18 23:47 UTC, laco-dev commented on domain/src/main/java/com/woowacourse/movie/domain/Ticket.kt
> +    }
티켓의 가격은 티켓이 계산하고
할인은 Decorator가 처리하는게 맞을까요?

티켓이 어떠한 할인 조건에 대해 결과적으로 "할인된 가격"을 계산하는 역할로 봐야 하지는 않을까요?

2023-04-18 23:47 UTC, merged