[부나] 1, 2 단계 영화 티켓 예매 제출합니다.
woowacourse/android-movie-ticket pull request #24
Opened 2023-04-13 08:51 UTC by tmdgh1592

안녕하세요 제리!
첫 안드로이드 리뷰이가 되어 영광입니다~ 😃
아직 부족한 점이 많아 리뷰를 많이 달아주신다면 정말 큰 도움이 될 것 같습니다!

감사합니다 : )

2023-04-14 03:41 UTC, vagabond95 requested changes
리뷰가 조금 늦어져 죄송합니다 🥲 
구현해주신 내용에 대하여, 도메인을 중심으로 1차 리뷰를 진행했습니다~!
코멘트 확인 부탁드릴게요~!

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/res/layout/item_movie.xml
> +        android:text="@string/ticket_now"
값을 하드코딩하지 않고, string res 를 잘 활용해주셨네요 👍

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/res/layout/fragment_ticketing.xml
> +            app:layout_constraintBottom_toBottomOf="@id/ticketing_container" />
해당 영역의 `android:text` 값도 string res 로 관리되면 좋을 것 같아요~!

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/res/layout-land/fragment_ticketing_result.xml
> +        android:background="@color/ticketing_header_color" />
color res 로 관리 👍

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/data/Movie.kt
> +) : Serializable {
해당 클래스는 도메인 모델로 분리해주신 것으로 보이는데요.
Serializable 를 구현해주신 이유가 있을까요?

activity 에서 활용하기 위한 것이라면, Serializable 용 모델을 별도로 분리해주는 것이 좋을 것 같아요.
도메인 영역은 android os 와는 독립적으로 구성되어야합니다!

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/view/activities/MainActivity.kt
> +                val a = getFragment(this, MovieListFragment::class.java.name)
a, b, c 와 같은 네이밍은 이해하기 어려울 것 같아요. 의미있는 네이밍을 붙혀주는 연습을 해보면 좋겠어요!

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/view/activities/MainActivity.kt
> +                if (it.isAdded) putFragment(outState, TicketingResultFragment::class.java.name, it)
코드가 중복되는 것으로 보이는데요. 하나의 함수로제공해볼 수 있지 않을까요?

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/view/activities/MainActivity.kt
> +                    }
코드가 중복되는 것으로 보이는데요. 하나의 함수로제공해볼 수 있지 않을까요?

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/view/adapter/MovieListAdapter.kt
> +                btnBook.setOnClickListener { onBookClickListener.onClick(this) }
클릭 이벤트를 외부로 위임 👍

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/view/fragments/MovieListFragment.kt
> +                object : MovieListAdapter.OnBookClickListener {
함수 타입으로 제공해주면 훨씬 간결해질 것 같아요~!

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +    override fun equals(other: Any?): Boolean {
data class 가 아닌, 직접 구현하신 이유가 있으실까요?

2023-04-14 03:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +        if (isDiscountDay()) (money - money * DISCOUNT_PERCENT).toInt() else money
discount 에 대한 정책을 외부로 분리해보는 것도 좋을 것 같아요!

2023-04-14 05:28 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/Extensions.kt
> +
확장함수 파일을 각 확장하는 클래스별로 분리했습니다!
- util
   + extensions
        * ContextExt.kt
        * FragmentExt.kt
        * FragmentManagerExt.kt

2023-04-14 05:51 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/data/Movie.kt
> +) : Serializable {
Movie 클래스는 Domain이 아닌 UI 레이어에서 사용하기 위해 만들었습니다!
따라서 별도의 비즈니스 로직을 포함하지 않으며 화면에 보여주기 위한 데이터를 관리하기 위해서 만들었습니다!

2023-04-14 05:58 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/data/Movie.kt
> +) : Serializable {
또한, 일반적인 상황의 경우 Parcelable의 성능이 더 좋다고 하여 Serializable을 구현하는 클래스를 Parcelable을 구현하도록 변경하였습니다.

2023-04-14 05:58 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/view/activities/MainActivity.kt
> +                val a = getFragment(this, MovieListFragment::class.java.name)
앗.. 임의로 작성한 변수명을 그대로 커밋한 것 같습니다..!!
수정하겠습니다!

2023-04-14 06:31 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/view/fragments/MovieListFragment.kt
> +                object : MovieListAdapter.OnBookClickListener {
함수 타입으로 정의해주었고, 람다를 전달하도록 변경하였으며, ViewHolder가 inner 클래스일 때 갖는 memory leak 문제를 해결하기 위해 nested class로 변경하였습니다.

2023-04-14 06:50 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +    override fun equals(other: Any?): Boolean {
MovieDate 클래스는 private constructor이기 때문에 data class로 변경해주면 아래와 같은 warning이 발생합니다.
`Private primary constructor is exposed via the generated 'copy()' method of a 'data' class.`
copy() 메서드를 외부로 노출하면서 private contructor를 사용하는 의미가 사라져서 직접 구현하였습니다!

이러한 문제점을 해결할 수 있는 방안이 있을까요?!

2023-04-15 04:25 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/view/activities/MainActivity.kt
> +                    }
Fragment 코드를 Activity 코드로 변경하면서 해당 함수 자체를 제거하였습니다!

2023-04-15 04:28 UTC, tmdgh1592 commented
안녕하세요 리뷰어님!
2차 리뷰 잘 부탁드립니다 : )

Fragment를 사용하면 오버 엔지니어링이기도 하고, Activity에 대해 공부하고 있는데 Fragment를 통해 구현하면 리뷰어님과 리뷰, 소통이 어려워진다는 이야기를 듣고 Activity로 리팩토링을 하였습니다. 🥲
리뷰하시기에 번거롭게 해드려 대단히 죄송합니다..!!

2023-04-15 13:28 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +    override fun equals(other: Any?): Boolean {
Movie 클래스를 private constructor 로 사용했을 때 이점은 무엇이 있을지 얘기나눠보고 싶습니다 ㅎㅎ
그리고 해당 이점이 data class 를 활용하지 않는 것보다 더 좋을지에 대해서도요!

2023-04-15 13:28 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/presentation/activities/ticketing/TicketingActivity.kt
> +    }
이러한 내용들은 extension function 으로 선언하는 것이 큰 의미가 없지 않을까요~?

extention function 을 사용하시는 기준이 궁금합니다~!

2023-04-15 13:28 UTC, vagabond95 commented on app/src/main/res/layout-land/activity_ticketing_result.xml
> +        android:textSize="15sp"
현재 과정에서 중요한 부분은 아니지만,
textSize 를 설정할 때는 sp 와 dp 를 모두 활용할 수 있는데요.

각각의 차이점에 대해 공부해보셔도 좋겠습니다~!

2023-04-15 13:28 UTC, vagabond95 commented on domain/src/main/java/woowacourse/movie/domain/model/movie/TicketPrice.kt
> +    fun applyDiscountPolicy(
할인 정책이 느슨하게 연결되었네요 👍

2023-04-15 13:28 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/data/Movie.kt
> +) : Serializable {
핫 그렇군요!
data 로 분류해주셔서 도메인의 개념으로 두신것으로 착각하고 있었네요 ㅎㅎ

저는, 기본적으로 최소한의 구분으로 domain 모델과 ui 모델이 분리되어야한다고 생각해요.
요구사항이 작거나 스몰 비즈니스의 경우 당장 분리의 효과를 느끼기는 어렵지만, 조금만 복잡해지더라도 두 레이어의 모델을 분리하지 않았을 때 변경이 너무나 어려워지는 경험을 많이 했어서 그런가 봅니다. ^.ㅜ

2023-04-15 13:28 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/data/Movie.kt
> +) : Serializable {
Parcelable 도입해주신 것 👍 

Parcelable 이 더 성능이 좋은 이유는 무엇일까요?

2023-04-15 13:32 UTC, vagabond95 requested changes
크게 피드백 드릴 부분이 없을 만큼 많이 개선되었네요 👍 👍 

모델별 레이어를 나누고 mapper 를 꼼꼼하게 둔 부분, policy 인터페이스 전환등이 좋았던거 같아요.
질문주신 내용에 대한 답변 및 간단한 코멘트 남겼는데 확인 부탁드릴게요 :)

2023-04-15 14:35 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/presentation/activities/ticketing/TicketingActivity.kt
> +    }
> Movie 클래스를 private constructor 로 사용했을 때 이점

MovieDate, MovieTime 같은 클래스는 생성할 인스턴스 수가 정해져 있습니다.
그렇기 때문에 팩토리 메서드와 private constructor를 통해 불필요한 인스턴스를 생성하는 상황을 방지할 수 있다는 장점이 있습니다!

하지만 두 번째 리뷰요청을 보낸 코드에서는 더 이상 private constructor가 아닙니다.
그 이유는 domain, presentation layer간에 객체를 mapping하는 과정에서 생성자가 필요한 상황이 발생하기 때문입니다.
여기서 궁금증이 생긴 것은 인스턴스 수를 제한하고 싶지만, `layer간에 객체를 mapping해야 하는 이유만으로 private constructor를 해제해야만 할까?` 입니다. 또한 `이러한 방법밖에 없는지` 궁금합니다.
구글링을 통해 찾아보았지만, 별다른 방법을 찾지 못해 조언을 구하고 싶습니다..! 😃

> 해당 이점이 data class 를 활용하지 않는 것보다 더 좋을지

data class를 사용하지 않음으로써, 두 클래스에 equals(), hashcode()를 직접 override 해주어야 하는 단점이 존재합니다.
이렇게 직접 override 해주면서 코드가 불필요하게 길어지는 단점까지 배제할 수 없다고 생각합니다.
하지만, private constructor를 사용함으로써, 불필요한 인스턴스를 생성하는 상황을 방지할 수 있고, data class에서 제공해주는 (현재로써 불필요한) copy(), getter(), setter(), toString() 코드가 자동 생성되지 않도록 할 수 있다는 이점이 있습니다.
이는 구현 방식에 따라 발생하는 trade-off라고 간주하고 data class를 작성하지 않는 방법을 택했었습니다.
`Movie 클래스를 private constructor 로 사용했을 때 이점`에서 말씀드린 바와 같은 이유로 지금은 data class를 사용하고 있습니다!   

> extention function 을 사용하시는 기준이 궁금합니다~!

우선 extension을 사용한 이유는 `with(binding) { ... }` 내에 작성한 코드를 cmd + shift + M 단축키로 메서드 분리를 하는 과정에서 자동으로 생겨났습니다!
이후에 Extension을 제거하지 않은 이유는 매번 view에 접근하는 과정에서 `with(binding) { ... }` 또는 `binding.tvtitle`과 같이 반복되는 코드를 줄일 수 있었기 때문입니다.
제리의 관점은 어떤지도 궁금합니다! : )

2023-04-15 14:42 UTC, tmdgh1592 commented on app/src/main/res/layout-land/activity_ticketing_result.xml
> +        android:textSize="15sp"
sp를 사용하면 android의 시스템 폰트 시이즈에 영향을 받습니다.
반면, dp를 사용하면 android의 해상도에 영향을 받는다고 알고 있습니다.
따라서 시스템 설정에서 폰트 사이즈, 해상도를 변경했을 때와 기기 자체의 해상도에 영향을 받습니다!

2023-04-15 15:03 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/domain/MovieDate.kt
> +    override fun equals(other: Any?): Boolean {
> Movie 클래스를 private constructor 로 사용했을 때 이점

MovieDate, MovieTime 같은 클래스는 생성할 인스턴스 수가 정해져 있습니다.
그렇기 때문에 팩토리 메서드와 private constructor를 통해 불필요한 인스턴스를 생성하는 상황을 방지할 수 있다는 장점이 있습니다!

하지만 두 번째 리뷰요청을 보낸 코드에서는 더 이상 private constructor가 아닙니다.
그 이유는 domain, presentation layer간에 객체를 mapping하는 과정에서 생성자가 필요한 상황이 발생하기 때문입니다.
여기서 궁금증이 생긴 것은 인스턴스 수를 제한하고 싶지만, `layer간에 객체를 mapping해야 하는 이유만으로 private constructor를 해제해야만 할까?` 입니다. 또한 `이러한 방법밖에 없는지` 궁금합니다.
구글링을 통해 찾아보았지만, 별다른 방법을 찾지 못해 조언을 구하고 싶습니다..! 😃

> 해당 이점이 data class 를 활용하지 않는 것보다 더 좋을지

data class를 사용하지 않음으로써, 두 클래스에 equals(), hashcode()를 직접 override 해주어야 하는 단점이 존재합니다.
이렇게 직접 override 해주면서 코드가 불필요하게 길어지는 단점까지 배제할 수 없다고 생각합니다.
하지만, private constructor를 사용함으로써, 불필요한 인스턴스를 생성하는 상황을 방지할 수 있고, data class에서 제공해주는 (현재로써 불필요한) copy(), getter(), setter(), toString() 코드가 자동 생성되지 않도록 할 수 있다는 이점이 있습니다.
이는 구현 방식에 따라 발생하는 trade-off라고 간주하고 data class를 작성하지 않는 방법을 택했었습니다.
`Movie 클래스를 private constructor 로 사용했을 때 이점`에서 말씀드린 바와 같은 이유로 지금은 data class를 사용하고 있습니다!

2023-04-15 15:09 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/data/Movie.kt
> +) : Serializable {
제가 아직 대규모 프로젝트를 경험하지 못해서 체감이 확 와닿지는 않네요 😭
하지만 만약 나중에 Movie 클래스의 멤버를 활용하는 요구사항이 추가되었을 때, 이미 domain 모델과 ui 모델이 분리되어 있다면 유지보수에 조금 더 수월할 수 있겠다는 생각이 듭니다!

2023-04-15 15:20 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/data/Movie.kt
> +) : Serializable {
제가 알고 있는 지식으로는, `Serializable`을 구현했을 때 내부적으로 `reflection`이 이루어져 비교적 속도가 느리다고 알고 있습니다.
`reflection 과정에서 불필요한 객체를 생성`하고, `GC가 이를 수거`하는 과정에서 오버헤드가 발생합니다.
반면, Parcelable은 사용자가 직접 역/직렬화를 정의해주어야 하고, 이로 인해 불필요한 과정이 생략되어 더 높은 성능을 띌 수 있습니다.

추가로 해당 [블로그 포스팅](https://medium.com/@limgyumin/parcelable-vs-serializable-%EC%A0%95%EB%A7%90-serializable%EC%9D%80-%EB%8A%90%EB%A6%B4%EA%B9%8C-bc2b9a7ba810) 에 따르면, Serializable 또한 마치 Parcelable처럼 구현해준다면 오히려 더 높은 성능을 띌 수 있다고 합니다!

2023-04-16 13:04 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/presentation/activities/ticketing/TicketingActivity.kt
> +    }
명확한 관점이 있다면 좋다고 생각합니다 👍 
다만, extension function 의 경우 접근 제한자를 잘 컨트롤해줘야하기 때문에 사용할 때, 일반 함수 대비 좀 더 주의를 기울여야한다고 생각해요.

public 하게 제공할 경우, 모든 곳에서 호출이 가능하므로 자칫하면 너무 자유도가 높아져 구현에 방해가 될 수 있기 때문입니다.
현재는 private 을 활용하여 잘 제어해주신 것 같습니다!

2023-04-16 13:11 UTC, vagabond95 approved these changes
1, 2 단계 구현하시느라 고생 많으셨습니다~!
현 단계에서는 추가로 중요하게 리뷰드릴 부분이 보이지 않아 머지하도록 하겠습니다.

남긴 코멘트는 다음단계 진행 시 참고 부탁드려요~!

2023-04-16 13:11 UTC, vagabond95 commented on app/src/main/java/woowacourse/movie/presentation/activities/ticketing/TicketingActivity.kt
> +                movieTimes.clear()
clear 와 addAll 이 항상 세트로 가야한다면, 하나의 함수로 묶어봐도 좋겠습니다!

개별로 다룰 경우, 이러한 케이스가 많아질수록 어느 하나를 빼먹기 쉽기도 하고, 함수로 만들면 사용방법을 강제할 수 있으니까요 :)

2023-04-16 13:11 UTC, merged

2023-04-16 13:20 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/movie/presentation/activities/ticketing/TicketingActivity.kt
> +                movieTimes.clear()
충분히 빠뜨릴 수 있는 부분이라고 생각합니다!
매번 clear()를 호출하고 addAll()을 해야 한다는 것을 기억해야 한다는 불편함도 있구요..!
다음 미션에서 두 메서드를 묶은 별도의 메서드를 만들어보겠습니다!