[코건] 1, 2 단계 영화 티켓 예매 제출합니다
woowacourse/android-movie-ticket pull request #3
Opened 2023-04-13 06:57 UTC by DYGames

안녕하세요! 2주 동안 잘 부탁드립니다.

이번 미션은 3개의 액티비티 `MainActivity`, `MovieReservationActivity`, `MovieReservationActivity`,
`Movie`, `ReservationDetail` 모델에서 영화와 예약 정보를 관리하고 `Reservation` 모델에서 영화와 예약 정보를 함께 관리합니다.

`~Controller` 에서는 도메인과 뷰를 연결해주게 구현하였는데, MVC 패턴을 의도하고 구현한 것은 아닙니다.

아키텍쳐 패턴을 사용하지 않으면서 액티비티에서 최소한의 역할을 수행하도록 하였습니다.

또한 질문이 있는데,
안드로이드에서 뷰, 도메인등에서 문자열 상수를 사용할때 string.xml에 저장해야할 지 companion object에 저장해야할 지 기준이 궁금합니다.

상세한 피드백 주시면 열심히 생각하고 반영해보겠습니다! 감사합니다!

2023-04-13 13:47 UTC, BeokBeok requested changes
영화관 1,2단계 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/MainActivity.kt
> +    }
onCreate 함수는 두 가지 이상의 일을 하고 있어요. (뷰 생성, 더미 데이터 생성, 리스트뷰 초기화 등)
하나의 함수에서는 한 가지 일만 하도록 개선해보면 어떨까요? (이하 관련 내용 동일)

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/GetSerializable.kt
> +inline fun <reified T : Serializable> Bundle.getSerializable(key: String): T? {
확장함수를 잘 구현해주셨네요. 👍 
Bundle과 관련된 확장함수를 구현하는 파일이라면, 파일명을 좀 더 관련있는 이름으로 작성해보면 어떨까요?

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +            COUNTER_SAVE_STATE_KEY,
```suggestion
            counter = Counter(
                minus = findViewById(R.id.movie_reservation_people_count_minus),
                plus = findViewById(R.id.movie_reservation_people_count_plus),
                text = findViewById(R.id.movie_reservation_people_count),
                count = INITIAL_COUNT,
            ),
            saveStateKey = COUNTER_SAVE_STATE_KEY,
```
코틀린에서는 argument name이라는 것을 지원합니다.
argument name을 활용하면, 전달하는 값이 어떤 값인지 쉽게 알 수 있어요. (이하 관련 내용 동일)

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +            )
MovieController와 ReservationButton은 너무 많은 것을 캡슐화하고 있어요.
클래스가 많은 책임을 가지게 되는 것은 아닌지 고민해보면 좋을 것 같아요.

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +        const val TIME_SPINNER_SAVE_STATE_KEY = "time_spinner"
클래스 내부에서만 사용하는 변수라면, private 접근자를 붙여보면 어떨까요?

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/domain/DateRange.kt
> +        (0..Period.between(startDate, endDate).days).map { startDate.plusDays(it.toLong()) }
테스트 코드를 작성해보면 어떨까요?

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/domain/movieTimePolicy/MovieTime.kt
> +    }
이 메시지는 View에서 보게 될 메시지입니다.
domain 패키지에는 View와 관련이 없도록 개선해보면 어떨까요?

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/domain/movieTimePolicy/WeekdayMovieTime.kt
> +    override fun generateTime(date: LocalDate): List<LocalTime>? {
```suggestion
    override fun generateTime(date: LocalDate): List<LocalTime> {
```
List, Map, Set과 같은 컬렉션은 null 대신 빈 컬렉션을 활용하는 것을 권장합니다. (이하 관련 내용 동일)

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/view/Counter.kt
> +    plus: Button,
변수명만 보고서 Button인지 알 수 있을까요?

2023-04-13 13:47 UTC, BeokBeok commented on app/src/main/res/layout/activity_movie_reservation.xml
> +                android:layout_width="match_parent"
```suggestion
                android:layout_width="0dp"
```
ConstraintLayout은 match_parent 대신 0dp 사용을 권장합니다.

ref. https://developer.android.com/develop/ui/views/layout/constraint-layout#adjust-the-view-size

2023-04-13 13:48 UTC, BeokBeok commented
> 또한 질문이 있는데,
안드로이드에서 뷰, 도메인등에서 문자열 상수를 사용할때 string.xml에 저장해야할 지 companion object에 저장해야할 지 기준이 궁금합니다.

A. 뷰와 관련된 문구라면 strings.xml을 활용하고, 그렇지 않다면 상수로 정의해서 사용하는 것이 좋습니다.

2023-04-13 13:50 UTC, BeokBeok commented
추가로 0명도 예매가 가능한데, 이부분도 예외처리를 해보면 좋을 것 같아요.

2023-04-16 15:29 UTC, DYGames commented on app/src/main/java/woowacourse/movie/activity/MainActivity.kt
> +    }
onCreate에서 하는 일을 분리해주었습니다!

2023-04-16 15:29 UTC, DYGames commented on app/src/main/java/woowacourse/movie/GetSerializable.kt
> +inline fun <reified T : Serializable> Bundle.getSerializable(key: String): T? {
BundleExtension 으로 파일명을 변경하였습니다.

2023-04-16 15:33 UTC, DYGames commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +            COUNTER_SAVE_STATE_KEY,
default parameter가 적용된 많은 수의 인자를 전달해주는 부분에서 argument name을 활용해주었습니다.

2023-04-16 15:35 UTC, DYGames commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +            )
ReservationButton은 너무 많은 요소를 캡슐화하고 있어 삭제하고 Activity로 되돌렸습니다.

그런데 ~Controller는 단순히 도메인 객체를 뷰와 연결해주는 역할을 한다고 생각했는데, 그럼에도 많은 것을 캡슐화하고 있는 것인가요?

2023-04-16 15:35 UTC, DYGames commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +        const val TIME_SPINNER_SAVE_STATE_KEY = "time_spinner"
private 접근자를 적용해주었습니다.

2023-04-16 15:50 UTC, DYGames commented on app/src/main/java/woowacourse/movie/domain/DateRange.kt
> +        (0..Period.between(startDate, endDate).days).map { startDate.plusDays(it.toLong()) }
테스트 코드를 작성해주었습니다. 
그런데 코드를 리팩토링하면서 이 로직은 View의 로직이라고 판단하고 옮겼습니다.
근거는, 도메인은 날짜 간의 간격만 가지고 있고, 스피너에서 그려주기 위해 날짜 사이의 모든 날을 List로 만들어 주는 것은 도메인에서 해주지 않아도 되겠다고 생각했습니다.
이게 옳은 판단인지 궁금합니다.

2023-04-16 15:51 UTC, DYGames commented on app/src/main/java/woowacourse/movie/domain/movieTimePolicy/MovieTime.kt
> +    }
이 메시지는 이 domain을 사용하는 개발자가 잘못된 값을 세팅했을 때 출력하는 값으로 domain의 companion object에 넣어두었습니다. 사용자 입력 관련 오류는 sealed class를 이용해 처리할 계획입니다.

2023-04-16 15:53 UTC, DYGames commented on app/src/main/java/woowacourse/movie/domain/movieTimePolicy/WeekdayMovieTime.kt
> +    override fun generateTime(date: LocalDate): List<LocalTime>? {
전부 빈 컬렉션을 반환하도록 변경하였습니다.

2023-04-16 15:55 UTC, DYGames commented on app/src/main/java/woowacourse/movie/view/Counter.kt
> +    plus: Button,
접두사로 Type을 붙이면 불필요하다고 생각했는데, Button Type의 변수가 아닌, 추상적인 의미의 Button Type의 변수라는 의미로 이름을 지을 수 있다고 생각해서 접두사로 Button을 붙여주었습니다.

2023-04-16 16:03 UTC, DYGames commented on app/src/main/res/layout/activity_movie_reservation.xml
> +                android:layout_width="match_parent"
match_parent 대신 match constraints를 의미하는 0dp를 사용하도록 변경하였습니다.

2023-04-16 16:30 UTC, DYGames commented
안녕하세요! 상세한 리뷰 정말 감사드립니다.

주요한 변경점은
View와 Domain 영역의 분리를 위해 Mapper를 이용했습니다.
ReservationButton 클래스를 삭제하였습니다.

구조적인 부분에서 더 개선할 점이 있을지 피드백 부탁드리겠습니다.

감사합니다!

2023-04-17 13:11 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +            )
생성자로 5개 이상 넘겨주는 클래스라면, 많은 책임을 갖게 되는 건 아닌지 고민해보시면 좋을 것 같습니다.
아니면 data class를 만들어서 넘겨주는 방법도 있습니다. 😄

2023-04-17 13:13 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/domain/DateRange.kt
> +        (0..Period.between(startDate, endDate).days).map { startDate.plusDays(it.toLong()) }
> 근거는, 도메인은 날짜 간의 간격만 가지고 있고, 스피너에서 그려주기 위해 날짜 사이의 모든 날을 List로 만들어 주는 것은 도메인에서 해주지 않아도 되겠다고 생각했습니다.

좋은 의견입니다. 👍

2023-04-17 13:29 UTC, BeokBeok requested changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-04-17 13:29 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/MainActivity.kt
> +        val intent = Intent(this, MovieReservationActivity::class.java)
MainActivity가 MovieReservationActivity에 의존하고 있습니다.
MovieReservationActivity 클래스명이 변경되어도 MainActivity에는 영향을 받지 않도록 개선해보면 어떨까요? (이하 관련 내용 동일)

2023-04-17 13:29 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +    }
https://github.com/woowacourse/android-movie-ticket/pull/3#discussion_r1165499157
^ 위 코맨트 참고하시어 개선해보면 어떨까요?

2023-04-17 13:29 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/ReservationResultActivity.kt
> +    }
https://github.com/woowacourse/android-movie-ticket/pull/3#discussion_r1165499157
^ 위 코맨트 참고하시어 개선해보면 어떨까요?

2023-04-17 13:29 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/domain/Count.kt
> +    }
추가와 제거에 대한 함수를 잘 구현하셨네요. 👍 
지금도 좋지만, 연산자 오버로딩을 활용해볼 수 있어요.

ref. https://kotlinlang.org/docs/operator-overloading.html#binary-operations

2023-04-17 13:29 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/domain/movieTimePolicy/WeekdayMovieTime.kt
> +        return listOf()
```suggestion
        return emptyList()
```
빈 리스트인 경우에는 emptyList를 활용하면 좀 더 가독성이 좋아집니다. (이하 관련 내용 동일)

2023-04-17 13:29 UTC, BeokBeok commented on app/src/test/java/woowacourse/movie/domain/discountPolicy/MovieDayTest.kt
> +    }
함수명에는 10일, 20일, 30일에 대한 언급이 있으나, 10일인 경우에만 테스트를 하고 있네요.
10일 뿐만 아니라, 20일과 30일에 대해서도 테스트를 작성해보면 어떨까요?

2023-04-17 13:29 UTC, BeokBeok commented on app/src/test/java/woowacourse/movie/domain/discountPolicy/OffTimeTest.kt
> +        val date = LocalDateTime.of(2023, 1, 10, 10, 0)
```suggestion
        val date = LocalDateTime.of(2023, 1, 10, 10, 59)
```
가급적이면 경계값을 위주로 테스트를 작성하시는 것이 좋습니다. (이하 관련 내용 동일)

2023-04-18 08:58 UTC, DYGames commented
안녕하세요! 리뷰 감사드립니다!!
피드백 바탕으로 코드를 다시 수정해보았습니다.

Android에서 Domain과 View간에 연결하고 역할을 분리하는 것이 쉽지 않음을 느끼고 있습니다..!

감사합니다!

2023-04-18 08:59 UTC, DYGames commented on app/src/main/java/woowacourse/movie/activity/MainActivity.kt
> +        val intent = Intent(this, MovieReservationActivity::class.java)
Activity에서 직접 의존하는 것이 아닌 다른 View 클래스에서 의존해서 이동하도록 변경하였습니다!
(MovieAdapter, ReservationButton)

2023-04-18 08:59 UTC, DYGames commented on app/src/main/java/woowacourse/movie/activity/ReservationResultActivity.kt
> +    }
onCreate에서 한가지 일만 하도록 수정하였습니다!

2023-04-18 08:59 UTC, DYGames commented on app/src/main/java/woowacourse/movie/domain/Count.kt
> +    }
연산자 오버로딩을 활용하여 가독성을 높였습니다!

2023-04-18 09:00 UTC, DYGames commented on app/src/test/java/woowacourse/movie/domain/discountPolicy/MovieDayTest.kt
> +    }
ParameterizedTest를 이용해 모든 경우에 대해 테스트를 진행했습니다!

2023-04-18 09:01 UTC, DYGames commented on app/src/test/java/woowacourse/movie/domain/discountPolicy/OffTimeTest.kt
> +    fun `11시 이후, 20시 이전일 경우 2000원 할인이 적용되지 않는다`() {
조건을 나누어 테스트 함수를 분리하였습니다!

2023-04-18 09:02 UTC, DYGames commented on app/src/test/java/woowacourse/movie/domain/movieTimePolicy/WeekdayMovieTimeTest.kt
> +    fun `평일이 아니라면 null을 반환한다`() {
함수명과 구현부를 일치시키도록 변경하였습니다! 도메인 구조를 변경하는 과정에서 인지하지 못했습니다.

2023-04-18 13:49 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-04-18 13:49 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/activity/MovieReservationActivity.kt
> +            savedInstanceState = savedInstanceState, movie = movie, timeSpinner = timeSpinner
```suggestion
            savedInstanceState = savedInstanceState, 
            movie = movie, 
            timeSpinner = timeSpinner
```
가로로 길어지는 경우에는 콤마 단위로 개행하시면 한 눈에 보기 편해집니다.

2023-04-18 13:49 UTC, BeokBeok commented on app/src/main/java/woowacourse/movie/view/MovieAdapter.kt
> +        val intent = Intent(context, MovieReservationActivity::class.java)
```suggestion
        val intent = Intent(context, MovieReservationActivity::class.java)
```
제가 설명이 부족한 것 같네요. 😭 
제가 의도한 것은, Intent를 생성할 때 MovieReservationActivity 클래스명이 변경되더라도 MovieAdapter 에서는 수정하지 않도록 변경하는 것이였어요. 
즉, MovieReservationActivity에 메시지를 보내서 인텐트를 얻어오도록 개선하는 것입니다. 🙏  (이하 관련 내용 동일)

2023-04-18 13:49 UTC, merged