[베르] 3, 4 단계 영화 티켓 예매 제출합니다.
woowacourse/android-movie-ticket pull request #40
Opened 2023-04-22 13:46 UTC by SeongHoonC

페로로님 안녕하세요! 
3, 4 단계 미션 제출합니다.
리뷰 잘부탁드립니다! ㅎㅎ

2023-04-22 15:31 UTC, laco-dev requested changes
먼저 가볍게, 패키지 관련된 정리가 한번 필요할 것 같아서 내용을 남겨드렸습니다.
다른 내용은 이어서 확인할 예정이니 우선 패키지 관련 피드백을 먼저 확인 해주시면 되겠습니다.

2023-04-22 15:31 UTC, laco-dev commented on settings.gradle.kts
> +include(":lib")
lib 라는 모듈은 무엇일까요?

2023-04-22 15:31 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/model/Ticket.kt
> +package woowacourse.movie.model
모델 별로 패키지가 이것저것 섞여 있는 것 같습니다.

```
woowacourse.movie.presentation.Model
woowacousre.movie.presentation.model.Model
woowacourse.movie.model.Model
```

우선 멀티 모듈을 구성할 때에는 앱 패키지를 기준으로 뒤에 이어서 붙여 나가는 형태가 맞습니다.
따라서 이전과 같이 패키지를 유지 해 주시는 것이 좋겠습니다.

`woowacourse.movie` // app 모듈의 기본 패키지
`woowacourse.movie.presentation.model.**` // UI 모듈의 모델 패키지
`woowacourse.movie.presentation.**` // UI 관련 패키지 
`woowacourse.movie.domain.**` // domain 관련 패키지
`woowacourse.movie.domain.model.**` // domain 모듈의 모델 패키지
`woowacourse.movie.data.XXXData` // Data 관련

2023-04-22 15:31 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/ChoiceSeatActivityTest.kt
> +package woowacourse.movie
테스트 코드도 프로덕션 코드와 동일한 패키지에 위치 해주시면 되겠습니다.

2023-04-22 15:31 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/ScreeningTimes.kt
> +package woowacourse.movie
도메인 모듈의 model 패키지와 아닌 것은 어떤 차이가 있는걸까요?

2023-04-23 02:48 UTC, SeongHoonC commented on settings.gradle.kts
> +include(":lib")
모듈 분리하다가 잘못 눌러서 들어간 것 같습니다..ㅎㅎ;;

2023-04-23 02:50 UTC, SeongHoonC commented on domain/src/main/java/woowacourse/movie/ScreeningTimes.kt
> +package woowacourse.movie
model 에 대한 이해가 많이 부족하네요. 
다시 생각해보니 Ticket 과 Movie 만 model 에 있어야 할 것 같아서 분리했습니다.
이것도 확신이 없네요.

2023-04-23 03:44 UTC, laco-dev requested changes
3, 4단계 미션 잘 해주셨습니다.
UI 레이어에서도 패키지 관련한 고민을 한번 더 하실 때가 되었습니다. 😅 

또한 다음 미션에서도 영화 관련한 도메인을 사용하는 만큼 잘 잡아주고 가면 좋을 것 같아서 
충분히 고민 후 도전 해 보시면 좋겠습니다.

2023-04-23 03:44 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/domain/rules/ScreeningTimes.kt
> +package woowacourse.movie.domain.rules
패키지 어렵죠 😢 
우선은 저라면, 도메인에 있는 모든 구현하신것은 전부 `domain.model` 아래에 있어야 한다고 보기는 합니다.

사실 패키지를 나누는 것은 정답이 없기는 합니다
다만! 아래 예시에 있는 것의 나누는 기준이 2가지 이상 섞이지 않도록 하는게 중요합니다.

https://5takoo.tistory.com/156

2023-04-23 03:44 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/SeatGrade.kt
> +    }
할인 정책, 할인 기준을 동적으로 결정하도록 만든 것 처럼
좌석에 대한 등급도 동적으로 결정하도록 만들어 보면 어떨까요?

가령 지금 구현에서는 A행이 S등급으로 바뀌어야 한다면 위 작성한 코드와 테스트가 수정되어야 합니다.

2023-04-23 03:44 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/Seats.kt
> +    private val _value = seats.toMutableList()
동일한 좌석이 2개 이상 존재하지 않도록 하려면 어떤 자료구조를 활용 해 볼 수 있을까요?

2023-04-23 03:44 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/Seats.kt
> +        println(_value)
테스트 목적으로 추가된 것 같은데 prinln() 코드는 제거 해 주세요

2023-04-23 03:44 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/Seats.kt
> +        )
Seat 클래스를 Comparable을 구현하도록 만들어 보면 어떨까요?

2023-04-23 03:44 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/Seats.kt
> +                getDiscountedMoney(seat.getPrice(), discountPolicy, dateTime).value
할인 정책을 고려한 실제 좌석의 가격 계산은
좌석이 해야할 책임일까요? 
좌석들이 해야할 책임일까요?
아니면 티켓이 해야할 책임일까요?

2023-04-23 03:44 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/Theater.kt
> +class Theater(private val seats: Map<Location, SeatGrade>) {
지금의 구현 설계대로라면, 극장이 Seats를 가지고 있어야 하지 않을까요?

2023-04-23 03:44 UTC, laco-dev commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/Theater.kt
> +class Theater(private val seats: Map<Location, SeatGrade>) {
손님이 예매하기 위한 협력 관계는 무엇일까요?

```
손님 --> 좌석을 예매한다 --> (누가?) --> (협력) --> (협력)
```

그렇다면 이 좌석을 예매한다는 협력은 누구의 역할로 봐야 좋을까요?
만약 극장에서 좌석들을 관리하고 있는데 어떤 좌석에 직접적으로 접근해서 데이터를 변경하면 어떤 문제가 있을까요?

2023-04-23 03:44 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/presentation/ChoiceSeatActivityTest.kt
> +        }
Activity에 Intent 데이터를 넣어줄 경우에도 객체지향 관점에서 주도적으로 하도록 만들 수 있습니다.
일반적으로도 많이 사용되는 전략으로 아래 내용을 참고 해보세요

https://github.com/PRNDcompany/android-style-guide/blob/main/Java.md#activity

2023-04-23 03:44 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/presentation/ChoiceSeatActivityTest.kt
> +        val title = onView(withId(R.id.textChoiceTitle))
given이라는 동작이 맞을까요?
Given은 "현재 영화" ReservationModel이 아닐까요?

따로 given이 없다면 명시하지 않아도 괜찮습니다.
```kotlin
// given: nothing
// given: 해리포터

// when & then
title.check(matches(withText(movie.title))
```

2023-04-23 03:44 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/presentation/ChoiceSeatActivityTest.kt
> +    fun 티켓_개수가_2일때_1개만_선택하면_확인_버튼이_비활성화_된다() {
given에 대해서 TicketCount를 고정 해 놨기 때문에 모든 테스트가 티켓 개수 2를 기준으로 사용하고 있습니다.
또한 이 테스트에서 given이 직접적으로 드러나지 않아서 왜 2개지? 라는 의문을 가지고 시작해야 합니다.

각 테스트 환경마다 필요한 내용을 준비하도록 할 수 있지 않을까요?


```
// given
// 아래 setIntent 개념이 실제로 동작하는지는 확인해보지 못했습니다!
activity.setIntent(given)

// when & then
...
```

2023-04-23 03:44 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/presentation/ChoiceSeatActivityTest.kt
> +    }
좌석을 클릭한 경우 좌석에 대한 가격을 테스트로 잘 작성을 해 주셨습니다.

다만, UI 테스트에서 비즈니스 로직의 결과인 "가격"을 그대로 노출하게 된다면,
비즈니스 로직이 변경되면 UI 테스트가 실패하게 됩니다.

가령 A행의 티켓이 S등급으로 변경된다면? UI 테스트가 터집니다.
그렇다면, 이러한 상황에서는 어떻게 테스트를 할 수 있을까요?

> 힌트 : 티켓의 가격은 단위 테스트로 검증이 되었기 때문에 UI 테스트에서는 UI에 노출하는 부분에만 집중해 볼 수 있습니다.
(가격이 얼마인지는 관심 없는데 0원은 아님)

2023-04-23 03:44 UTC, laco-dev commented on app/src/main/AndroidManifest.xml
> +            android:name=".presentation.activity.CompletedActivity"
UI 레이어의 패키지를 구성할 때에도 어떤 기준으로 나누는지가 중요합니다.
기능 단위로 나눌 것인지, 화면 단위로 나눌 것인지 등에 대한 내용이 될 수 있습니다.

다만 일반적으로 화면에 관해서는 화면별로 나누는 것이 권장됩니다.
만약 예매 완료 라는 화면이 별도 모듈로 분리가 되어야 한다면, 패키지 하나만 옮겨지는 것과
패키지별로 필요한게 다같이 옮겨지는 차이가 있습니다.

```
.presentation.complete.**
.presentation.booking.**
.presentation.main.**
```

2023-04-23 03:44 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/presentation/model/MovieItemModel.kt
> +abstract class MovieItemModel
모든 리사이클러뷰 아이템이 ItemUI를 구현 해야만 한다는 것을 까먹지 않을 수 있을까요?
영화 목록에서 사용하기 위한 아이템 타입은 아래와 같이 나타낼 수 있지 않을까요?

```
영화 목록 아이템 
   - 영화 아이템
   - 광고 아이템
```

sealed class 를 활용 해 볼 수 있습니다.

```kotlin
sealed class MovieItem {
   data class Ad(...)

   data class Movie(movie)
}
```

2023-04-23 03:44 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/presentation/util/SeatsFormat.kt
> +    this.map { "${it.row}${it.number}" }
정말 유틸리티가 맞을까요..?
예매 결과에서만 사용되는 포맷으로 볼 수 있지 않을까요?

하나 둘씩 유틸리티에 넣다보면 무서운 일이 발생할 수 있습니다.. 😱

2023-04-23 03:44 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/presentation/viewholder/MovieViewHolder.kt
> +        movie.thumbnail?.let { thumbnail.setImageResource(it) }
만약 thumbnail이라는 데이터가 처음에는 있었다가 나중에 null로 바뀌면
이미지 뷰에는 어떤 변화가 있을까요?

2023-04-23 03:44 UTC, laco-dev commented on app/src/main/res/drawable/selector_seat_item.xml
> +    <item android:drawable="@drawable/shape_not_selected_color" android:state_selected="false" />
기본 상태는 별도로 추가하지 않아도 됩니다.
하지만 선언한 순서대로 우선순위가 결정되니 가장 하단에 위치 해 주시면 됩니다.
```
<item>
   <...>
</item>
```

2023-04-24 01:02 UTC, SeongHoonC commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/Seats.kt
> +                getDiscountedMoney(seat.getPrice(), discountPolicy, dateTime).value
좌석과 dateTime 모두 티켓이 가지고 있어서 본래 티켓이 해야할 책임이라고 생각합니다. 다만
> 좌석을 선택하면 배경색이 바뀌고, 하단에 할인정책과 좌석 등급을 고려한 최종 가격이 표시된다.

라는 요구사항에 때문에 티켓과 좌석 모두 할인 정책을 적용할 필요가 생겼습니다.
따라서 좌석들(Seats)이라는 클래스를 만들고 책임을 위임하였습니다.

Seats 의 메서드가 LocalDateTime 을 받아서 실제 가격을 계산하는 것도 이상하고
좌석이나 티켓의 책임은 아니라고 생각합니다.

따라서 좌석들을 가지고 계산하는 추가 클래스가 필요할 것 같습니다.

2023-04-24 02:56 UTC, SeongHoonC commented on domain/src/main/java/woowacourse/movie/domain/tools/seat/Theater.kt
> +class Theater(private val seats: Map<Location, SeatGrade>) {
Theater 이 seats 를 private 로 하여 극장에 좌석에 직접 접근 불가능하게 만들었습니다.
불변이기 때문에 문제가 발생하지 않을 것이라 생각합니다.

하지만 사용자가 여러 명이면 예매 좌석이 중복되지 않게 해야합니다.
그럴 땐 seat를 넣거나 빼는 작업이 일어날 때 마다 함수형 프로그래밍으로 극장 객체를 새로 만들어 반환하는 방법이 좋을 것 같습니다.
그런 구조라면 협력은 (티켓 발급기 혹은 계산원)의 역할이고 추가해야 할 것입니다.

2023-04-24 05:25 UTC, SeongHoonC commented on app/src/main/java/woowacourse/movie/presentation/viewholder/MovieViewHolder.kt
> +        movie.thumbnail?.let { thumbnail.setImageResource(it) }
thumbnail 이 없으면 null 이라 let 이 받는 람다가 실행되지 않습니다.
그래서 이미지가 업데이트 되지 않습니다.

<img width="159" alt="image" src="https://user-images.githubusercontent.com/108349655/233902264-cd68547d-0a93-4ed5-aa48-7b862f53212c.png">

MovieModel 에 thumbnail, poster 가 없으면 default image 를 가지도록 변경하였습니다.

2023-04-24 12:10 UTC, laco-dev approved these changes
피드백 반영하느라 고생 많으셨습니다.

기존 레벨 1과 달리 여러개의 컨트롤러(화면)가 존재하기 때문에 도메인 로직의 상태 관리가 발목을 잡아서 도메인 구현이 더 어려워졌을거라 생각이 듭니다.

남겨드린 내용은 다음 미션을 진행하면서 도메인을 어떻게 적용할지 적용할 때 참고 해 보시면 좋겠습니다. 💪🏻

2023-04-24 12:11 UTC, merged