[둘리] 3, 4 단계 영화 티켓 예매 제출합니다.
woowacourse/android-movie-ticket pull request #47
Opened 2023-04-23 11:40 UTC by hyemdooly

안녕하세요, 말리빈! 둘리입니다.☺️
좌석 선택 기능을 추가하면서 도메인 코드가 많이 추가되고 수정되었습니다!
row, col을 기준으로 5*4 좌석 뿐만 아니라 다양한 크기의 좌석들도 호환되도록 고려하여 도메인을 작성했는데, 뷰에서는 아직 해결하지 못했습니다.. 주말 내내 고민했는데 어떻게 해결해야할지 아직 잘 모르겠습니다🥲

다음 미션 시작날이 얼마 남지 않아 마감일보다 조금 더 빨리 제출합니다!
날카로운 피드백 부탁드립니다!

2023-04-23 13:21 UTC, malibinYun requested changes
3, 4단계 미션 고생 많으셨어요 :)
리사이클러뷰의 어뎁터 코드가 굉장히 재미있었습니다 ㅎ_ㅎ
고민해보면 좋을 점들에 코멘트 남겨두었으니 확인해주세요 :)
피드백 반영 후 다시 리뷰 요청 부탁드려요~

2023-04-23 13:21 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/movielist/MovieListAdapter.kt
> +        }
처음에 굉장히 당황을 많이 했네요.... ㅋㅋㅋㅋㅋㅋ
이 어뎁터가 어떻게 동작하는 지 너무 신기해서 디버그 해보니 광고 뷰가 영화 정보 view를 들고 있었군요!!!

보여 주어야할 다른 View 유형이 생긴다면 어떻게 될까요?
경우에 맞는 모든 xml을 만들어주어야 할까요?

이곳에서도 단일 책임 원칙은 여전히 유효합니다 :)
ViewHolder 및 xml View 조차도 이런 원칙을 지켜보세요 🙂


보여주어야할 항목을 sealed class 등으로 묶어봐도 좋겠네요 :)

2023-04-23 13:21 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/movielist/MovieListAdapter.kt
> +        return NORMAL_VIEWTYPE
광고 배치의 규칙이 변경된다면 유연하게 변경될 수 있을까요?

2023-04-23 13:21 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/seatselect/SeatSelectActivity.kt
> +        if (isDataNull(title, dateTime, count)) {
전달 받는 객체를 한 개로 묶어서 전달 받으면 isDataNull 같은 함수를 만들지 않아도 되겠네요 :)

2023-04-23 13:21 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/seatselect/SeatSelectActivity.kt
> +        seatView.set(title!!, dateTime)
!! 연산자의 사용을 지양해주세요.
코틀린의 non-null 특장점을 발휘 하지 못하는 케이스입니다 :)

2023-04-23 13:21 UTC, malibinYun commented on domain/src/main/java/woowacourse/movie/domain/system/SelectResult.kt
> +    object MaxSelection : SelectResult()
이벤트를 sealed class을 활용해 만들어주셨네요 👍

2023-04-23 13:21 UTC, malibinYun commented on domain/src/test/java/woowacourse/movie/domain/SeatSelectSystemTest.kt
> +
테스트 코드에 if문이 들어있는 것은 좋은 패턴이 아닙니다.
테스트 코드가 if를 통과하지 않고, else를 통과하면 테스트는 성공일까요 실패일까요?
콘솔에는 어떻게 나타날까요?

2023-04-23 13:21 UTC, malibinYun commented
> row, col을 기준으로 5*4 좌석 뿐만 아니라 다양한 크기의 좌석들도 호환되도록 고려하여 도메인을 작성했는데, 뷰에서는 아직 해결하지 못했습니다.. 주말 내내 고민했는데 어떻게 해결해야할지 아직 잘 모르겠습니다🥲

동적인 View를 만드는 것은 사실 쉬운 일이 아니에요.
너무 어렵고 시간이 많이 든다면 꼭 반영하지 않으셔도 됩니다.
미션 목표에 더 집중하셔도 좋겠어요 :)

2023-04-24 05:10 UTC, hyemdooly commented on app/src/androidTest/java/woowacourse/movie/MovieDetailActivityTest.kt
> +
```kotlin
val intent = Intent(ApplicationProvider.getApplicationContext(), MovieDetailActivity::class.java)
intent.putExtra(MovieDetailActivity.MOVIE_KEY, movieModel)
activityScenario = ActivityScenario.launch(intent)
```
각 테스트에서 다음과 같이 intent 내용을 지정하여 launch로 실행해줄 수 있습니다!
더 나아가 함수로 분리하여 데이터를 인자로 받아 intent를 리턴해줄 수 있을 것 같습니다. :)

2023-04-24 05:28 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/InjectedModelListener.kt
> +}
모델을 다른 액티비티에 전달하는 리스너 형태가 많아져서 생성한 것이 맞습니다.ㅎㅎ

말씀대로 인터페이스 이름이 한 눈에 알아볼 수 있는 이름이 아닌 것 같습니다.ㅜㅜ 이름 짓기 어렵네요..
그리고 지금처럼 이 T만 다른 Listener 구현이 여러 개 필요할 때, Activity에서 모두 implement할 수도 없습니다!
고차함수로 받는 것이 더 좋은 방법일까요?🤔

2023-04-24 05:40 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/moviedetail/ReservationInfoView.kt
>      fun set(savedInstanceState: Bundle?, movie: MovieModel) {
Bundle의 내용이 변경될 경우 ReservationView에서 많은 부분을 함께 변경해주어야합니다!
데이터를 세팅할 때 필요한 값만 넘겨주는 것이 Bundle의 의존을 막을 수 있을 것 같아 데이터 값을 받도록 수정했습니다.

2023-04-24 05:46 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/moviedetail/ReservationInfoView.kt
>              it.context.startActivity(intent)
다른 코드와 동일하게 intent를 넘겨 고차함수로 빼주었습니다!

2023-04-24 05:54 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/movielist/MovieListActivity.kt
> +class MovieListActivity : AppCompatActivity(), InjectedModelListener<MovieModel> {
위에서도 말씀드렸듯이 여러개가 필요한 경우에는 상속으로 해결하지 못합니다..ㅠㅠ
따로 구현하자니 context를 넘겨주는 것이 꺼려져서 고차함수로 수정했는데요!
다른 방법이 있을까요? 고차함수로 수정하니 정형화해주지 못한 것 같아서 고민됩니다.

2023-04-24 05:59 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/movielist/MovieListActivity.kt
> +    }
이런 간단한 방법이 있었군요... 수정했습니다!

2023-04-24 06:11 UTC, hyemdooly commented on domain/src/test/java/woowacourse/movie/domain/SeatSelectSystemTest.kt
> +
if문을 통과하지 않은 경우 성공으로 나오는 것을 확인했습니다😱
클래스 타입을 확인하고 가격을 확인하도록 수정했습니다!

2023-04-24 06:29 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/seatselect/SeatSelectActivity.kt
> +        if (isDataNull(title, dateTime, count)) {
객체를 생성해서 함수를 삭제했습니다!

2023-04-24 06:30 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/seatselect/SeatSelectActivity.kt
> +        seatView.set(title!!, dateTime)
객체를 생성하여 null값을 체크하면서 !! 연산자도 지웠습니다!

2023-04-24 07:58 UTC, malibinYun commented on app/src/androidTest/java/woowacourse/movie/MovieDetailActivityTest.kt
> +
`@BeforeEach` 를 활용해보세요 :)

2023-04-24 08:26 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/InjectedModelListener.kt
> +}
클릭했을 때 intent를 생성하고 싶으면 packageContext가 필요해서 넘겨주어야한다고 생각했습니다!

2023-04-24 08:28 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/movielist/MovieListAdapter.kt
> +        }
movie list의 index 때문에 그렇게 구현했는데, 다시 생각해보니 position에 따른 index를 다시 계산해주면 되는거였네요...!🫠
sealed class를 생성하여 view holder를 여러개 구현했고, view type도 enum class로 정의했습니다!

2023-04-24 08:29 UTC, hyemdooly commented on app/src/main/java/woowacourse/movie/activity/movielist/MovieListAdapter.kt
> +        return NORMAL_VIEWTYPE
enum class ListViewType에서 광고 아이템 주기를 입력 받아 Type을 리턴하는 getViewType을 작성했습니다!

2023-04-24 14:53 UTC, malibinYun approved these changes
미션 고생 많으셨어요 :)
저와 함께 소통한 내용이 앞으로 개발하실 때 도움이 되셨으면 좋겠네요 🙂
미션은 이만 머지하겠습니다.
다른 미션들도 잘 마무리하시길 응원할게요! 💪

2023-04-24 14:53 UTC, malibinYun commented on app/src/androidTest/java/woowacourse/movie/MovieDetailActivityTest.kt
> +    ).toPresentation(R.drawable.img)
Movie가 변경되면 이 테스트 코드 크래시가 나겠네요 :)
Movie class와는 거의 상관 없는 이 테스트가 문제가 생기면 꽤나 당황스러울 게 예상되네요 🙂

테스트에는 정말 필요한 의존 관계만 갖게 작성해보세요 :)

2023-04-24 14:53 UTC, malibinYun commented on app/src/androidTest/java/woowacourse/movie/MovieDetailActivityTest.kt
> +}
> JUnit4에서 `@Before`는 파라미터를 받을 수 없고, 안드로이드에서는 JUnit4를 사용해야하는데 다른 방법이 있을까요?!

Before를 통해 클래스 필드를 공통적으로 선언해주고,
특정 테스트 메서드에서만 해당 필드를 필요한 데이터로 변경해줄 수 있겠지요 :)

2023-04-24 14:53 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/moviedetail/MovieDetailActivity.kt
> +        val intent = Intent(this, SeatSelectActivity::class.java)
클릭되었을 때는 알겠는데, 메서드가 무슨 일을 하는 지는 구현을 전부 보아야 파악할 수 있겠네요 :)
메서드 자체가 무슨 일을 하는 지 이름을 지어주는 것은 어떨까요?

2023-04-24 14:53 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/moviedetail/ReservationInfoView.kt
> +) {
무엇이 클릭 되었을 때인지도 나타내주면 좋겠네요 :)
on"What"Click

2023-04-24 14:53 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/movielist/CustomViewHolder.kt
> +sealed class CustomViewHolder(view: View) : RecyclerView.ViewHolder(view) {
ViewHolder에 sealed class를 활용하셨네요 👍
CustomViewHolder란 이름은 좀 더 고민해보면 좋겠네요 :)

2023-04-24 14:53 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/movielist/ListViewType.kt
> +    AD_VIEWTYPE, NORMAL_VIEWTYPE;
이 View Type 정보는 어딘가로 응집할 수 있어 보이네요 :)

2023-04-24 14:53 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/movielist/MovieListAdapter.kt
> +    private val movies: List<MovieModel>,
다른 n개 종류의 ViewHolder가 표시되고, 이 View 또한 고유의 interval이 생긴다면 어떨까요?

이러한 데이터 종류를 다형성으로 묶어서 한 번에 List로 넘겨보는 방법에 대해서 고민해보세요 :)

2023-04-24 14:53 UTC, merged

2023-04-24 14:54 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/InjectedModelListener.kt
> +}
intent 를 생성해주는 것은 메서드를 넘겨주는 곳에서 만들게 하는 건 어떨까요?

람다와 크게 다르지 않습니다 :)
fun interface 에 대해 학습해보시면 더 이해가 높아질 거예요 🙂

2023-04-24 14:54 UTC, malibinYun commented on app/src/main/java/woowacourse/movie/activity/movielist/MovieListActivity.kt
> +class MovieListActivity : AppCompatActivity(), InjectedModelListener<MovieModel> {
람다의 타입에 typealias로 이름을 붙여줄 수는 있겠지만,
위에서 말씀드린 인터페이스를 넘기는 방법으로 시도해보셨으면 좋겠네요 :)

2023-04-30 14:57 UTC, malibinYun commented on app/src/androidTest/java/woowacourse/movie/MovieDetailActivityTest.kt
> +
이 부분은 제가 `ServiceTestRule`과 착각해서 각 activity를 실행시킬 때마다 다른 intent를 넘겨줄 수 있을 것으로 잘못 생각했어요.

`ActivityScenarioRule`에는 해당 메서드가 존재하지 않네요. 내부를 잘 들여다보니, 생성자로부터 intent를 한 번 넘겨주면 해당 intent로 액티비티를 실행시켜버려서 바꿀 방법이 없네요. 혼동을 드려서 죄송해요 😥그

그래도 방법이 없을까, 고민을 많이 해봤는데요, 꽤나 어려운 방법일 것 같아서 방법만 공유해봅니다 😅

Rule class는 사실 before, after에 미리 해야 할 일을 모아 둔 별 거 없는 class 랍니다. `ActivityScenarioRule`는 `ExternalResource`를 상속 받고 있어요. 그래서 테스트를 실행할 때 `@Before` 붙어있는 메서드를 자동으로 실행해 주듯이, 이 내부에서도 실행시켜주어요 :)

`ActivityScenarioRule`의 내부는 생각보다 매우 간단한데요, 4개의 생성자를 통해 여러 동작을 지원하고, 해당 동작을 매 테스트 때마다 before를 통해 실행시켜줍니다.

다행스럽게도 내부에서 사용하는 `ActivityScenario` class는 public 이에요. 그렇기에 이 Rule class를 참고하고, intent 객체를 lazy하게 가져오게 만드는 기능을 추가해서 직접 Rule class를 만들어내면 충분히 intent를 교체할 수 있게 되어요.

`ActivityScenarioRule`이 final class 여서 상속을 받아 개조하는 방법은 통하지 않겠더라구요.

이 부분은 꼭 시도해보시지 않아도 좋아요.

간단히 접근할 수 없는 부분이었는데, 쉽게 접근할 수 있는 분야처럼 말씀드려 혼란을 드린 거 같아 죄송한 마음이에요.

많은 고민을 하셨지만 답을 찾지 못해 답답하실 것 같아서, 해결 방법 중 하나를 대신 고민해서 공유드려요 :)

2023-04-30 18:17 UTC, hyemdooly commented on app/src/androidTest/java/woowacourse/movie/MovieDetailActivityTest.kt
> +
이번 미션 기간에 여유가 생기면 같이 공부해보겠습니다ㅎㅎ
리뷰가 끝났는데도 이렇게 답변 주셔서 정말정말 감사합니다~~!! ☺️