[영화 티켓 예매] 빙티 1, 2단계 미션 제출합니다.
woowacourse/android-movie-ticket pull request #57
Opened 2024-04-17 07:08 UTC by s6m1n

안녕하세요 페로로😊 레벨 2 영화 티켓 예매 미션의 리뷰이로 매칭된 빙티입니다.
액티비티에서 뷰와 컨트롤러를 분리하기 위해 MVP 리팩터링을 시도해봤습니다.
부족함 많은 코드지만 잘 부탁드리겠습니다!

2024-04-17 11:52 UTC, laco-dev requested changes
하루 빨리 미션을 완료해서 기대를 많이 했습니다!
하지만 구현을 절반만 해주셨네요 😅 

레벨 1에서 비즈니스 로직. 도메인 로직에 대한 학습을 다뤘습니다.
하지만 아무런 도메인 로직이 작성되어 있지 않아요.
*마찬가지로 단위 테스트가 존재하지 않아요.

레벨 2는 단순히 주어진 디자인 대로 UI만 그리는 것이 아닌. 레벨 1을 기본으로 진행하게 됩니다.

영화 티켓 예매 프로그램이라는 도메인 모델을 구현하고 다시 리뷰 요청 해주세요.
*리뷰를 하면서 중간에 발견하여 모든 내용을 확인하지 않았습니다.

2024-04-20 02:16 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/main/MainActivity.kt
> +    }
재활용할 수 있는 convertView가 없는 경우에만 view를 새롭게 inflate 하고 viewHolder에서 findViewById를 호출하도록 개선했습니다!

2024-04-20 03:07 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/main/MainContract.kt
> +    }
처음에는 Controller가 View와 Model을 모두 알고 흐름을 제어했던 것처럼,
Controller를 대체하는 Presenter도 능동적으로 View와 Model에 요청을 하는 객체라고 생각했습니다.
그러나 곰곰히 생각해보니 프로그램 흐름이 View로 들어오는 `입력`에 의해 결정되고 있습니다.
Presenter는 View로 들어온 입력에 대해 적절한 요청(Model의 데이터 가공 및 View로 전달)을 처리하는 수동적인 객체로 여겨집니다.
따라서 Presenter가 뷰의 세부적인 상태를 알 필요는 없기에 좀 더 일반적인 onStart라는 이름으로 변경했습니다!

2024-04-20 03:22 UTC, s6m1n commented on app/src/androidTest/java/woowacourse/movie/ReservationActivityTest.kt
> +    }
수량 기본 값에 대한 테스트를 추가하였습니다!

2024-04-20 03:30 UTC, s6m1n commented on app/src/androidTest/java/woowacourse/movie/MainActivityTest.kt
> +    }
화면간의 이동도 테스트가 필요한 기능이라고 생각했는데, UI 테스트는 하나의 액티비티에만 국한되는 것이었군요...
그렇다면 이런 경우는 사람이 일일이 직접 이벤트를 발생시키며 화면 전환이 잘 이뤄지는지 검증하는 방법밖에 없는지 궁금합니다!🤔

2024-04-20 06:28 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/main/MainContract.kt
> +    }
처음에는 Controller가 View와 Model을 모두 알고 흐름을 제어했던 것처럼, Controller를 대체하는 Presenter도 능동적으로 View와 Model에 요청을 하는 객체라고 생각했습니다.
그러나 곰곰히 생각해보니 프로그램 흐름이 View로 들어오는 `입력`에 따라 결정되고 있으며 Presenter는 View의 요청을 받아 적절한 작업을 수행하는 수동적인 객체로 여겨집니다!
Presenter는 Contract 인터페이스로 View와 통신할 뿐, 뷰의 세부적인 상태를 알 필요는 없다고 느껴 좀 더 일반적인 onStart라는 이름으로 변경했습니다.

2024-04-20 06:29 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/model/Movie.kt
> +) : Serializable
영화 예매에 필요한 도메인과 단위 테스트를 추가했습니다!

2024-04-20 13:09 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/MainActivityTest.kt
> +    }
단위 테스트 환경에서 콘솔에 입력한 값이 잘 동작하는지 매번 확인하지 못했었죠..?
하지만, 어떠한 값이 만들어 질 것이다 라는 것을 가정하고 진행하기도 했습니다.

마찬가지로 화면이 이동하는 것은 한 화면의 UI 테스트를 한 다기 보다는 시나리오 테스트 관점으로 접근을 해야 합니다.
앱이 시작부터 어떠한 과정을 거쳐 최종 목작지에 도착하는 것 까지 하나의 시나리오를 그리는 것이죠.

UI Automator나 appium과 같은 자동화 테스트가 이러한 예시인데
현재는 이런게 있다 정도로만 우선 판단 해 주시고, 단위 테스트가 다른 객체를 테스트 하지 않는 것 처럼, UI 테스트도 해당 화면에 대한 테스트를 수행하는데 집중한다고 봐주시면 됩니다.

2024-04-20 14:54 UTC, laco-dev requested changes
좋습니다.

UI 테스트가 복잡하고 어렵기 때문에 아키텍처가 생겨나고, 그에 맞게 프레젠터를 테스트 할 수 있게 된다는 사실을 아시나요?

이 내용을 이해하는 것이 이번 1 주차의 핵심 주제랍니다.

2024-04-20 14:54 UTC, laco-dev commented on app/src/main/res/values/strings.xml
> +    <string name="running_time_prefix">러닝타임:&#160;</string>
strings 리소스에 파라미터를 전달받아 출력하는 방법이 있어요. `%d` 와 같은 값

2024-04-20 14:54 UTC, laco-dev commented on app/src/test/java/woowacourse/movie/model/ReservationTest.kt
> +    fun `예약은 스스로 총 가격을 계산할 수 있다`() {
> 예약은 스스로 총 가격을 계산할 수 있다

위 이름은 그래서 가격이 얼마로 결정되는지에 대한 정보가 드러나지 않아요.

> 티켓의 가격이 13,000원일 때 3장을 구매하면 총 가격은 39,000원이다.

2024-04-22 07:17 UTC, s6m1n commented on app/src/main/res/layout/activity_reservation_completed.xml
> +        android:text="영화 상영 시작 시간 15분 전까지\n취소가 가능합니다"
혼용해서 사용하고 있었는데 통일성을 위해 나름의 기준을 세워 수정했습니다😅
영화 제목, 상영일처럼 model에서 값을 받아오는 것들은 tools:text로 미리보기 텍스트를 넣어주었고,
위 안내 메시지처럼 변동이 적은 경우에는 android:text는 string 리소스로 분리해주었습니다!

2024-04-22 07:23 UTC, s6m1n commented on app/src/main/res/layout/activity_reservation.xml
> +                </LinearLayout>
빠뜨린 부분 지적 감사합니다👍
이번 미션을 진행하며 LinearLayout과 ConstraintLayout을 혼용했는데, 페어는 LinearLayout에 익숙하고 저는 ConstraintLayout에 익숙해 모두 사용해보기 위함이었습니다.
간단한 레이아웃에는 LinearLayout으로도 충분했지만 복잡한 레이아웃에는 뷰 그룹이 중첩되며 코드의 가독성이 떨어진다고 느꼈습니다.
따라서 LinearLayout로 작성된 기존의 xml들을 ConstraintLayout으로 통일해 depth를 줄여주었습니다!

2024-04-22 08:31 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/screen/main/MainActivity.kt
> +        val movieListView = findViewById<ListView>(R.id.list_view)
by lazy 블럭에서 findViewById를 사용해 초기화 시 한 번만 호출되도록 수정했습니다.
그러나 by lazy는 프로퍼티의 호출 위치에 따라 초기화 되지 않았을 때 접근할 수 있는 경우가 있어 불안정하다고 들었습니다..
이 점 때문에 lateinit 키워드를 사용할까 생각했지만, var도 가변 변수이므로 완전히 안전한 방법은 아니라고 생각이 됩니다!
페로로는 이런 상황에서 보통 어떤 방식을 선호하시는지 궁금합니다 :)

2024-04-22 08:59 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/screen/reservation/ReservationContract.kt
> +        fun initializeMovieDetails(movie: Movie)
뷰에 보여질 초기 값들을 넣어주는 기능은 initialize로, 이 외에 setOnClickListener와 같은 기타 설정은 setup으로 구별했습니다!
setup 메서드에 문제가 있다면 액티비티가 보여지긴 하지만 원하는 대로 동작하지 않고, initialize는 액티비티가 실행조차 되지 않습니다.
저만의 규칙이라 다른 사람들이 이해하기 어려운 모호한 네이밍이란 생각이 드는데 혹시 관련해서 참고할만한 컨벤션이 있을까요?.?

2024-04-22 09:00 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/screen/reservation/ReservationActivity.kt
> +    }
[여기](https://github.com/woowacourse/android-movie-ticket/pull/57#discussion_r1574349568)와 동일하게 개선해주었습니다!

2024-04-23 16:42 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/screen/reservation/ReservationContract.kt
> +        fun minus()
``` kotlin
fun increaseTicketQuantity()
fun decreaseTicketQuantity()
```
더 구체적인 함수명으로 수정했습니다!

2024-04-23 17:29 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/model/Movie.kt
> +    @DrawableRes val poster: Int,
@DrawableRes와 Serializable을 가진 Movie Ui 모델을 추가하여 도메인 모델에서 View의 연관성을 없애주었습니다!

2024-04-23 18:05 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/model/screening/Screening.kt
> +    val quantity: Quantity,
확실히 수량 정보는 Reservation 클래스에 있는 게 더 자연스러워 보이네요!.!

2024-04-24 13:47 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/adapter/ListViewAdapter.kt
> +    }
Movie를 넘겨주면 객체의 크기에 따라 메모리 비용이 많이 들 수 있지만 정확한 데이터를 넘겨줄 수 있습니다.
position을 넘겨준다면 리스트에서 추가나 삭제 등 수정이 일어났을 때 데이터와 position이 일치하지 않을 위험이 있을 것 같습니다..!
혹시 제가 해석한 게 맞을까요??

2024-04-24 13:55 UTC, s6m1n commented on app/src/androidTest/java/woowacourse/movie/ReservationCompletedActivityTest.kt
> +    }
메서드마다 intent에 각각 다른 값을 담아 가변 프로퍼티 activityScenarioRule에 넣어주면 각 테스트 메서드의 시나리오를 다양하게 할 수 있을 것 같습니다!

2024-04-24 13:57 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/adapter/ListViewAdapter.kt
> +) : BaseAdapter() {
notify 리스트의 데이터나 포지션 등이 바뀌었을 경우 다시 그려달라고 요청하는 메서드 입니다!
생성자로 아이템을 결정하면 리스트가 고정되어 리스트 아이템 변경에 대응하기 어려운 구조가 될 것 같습니다🤔

2024-04-25 12:08 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/adapter/ListViewAdapter.kt
> +    }
넵, 특별히 문제점이 있다거나 하지는 않아요.

`onItemClick = { index -> }`
`onItemClick = { movie -> }`

말씀하신 대로 어떠한 아이템을 선택했는지 다시 찾지 않아도 되는 장점이 있습니다.
둘다 장단점이 있지만, 이러한 방법도 있다 정도로 알려드리고 싶었어요

2024-04-25 12:10 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/screen/main/MainActivity.kt
> +        val movieListView = findViewById<ListView>(R.id.list_view)
아직 Fragment를 학습하기 전이기에 결론부터 말씀드리자면 두 가지 방법 모두다 사용합니다.

프래그먼트에서는 by lazy 를 사용하면 안되기 떄문인데요.
왜 그런지는 이후에 한번 고민 해보세요 !

2024-04-25 12:13 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/screen/reservation/ReservationContract.kt
> +        fun initializeMovieDetails(movie: Movie)
setup, initialize 같은 초기화 함수를 반드시 호출해야 한다라는 설정이 있는 한, 항상 동일한 문제가 발생하는데요.
다른 개발자가 이 함수들을 호출해야 한다는 사실을 알지 못하면 의도치 않은 문제가 발생하게 됩니다.

초기화 자체는 스스로 하도록 만들고, 런타임에 필요한 업데이트 로직을 인터페이스로 만들면 좋습니다.

2024-04-25 12:15 UTC, laco-dev commented on app/src/main/res/layout/activity_reservation.xml
> +                </LinearLayout>
LinearLayout, ConstraintLayout의 문제라기 보다는
뷰그룹에 자식 뷰가 여러개 있을 때, 공통으로 사용해야 하는 여백을 누가 가져야 할지에 대한 질문이었어요 😄 

```
<ViewGroup marginTop=24dp>
</ViedwGroup>

<ViewGroup>
  <View marginTop=24dp>
  <View marginTop=24dp>
</ViewGroup>
```

만약 여백을 수정할 때 두개 다 수정해야 한다는 것을 까먹으면 바로 문제가 되니까요

2024-04-25 13:00 UTC, merged

2024-04-28 02:10 UTC, s6m1n commented on app/src/main/java/woowacourse/movie/feature/main/ui/ListViewAdapter.kt
> +    inner class ViewHolder(val view: View) {
inner 클래스는 자동으로 외부 클래스를 참조하는데, ViewHolder에서 필요한 프로퍼티 외에도 불필요한 참조가 생겨서 메모리 누수가 발생할 수 있을 것 같습니다!