[영화 티켓 예매] 해음 1, 2단계 미션 제출합니다.
woowacourse/android-movie-ticket pull request #58
Opened 2024-04-18 05:33 UTC by haeum808

안녕하세요 페로로!
Android 6기 해음입니다. 잘 부탁드리겠습니다!

2024-04-18 14:07 UTC, laco-dev commented
> ConstraintLayout 안에 ConstraintLayout이 중첩으로 있어야 하는 상황이면 Layout 중첩으로 하는 방법 말고 더 성능 좋고 가독성이 좋은 방법이 있는지 궁금합니다.

ConstraintLayout도 결국 UI를 배치하는 방법중에 하나이기 때문에 중첩 구조가 필요한 상황이라면 더 좋은 방법은 없을 거에요.
다만 이 제약 레이아웃을 사용한다는 것 자체가, 중첩 레이아웃이 불필요하다는 것을 의미할 수도 있지는 않을까요?

2024-04-18 14:49 UTC, laco-dev requested changes
1, 2 단계 미션 고생 많으셨습니다.

MVP 패턴의 구현을 어느정도 따르고 있지만 근본적인 MVP 패턴의 역할 분리가 잘못 되어 있습니다.
조금 더 학습 해 보시고 인터페이스를 어떻게 나누는 것인지 찾아보시면 좋겠습니다.

2024-04-18 14:49 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/TestFixture.kt
> +}
도메인 레벨의 데이터는 일반적인 Fixture가 자주 사용될 수 있지만 화면으로 오면 조금 이야기가 달라집니다.

화면에서 UI를 그리는 방법은 정말 다양합니다.
하지만 이를 단순히 moveisFirstItem이라고 한다고 가정했을 때, 다른 화면에서는 moviesFirstItem의 아이디가 다르다라고 한다면. 바로 문제가 발생하게 됩니다.

이렇게 된다면 여러개의 화면이 사용하는 첫 번 째 아이템의 아이디는 R.id.list_view_reservation_home이다 라는 테스트가 될지도 모릅니다.

2024-04-18 14:49 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/activity/ReservationDetailActivityTest.kt
> +package woowacourse.movie.activity
안드로이드에서 패키지를 나눌 때는, 클래스 이름별로 나누는 것이 아닌 기능 즉 화면별로 나누게 됩니다.
activity 와 같은 패키지에 모아두면 어떤 문제가 있길래 이런 말이 나오는 것일까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/activity/ReservationDetailActivityTest.kt
> +    }
더하기, 빼기라는 각각 1과 2라는 값을 출력한다는 것을 어떻게 증명 할 수 있을까요?
이러한 테스트의 배경에는 기본 값은 1이다 라는 설정이 들어와야 하지 않을까요?

혹은, 여러번의 버튼 클릭을 눌러도 항상 2가 출력된다고 생각할 수도 있습니다.

2024-04-18 14:49 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/activity/ReservationDetailActivityTest.kt
> +    }
https://github.com/woowacourse/android-movie-ticket/pull/58#issuecomment-2063954979

2024-04-18 14:49 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/activity/ReservationFinishedActivityTest.kt
> +    }
이 테스트코드의 어딜 봐야 13000원이라는 가격이 출력된다는 것을 알 수 있을까요?
이 화면은 항상 13,000이라고 출력하는 것이라고 생각할 수도 있지 않나요?

"given, when, then" 이라는 흐름을 잘 나타내고 있나요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/adapter/MovieCatalogAdapter.kt
> +    private val movies: List<Movie>,
어댑터 클래스에는 데이터 상태가 변경되었음을 알리는 notifyXXX() 형태의 메소드를 제공합니다.

이 기능은 왜 있을까요?
그리고 나서 생성자로 아이템을 결정하는 것과 비교하면 어떤 차이가 있을까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/adapter/MovieCatalogAdapter.kt
> +    val movie: (Movie) -> Unit,
movie() 라고 함수를 호출하면 무엇을 의미하는지 누가 봐도 이해가 되는 코드일까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/ReservationHomeContract.kt
> +}
MVP 패턴에서 인터페이스를 나누는 방법이 잘못되었어요.
학습을 다시 해 보시면서 무엇이 잘못되었는지 찾아보세요

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/presenter/ReservationDetailPresenter.kt
> +    }
함수의 파라미터를 통해 서로 다른 movieId가 프레젠터의 이 함수로 전파될 일이 있을까요?
Finish 화면에서 받아온 것과 같이 이전 화면에서 movieId를 전달받을 수 있지 않을까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/presenter/ReservationDetailPresenter.kt
> +    }
detect() 라는 접두어는 어떤 이유로 붙게 되었나요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/presenter/ReservationDetailPresenter.kt
> +    }
비즈니스 로직 호출 결과에 따라 적절한 요청을 View로 잘 전파하고 있어요. 👍🏻 
그런데, 실패했을 때 showResultToast()라는 이벤트가 발행된다면 이게 성공인지 실패인지 알 수 있을까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activity/ReservationDetailActivity.kt
> +        val summary = findViewById<TextView>(R.id.text_view_reservation_summary)
안드로이드에서 가장 무거운 작업 중 하나는 바로 findViewById 입니다.
그렇기 때문에 항상 findViewById를 호출하는 것은 매우 비효율적이라고 볼 수 있습니다.

어떻게 개선할 수 있을까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activity/ReservationDetailActivity.kt
> +    }
버튼을 클릭한다 -> 값을 증가시키라고 프레젠터에게 요청한다 -> 모델의 값을 1 증가시킨다 -> 증가시킨 결과를 출력하도록 요청한다 -> 변경 결과를 출력한다.

이 시나리오를 구현하기 위해서 위 두개의 함수가 어떤 역할을 하는지 매칭이 안되네요.
이 함수들은 왜 MVP 인터페이스의 구현으로서 필요한 것일까요?

View와 Presenter는 서로에게 필요한 협력 관계이지, 초기화를 하라고 명령하는 역할이 아닙니다.

> Presenter : Model과 상호작용하고 View에 UI 갱신을 요청한다. Model과 View를 이어주는 가교 역할을 하는 것이다.

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activity/ReservationFinishedActivity.kt
> +        onBackPressed(this)
이 코드는 왜 있을까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activity/ReservationFinishedActivity.kt
> +        val ticket = intent.intentSerializable("ticket", Ticket::class.java) ?: Ticket()
Movies라는 데이터 홀더 역할을 만들었기 때문에 Ticket에 대해서도 꼭 넘겨주도록 하지 않는 방법도 있습니다.

가령 이러한 함수를 도메인 역할로 만들어 볼 수도 있겠습니다.
> TicketStore.getTicketBy(movieId)

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/activity/ReservationFinishedActivity.kt
> +    }
이 화면의 뒤로가기가 커스텀으로 변경된 이유는 무엇일까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/model/Movies.kt
> +import woowacourse.movie.R
R 클래스는 View일까요? Model일까요?

1단계 미션의 경험을 되살려 봤을 때 Model이 View에 접근해도 될까요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/model/Ticket.kt
> +class Ticket : Serializable {
`Serializable` 이 필요한 이유는 무엇일까요?

> 화면 이동에 필요해서요

라고 답변을 하신다면 그것은 UI 의 관심사가 아닐까요? 라는 대답을 다시 돌려드릴 것 같아요.
UI 때문에 도메인 모델을 수정하고 있다는 의미니까요.

앞서 Ticket을 반드시 전달하지 않는 방법을 소개 해 드렸습니다.
혹은 Serializable Parcelable 이라는 키워드로 안드로이드에서 화면 이동을 할 때 사용하는 전략을 한 번 공부 해 보시면 좋습니다.

2024-04-18 14:49 UTC, laco-dev commented on app/src/test/java/woowacourse/movie/model/TicketTest.kt
> +    fun `플러스 버튼을 누르면 티켓 매수가 1장 증가한다 `() {
티켓이라는 모델이 플러스 버튼을 누른다는 관심사를 알 필요가 있나요?

2024-04-18 14:49 UTC, laco-dev commented on app/src/test/java/woowacourse/movie/model/TicketTest.kt
> +    }
1장 미만 그리고 100장 초과를 실패라는 것으로 봐야 할까요?
만약 정말 오류가 나서 실패하는 것도 Failure인가요? 그렇지 않다면 throw로 처리를 하실 것인가요?

레벨 1에서 자주 연습해온 것 과 같이 조금 더 테스트 하기 좋은 모델로 만드려면 어떻게 할 수 있을까? 라는 고민을 같이 해 보시면 좋겠습니다.

가령 아래와 같은 테스트를 예로 들 수 있습니다.
> 티켓의 최소 수량은 1개이다.
> 티켓은 최대 100개까지만 수량으로 가질 수 있다.

2024-04-19 06:35 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/activity/ReservationDetailActivity.kt
> +        val summary = findViewById<TextView>(R.id.text_view_reservation_summary)
한 번만 초기화되게 변경하겠습니다.

2024-04-19 08:38 UTC, haeum808 commented on app/src/androidTest/java/woowacourse/movie/TestFixture.kt
> +}
UI Test는 UI 별로 달라질 수 있기 때문에 분리하겠습니다.

2024-04-19 08:50 UTC, haeum808 commented on app/src/androidTest/java/woowacourse/movie/activity/ReservationDetailActivityTest.kt
> +package woowacourse.movie.activity
어떤 기능을 바꿔야할 때 해당 클래스를 찾기 힘들어져서 유지 보수성이 떨어집니다.

2024-04-19 13:38 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/presenter/ReservationDetailPresenter.kt
> +    }
movieId는 바뀔일이 없기 때문에 ReservationDetailPresenter 생성자에 전달하겠습니다.

2024-04-23 07:25 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/presenter/ReservationDetailPresenter.kt
> +    }
실패라는 의미가 명확하게 변경하겠습니다.

2024-04-23 07:37 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/activity/ReservationFinishedActivity.kt
> +        onBackPressed(this)
뒤로가기 버튼을 테스트하려고 넣었는데 현재는 필요없어져서 삭제했습니다.

2024-04-23 07:39 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/activity/ReservationFinishedActivity.kt
> +    }
테스트하려고 추가했는데 필요없어져서 삭제했습니다.

2024-04-23 07:41 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/model/Movies.kt
> +import woowacourse.movie.R
Model이 View에 접근하면 안됩니다. local db로 변경하겠습니다.

2024-04-23 07:42 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/model/Ticket.kt
> +class Ticket : Serializable {
MovieId와 TicketCount를 전달하게 변경했습니다.

2024-04-23 07:50 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/adapter/MovieCatalogAdapter.kt
> +    private val movies: List<Movie>,
notifyXXX()를 사용하면 효율적으로 업데이트할 수 있습니다.
생성자로 아이템을 결정하면 전체를 다시 다 바꿔야 하기 때문에 비효율적입니다.

2024-04-23 14:41 UTC, laco-dev approved these changes
좋습니다.

조금 더 모델을 활용 해 보면 좋을 것 같은데, 다음 단계에서 이를 요구하고 있어서 고민 해볼 기회가 될 것 같아요.
그 외에도 MVP 패턴에 맞게 분리를 했기에 우리는 프레젠터를 테스트 할 수 있게 됩니다.
그렇기에 프레젠터에 대한 단위 테스트를 작성 해보는 연습도 해 보면 좋을 것 같습니다.

다음 미션에서도 진행해야할 내용이 많이 있어서 1, 2단계는 머지하도록 하겠습니다.
남겨드린 의견은 같이 확인 해주시면 됩니다. 🙏🏻

2024-04-23 14:41 UTC, laco-dev commented on app/src/main/res/layout/item_movie_catalog.xml
> +    <androidx.appcompat.widget.AppCompatImageView
`androidx.appcompat.widget.AppCompatImageView`와 `ImageView`는 어떤 차이가 있을까요??

2024-04-23 14:41 UTC, laco-dev commented on app/src/main/res/values/strings.xml
> +    <string name="reservation_finished_price_unit">원 (현장 결제)</string>
strings.xml 에서도 포맷 형태의 출력을 지원합니다.
아래와 같이 지정하고 사용할 수 있어요. 
```
%d 명
```

2024-04-23 14:41 UTC, laco-dev commented on app/src/test/java/woowacourse/movie/model/TicketTest.kt
> +        }
생성자를 통해 티켓 수량을 만들 수 있다면 repeat을 사용하지 않아도 되겠죠?

2024-04-23 14:41 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/reservation/detail/ReservationDetailContract.kt
> +    }
UI 테스트는 어렵고 복잡합니다.
그렇기에 프레젠터라는 레이어가 만들어지면서 조금 더 테스트 하기 쉬운 구조로 발전하게 됩니다.

그렇다면 프레젠터에 대한 "단위 테스트"를 작성 해 볼 수 있지 않을까요??

2024-04-23 14:42 UTC, merged

2024-04-24 08:47 UTC, haeum808 commented on app/build.gradle.kts
> +
Mockk 라이브러리를 사용해서 테스트 할 때 이 옵션이 빠져있으면 에러가 나서 추가했습니다.
그런데 mockk agent 라이브러리를 추가해서 이 옵션을 삭제했습니다.

2024-04-24 08:48 UTC, haeum808 commented on app/src/androidTest/java/woowacourse/movie/home/HomeActivityTest.kt
> +    }
mockk에 대한 이해가 부족한 상태로 진행했습니다. 이 코드를 제거하고 각 Presenter 테스트를 변경하겠습니다.

2024-04-24 09:01 UTC, haeum808 commented on app/src/androidTest/java/woowacourse/movie/reservation/ReservationFinishedActivityTest.kt
> +        }
@Before을 이용해서 중복을 제거하겠습니다.

2024-04-24 09:04 UTC, haeum808 commented on app/src/main/AndroidManifest.xml
> +            android:parentActivityName=".home.HomeActivity"
backpressed를 추가했을 떄 같이 추가했었는데 까먹고 같이 지워주지 못했습니다.

2024-04-24 09:44 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/home/HomeContract.kt
> +        fun obtainMovies(): List<Movie>
각 역할을 잘 분리하겠습니다.

2024-04-24 10:22 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/model/Movie.kt
> +    val screeningDate: String,
LocalDate 타입으로 바꿔서 대응하기 좋게 변경하겠습니다.

2024-04-24 10:26 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/model/Ticket.kt
> +    }
Failure로 되어 있으면 실패해서 다른 문제가 발생한다고 생각할 것 같습니다.
범위를 벗어났다고 알려주는게 좋다고 생각합니다.

2024-04-24 10:31 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/model/Ticket.kt
> +        get() = _count
백킹 프로퍼티는 List, Mutablist를 쓸 때 사용하는 예인데 이 때는 private set으로 충분하기 때문에 private set을 사용하겠습니다.

2024-04-24 10:52 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/reservation/detail/ReservationDetailActivity.kt
> +            }
프레젠터가 스스로 초기화하게 변경했습니다. 꼼꼼하지 못해서 중복 로직이 생겼습니다.

2024-04-24 11:20 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/reservation/detail/ReservationDetailActivity.kt
> +    }
말도 안된다고 생각합니다.
View에 대한 기능은 Activity에서 하게 변경하겠습니다.

2024-04-24 11:22 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/reservation/detail/ReservationDetailPresenter.kt
> +    }
필요한 값들을 전달한다는 의미로 deliver를 사용했습니다. 그런데 load하는 것도 deliver로 만들어서 load와 deliver를 분리해서 명명하도록 하겠습니다.

2024-04-24 11:37 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/reservation/finished/ReservationFinishedActivity.kt
> +            }
Intent를 다시 반환하고 다른 로직이 없기 때문에 체이닝을 쓸 수 있습니다.

2024-04-24 11:47 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/reservation/finished/ReservationFinishedPresenter.kt
> +        contract.showMovieInformation(movies[movieId])
Movies에서 각 영화를 가져오게 변경하겠습니다.

2024-04-24 11:49 UTC, haeum808 commented on app/src/main/res/layout/item_movie_catalog.xml
> +    <androidx.appcompat.widget.AppCompatImageView
AppCompatImageView는 ImageView와 달리 다양한 버전에서 작동하여 호환성 문제를 해결할 수 있습니다.

2024-04-24 11:50 UTC, haeum808 commented on app/src/main/res/values/strings.xml
> +    <string name="reservation_finished_price_unit">원 (현장 결제)</string>
감사합니다!!

2024-04-24 12:42 UTC, haeum808 commented on app/src/main/java/woowacourse/movie/reservation/detail/ReservationDetailContract.kt
> +    }
프레젠터 단위 테스트들을 작성하겠습니다.