[영화 티켓 예매] 호두 1, 2단계 미션 제출합니다.
woowacourse/android-movie-ticket pull request #69
Opened 2024-04-18 07:57 UTC by Junyoung-WON

# 영화 티켓 - 1, 2단계

안녕하세요, 파이로! 호두입니다. 오랜만에 다시 인사드립니다!
레벨 2의 첫 미션을 파이로에게 리뷰 받게 되었습니다. 이번에도 잘 부탁드립니다~!! 🙇 

오랜만에 다시 미션을 하다보니 레벨 1때의 기억이 가물가물해지네요.. 테스트코드도 뒤늦게 작성하고... 😞 
다시 마음잡고 미션에 임하겠습니다!ㅠㅠ

구현한 기능들에 대한 설명을 간단하게 정리하여 아래에 작성해보았습니다.

## 구현 기능

### 도메인 모델 생성
영화의 정보를 담고 있는 `Movie` 와 예매할 영화 티켓을 나타내는 `MovieTicket` 객체를 만들었습니다.
그리고 `Movie` 의 리스트를 일급 컬렉션으로 묶고, 영화 리스트를 초기화하는 역할을 하는 `Movies` 도 추가로 생성하였습니다.

### 영화 목록 출력
영화 목록을 출력하는 `MainActivity` 에서는 `ListView` 를 활용하여 나타냈습니다.
`ListView` 의 각 Item을 View로 변환하여 보여주는 역할을 하는 Adapter(`BaseAdapter`)도 함께 구현해보았습니다.
`ListView` 보다는 `RecyclerView` 를 더 많이 활용하는 것 같았지만, 우선 `ListView` 를 먼저 사용해보고 둘의 차이가 무엇인지 알아보고 싶었습니다.

### 영화 상세 내용 출력
'지금 예매' 버튼을 클릭하면 해당 영화의 정보를 Intent에 담고, 상세 화면에서 출력했습니다.
해당 Activity 단계에서는 예매할 영화 티켓의 정보를 생성(`MovieTicket` 생성)합니다.
인원 증가, 감소 버튼 클릭에 따라 `MovieTicket` 의 데이터를 변경하고, 변경된 데이터를 화면에 출력합니다.
'예매 완료' 버튼을 누르면 `MovieTicket`의 정보를 다음 Activity로 전달합니다.

### 예매 결과 출력
`MovieDetailActivity` 에서 전달받은 Intent를 활용하여 각 정보들을 화면에 출력합니다.
이전 Activity에서 `MovieTicket` 을 넘겨주는 것이 아니라, `MovieTicket` 의 화면에 출력할 내용만을 넘겨주었기 때문에,
이 경우 View가 Model을 알고 있는 것이 아니기에 MVP 패턴의 적용이 불필요하다고 생각했습니다.
그래서 해당 Activity에서는 MVP 패턴을 적용하지 않았습니다.

### MVP 패턴 활용
미션 요구사항에 따라 MVP 패턴을 적용해보았습니다.
레벨 1에서 자주 사용했던 MVC 패턴과 차이점을 이해하는 것이 어려웠습니다.
특히나 _View가 Model에 관해서 알지 않을 때, `ListView`의 `Adapter`를 리팩터링할 때,_
_과연 이러한 경우에도 MVP 패턴을 적용시켜야 하는가?_ 에 대한 이야기를 페어와 다른 크루들과 많이 나눈 것 같습니다.

## 궁금한 내용

### `ListView` 의 Adapter는 또 다른 View(Activity)로 보는 게 맞을까?
MVP 패턴을 구현하면서 느꼈던 점은, Activity는 View를 그리고 입력을 처리하는 클래스로, 즉 View로서 보고 있다는 것입니다.
처음에는 `ListView`에서 나타낼 각 Item을 View로 그려주어 넘겨주기 때문에, View의 역할을 한다고 생각했습니다.
그렇다면 `ListView`에서 사용하는 Adapter 또한 View의 일부로 보는 것이 맞을까요?

### `ListView` 의 Adapter는 Presenter와 역할이 비슷하다...? 그럼 여기에도 MVP가 적용되는게 맞을까?
하지만 MVP 패턴을 구현해보면서, View와 Model 사이를 연결해주는 매개체 역할을 Presenter가 하고 있고,
이는 Adapter가 하는 일과도 비슷했다고 생각했습니다.
Adapter가 하는 일이 MVP 패턴을 적용하기 전의 Activity가 하는 일과 비슷했기 때문입니다.
- Adapter: List에 있는 각 Model을 적절한 View로 변환해준다.
- Presenter: Model의 데이터를 View에게 적절하게 변환하여 넘겨준다.

***그렇다면 Adapter는 무엇으로 바라봐야 할까?***
***무엇으로 바라보는지에 따라, MVP 패턴의 적용 여부가 달라지겠는데?***

이 두가지 안건 때문에 많은 고민과 토론이 오갔던 것 같습니다.
페어와 내린 결론은,
```
Adapter는 Presenter의 역할도 수행하지만 결국 비즈니스 로직이 존재하지 않고,
View에게 리스트의 각 아이템을 그려서 넘겨주기 위한 객체이니 View에 더 가깝다고 보자.
대신 Model에 대한 의존성을 낮추기 위해 Presenter를 활용하게 하자!
```
입니다. 그래서 지금과 같은 구현을 하게 되었습니다.
~MVP 패턴을 적용하면서 제일 골치 아프게 했던 부분입니다.. 😭~

혹시 저희의 이러한 구현에서 어떤 부분이 잘못되었을까, 무엇을 위배한 것일까를 알고싶습니다.
혹은 너무 요구사항을 맞추는 것에만 집중해서, 오버 엔지니어링으로 무리하게 MVP를 적용하려는 것은 아닌지도 알고싶습니다.

### UI 테스트에서의 Intent 활용과 화면 전환
테스트 실행 전, Intent를 생성하여 해당 Intent를 테스트 액티비티에서 적용하도록 하였습니다.
UI테스트를 진행할 때 이와 같이 Intent를 활용하는 것이 맞는지 궁금합니다!

그리고 화면전환에 대한 테스트도 필요하다고 생각해서, 다음에 나타날 View(`withId()` 활용)가 나타나는지를 확인하는 것으로 구현했습니다.
이렇게 테스트코드를 작성해도 문제가 없을까요?

2024-04-19 02:29 UTC, ghojeong commented
> ListView 의 Adapter는 또 다른 View(Activity)로 보는 게 맞을까

넵. Adapter 는 Item 들을 받아서 ListView 의 각 항목을 랜더링하는 역할을 수행하므로 View로 볼 수 있습니다.

> Adapter는 Presenter의 역할도 수행하지만 결국 비즈니스 로직이 존재하지 않고, View에게 리스트의 각 아이템을 그려서 넘겨주기 위한 객체이니 View에 더 가깝다고 보자. 대신 Model에 대한 의존성을 낮추기 위해 Presenter를 활용하게 하자!

잘 해주신 것 같습니다! Adapter 는 위에 말씀드린 것처럼 View 에 가깝기 때문에, 
Adapter에서 Model에 직접 접근하기보다는 Presenter를 통해 데이터를 전달받는 것이 좋습니다.

> UI 테스트에서의 Intent 활용과 화면 전환
테스트 실행 전, Intent를 생성하여 해당 Intent를 테스트 액티비티에서 적용하도록 하였습니다. UI테스트를 진행할 때 이와 같이 Intent를 활용하는 것이 맞는지 궁금합니다!

넵 ㅎㅎ 잘 전달받았는지 전달받은 데이터가 잘 보이는 지 확인하기 위해 인텐트를 활용해서 테스트합니다 :)

2024-04-19 02:47 UTC, ghojeong requested changes
안녕하세요 호두 🙌
다시 또 만나뵙게 되어 반갑습니다!
도메인 모델에 대한 테스트를 잊지 않아주셔서 감동이네요.
이번 미션도 함께 화이팅입니다!

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/adapter/MovieListAdapter.kt
> +    private val context: Context,
context 를 꼭 넘겨받아야 할까요?
모든 view 는 context 를 가지고 있다는 점 생각해보시면 좋을 것 같습니다.

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/adapter/MovieListAdapter.kt
> +        return view
bindData 메서드로 묶어서 깔끔해보이지만, finViewById 를 매번 호출하고 있네요! 
참고로 finViewById 는 ViewGroup 하위 뷰들을 전부 순회하면서 id 를 비교하기 때문에 무거운 작업입니다. 
어떻게 개선할 수 있을까요?

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/adapter/MovieListAdapter.kt
> +    private val presenter: MainContract.Presenter,
Adapter 에 Presenter를 넘기게 되면 생길 문제는 없을까요?

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/contract/MainContract.kt
> +    }
호두는 Contract 의 역할이 무엇이라고 생각하시나요? 
Model 이 Contract 에 있어서 질문드렸습니다.

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/presenter/MainPresenterImpl.kt
> +    }
Model 을 가져오는 부분을 Presenter 의 역할과 책임에서 분리해보시길 제안드려봅니다.

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/view/MainActivity.kt
> +        startActivity(intent)
하드코딩된 extra key 값은 실수하기 쉽기 때문에 상수해주시길 바랍니다!

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/view/MovieDetailActivity.kt
> +        val posterImageId = intent.getIntExtra("posterImageId", 0)
"posterImageId" 를 가져오는데 실패했는데 id 가 0 이라면 예상지 못한 이미지가 나올 수도 있지 않을까요?

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/view/MovieDetailActivity.kt
> +        findViewById<TextView>(R.id.screeningDate).text = getString(R.string.screening_date_format, screeningDate)
문자열 리소스(R.string.~) 를 잘 활용해주셨네요 👍
문자열 리소스를 활용하면 어떤 장점이 있을까요?

2024-04-19 02:47 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/base/BaseActivity.kt
> +}
BaseActivity 를 사용해주셨군요! 
[읽어볼만한 글](https://thdev.tech/kotlin/2020/12/08/kotlin_effective_14/)이 있어서 첨부드립니다!
따로 수정을 원하는 리뷰는 아닙니다!

2024-04-19 02:47 UTC, ghojeong commented on app/src/androidTest/java/woowacourse/movie/presentation/view/MainActivityTest.kt
> +    }
> 그리고 화면전환에 대한 테스트도 필요하다고 생각해서, 다음에 나타날 View(withId() 활용)가 나타나는지를 확인하는 것으로 구현했습니다. 이렇게 테스트코드를 작성해도 문제가 없을까요?

MainActivity 테스트에서는 MainActivity의 기능과 동작에 집중하는 것이 좋습니다!

2024-04-19 02:47 UTC, ghojeong commented on app/src/test/java/woowacourse/movie/domain/model/MovieTicketTest.kt
> +    }
레벨1에서 연습하신 내용을 잘 반영해주셨군요! 👏
UI 테스트 뿐만 아니라 도메인 모델에 대한 테스트를 잊지 않아주셔서 감동입니다.

2024-04-19 06:17 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/presentation/contract/MainContract.kt
> +    }
제가 이해한 Contract의 역할은,
어떤 기능이나 동작을 위해 필요한 데이터, 요청들을 하나의 집합으로서 묶어놓은 집합체 또는 틀이라고 생각합니다.
Contract 안에 함께 명시해줌으로서 어떠한 기능에서 사용되고 무엇이 필요한 것인지 한 눈에 알 수 있게 해주는 장점을 가지고 있는 것 같습니다.

Model에 대한 Interface를 Contract에 명시한 이유도 마찬가지였습니다. MainActivity에서 영화 리스트를 보여주는데 필요한 모델의 할 일을 명시해주는 것이 적절하다고 생각했습니다.

2024-04-19 07:08 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/presentation/adapter/MovieListAdapter.kt
> +    private val context: Context,
부모(여기서는 ViewGroup인 ListView)가 이미 context를 가지고 있으니, 굳이 context를 넘겨받지 않고, 부모로부터 context를 가져오면 되겠군요! 참고하여 수정해보겠습니다!

2024-04-19 07:11 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/presentation/adapter/MovieListAdapter.kt
> +        return view
이 부분은 오늘 수업 시간에 배운 내용이네요...!
ListView의 단점들 중 하나인 - ViewHolder를 강제하지 않는다는 것과 ViewHolder의 목적과 사용 이유를 배웠습니다.
수업시간에 배운 것을 토대로, ViewHolder를 활용하여서 `findViewById()` 의 호출 횟수를 줄일 수 있을 것 같습니다.
개선해보겠습니다!

2024-04-19 08:56 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/presentation/view/MovieDetailActivity.kt
> +        findViewById<TextView>(R.id.screeningDate).text = getString(R.string.screening_date_format, screeningDate)
문자열 리소스를 활용할 때의 장점은 상수를 활용할 때의 장점과 비슷하다고 생각합니다!
하드코딩한 문자열은 재사용이 어렵고, 만약 다국어 변역과 같이 문자열이 변경되어야하는 기능이 추가될 때에 활용하기가 어렵습니다.
문자열 리소스를 잘 활용한다면 자주 사용되는 문자열을 재사용하기 편리하고, 다른 언어로의 번역이 필요한 기능을 구현하기에도 유용할 것 같습니다!

2024-04-19 12:54 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/presentation/view/MainActivity.kt
> +        startActivity(intent)
intent를 사용하는 Activity에서 companion object로 key 값들을 상수화 해보았습니다.
처음에는 전역에서 사용할 수 있는 상수 클래스를 생성하여 관리할까 생각했지만, 이후에 기능이 추가되면서 Activity가 많아지면 오히려 관리가 까다로워질 것 같았습니다.
그래서 해당 intent의 데이터를 사용하는 Activity에서 상수 key 값을 갖는 것이 더 좋을 거라 생각했습니다!

2024-04-21 11:04 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/movie/presentation/adapter/MovieListAdapter.kt
> +    private val presenter: MainContract.Presenter,
Adapter에 Presenter를 넘긴다면, 우선 해당 ListView를 재사용하기가 어려워질 것 같습니다..!
영화 목록을 보여주는 화면이 다른 Activity에서도 필요하거나, 또 다른 기능을 위해 다른 Presenter와 함께 사용해야 하는 경우에, 해당 Adapter를 사용하기 위해서는 불필요할지도 모르는 MainPresenter를 넘겨주어야 합니다. 이에 View의 재사용이 까다롭고 어려울 수 있을 것 같습니다.
그리고 불필요한 Presenter를 넘겨주어야 하다 보니, Presenter를 더 이상 사용하지 않더라도 Adapter의 사용으로 참조가 계속되기 때문에 메모리의 누수가 발생할 수도 있다고 생각합니다.

presenter를 직접 가지지 않고 MainActivity에서 콜백 이벤트를 넘겨주어서, Activity에서 가지고 있는 presenter를 간접적으로 호출할 수 있도록 수정해 보았습니다!

2024-04-21 12:16 UTC, Junyoung-WON commented
안녕하세요, 파이로! 지난번 피드백 주신 것을 바탕으로 기능을 수정해보았습니다~
그리고 수업시간에 배운 내용들을 활용해서 추가로 더 개선해보았습니다.
제 코드를 리뷰하시기에 조금 더 편하도록, 개선한 부분들에 대한 커밋을 함께 적어보았습니다...!

## 변경 사항

### ListView Adapter에 ViewHolder 패턴 적용 - [4b30741](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/4b307412cdea9f44a3089e43324eb43ac83b5c4f)
>bindData 메서드로 묶어서 깔끔해보이지만, finViewById 를 매번 호출하고 있네요!
참고로 finViewById 는 ViewGroup 하위 뷰들을 전부 순회하면서 id 를 비교하기 때문에 무거운 작업입니다.
어떻게 개선할 수 있을까요?

이후 미션에서 여러 영화들이 추가된다면, findViewById 를 매번 호출하면서 View를 그리는 작업이 무거워질 것 같네요.
ViewHolder 패턴을 적용하면 초기에 한번 생성하여 만들어진 ViewHolder를 가지고서 다시 재사용할 수 있다는 것을 수업 시간에 배웠습니다. ViewHolder 패턴을 활용해서 findViewById의 호출 횟수를 줄이도록 개선해보았습니다.

### Adapter의 불필요한 context 프로퍼티 제거 - [5096d81](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/5096d817a6ee62730abeba82f75c8002301da0fa)
Adapter를 사용하는 부모인 ListView는 ViewGroup으로서, context를 기본적으로 가지고 있습니다.
그리고 Adapter의 getView 오버라이드 메서드에서는 부모 클래스 View가 자신을 인자로 넘겨주고 있으며, 이를 통해 부모의 context에 접근이 가능한 것을 알았습니다!
즉 Adapter 클래스가 굳이 프로퍼티로 부모의 context를 가지고 있지 않아도, getView 메서드 내에서 충분히 부모 context를 사용할 수 있으므로 불필요한 프로퍼티를 제거하였습니다.

### extra key 값의 상수화 - [300b293](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/300b29370305b6fc41849e2d09629df7ff68a046)
Intent에 삽입할 extra key 값을 상수화를 진행였습니다.
해당 Intent의 데이터를 사용하는 Activity에서 상수 key 값을 갖도록 구현하였습니다.

### 화면 전환에 대한 테스트 제거 - [b6641de](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/b6641dea04dabeb5a8a9cc3196214ba88ef8607b)
Activity 테스트에서는 해당 Activity에 대한 UI 테스트 만을 남겨놓는 것이 적절하다는 피드백을 반영해보았습니다..!
화면이 잘 전환되었는지에 대한 테스트는 다른 Activity에서의 Intent 설정이 잘 이루어졌는지 등으로 수행할 수 있는 걸로 이해했습니다.

### 영화 포스터 이미지 불러오기 오류 대처 - [6e42208](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/6e4220886fa4b87e02e6b4e498abfc68622ba92c)
영화 이미지를 불러오는데 실패한 경우(`posterImageId`)에 기본 id를 0으로 설정하는 것에서,
대체 이미지를 drawable에 추가하고, `posterImageId`를 불러오는데 실패한 경우에 해당 이미지 id를 넘겨주는 것으로 변경했습니다.

### MVP Contract에 Model Interface 제거 - [3fd5b19](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/3fd5b19d4a5a68a6470fc1535b875844ab33c68e)
MVP의 Contract에 Model에 대한 Interface를 명시한 이유는, Activity에서 영화 리스트를 보여주기 위해서 Presenter가 Model이 해주기를 원하는 요청 사항을 알기 쉽게 나타내고 싶어서였습니다.
하지만 Model 인터페이스를 명시했을 때, 어떤 문제점이 생기지 않을까를 고민해보았습니다.

지금의 간단한 구현에서는 큰 문제가 생기지 않겠지만, 추후에 다른 기능이 더 생기게 된다면,
그래서 그 기능에서도 Model이 하길 원하는 Interface를 정의한다면, Movie라는 클래스는 너무 많은 Interface를 정의해야 할 것입니다. 이로써 도메인 로직이 복잡해질 것 같습니다.
그리고 이로 인해, 도메인 로직이 View를 위한 UI 로직에 점점 많은 의존성이 발생할 것 같습니다. 이렇게 여러 Presenter가 사용하기 위한 Interface임을 명시한다면 결국 Presenter와 강한 결합이 생기게 되고, 나중에는 View의 변경에도 도메인 로직의 코드를 변경해야할 수도 있습니다.
도메인은 Presenter와 View에 상관없이 독립적으로 그 기능을 수행할 수 있어야 하고, 이를 생각한다면 Model에 대한 Interface를 굳이 정의하지 않는 것이 좋을 것 같다고 생각했습니다.
그래서 Contract에 Model Interface를 제거하였습니다! 그리고 Model Interface를 제거하면서, Presenter에 있던 Model에 대한 역할과 책임의 분리도 함께 진행하였습니다. 이 역시 Model과 Presenter의 결합도를 낮추는 좋은 개선이 된 것 같습니다!

### 화면 회전 시 예매 인원 수가 초기화되는 오류 수정 - [3621da7](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/3621da72f78dd44b448dfdb45f3fcea6597e9cc6)
화면 회전 시에 Activity가 재시작하면서, 예매할 인원 수가 초기화되는 것을 수정하고자
수업 시간에 배운 SIS를 활용하여 개선해보았습니다!
이에 따라 `MovieTicket` 에 예매 인원 수를 초기화하는 메서드를 추가하였고,
SIS를 활용할 수 있도록 `BaseActivity` 의 `onCreateSetup` 메서드에 sis Bundle 인자를 추가하였습니다.
`MovieDetailActivity` 에서는 `onSavedInstanceState()` 가 호출될 때 마다 현재 예매 수를 "count" 키 값으로 저장,
액티비티가 다시 시작할 때 SIS에 저장된 count가 있다면 그 값으로 `MovieTicket` 의 count를 초기화하도록 하였습니다.
이에 필요한 메서드를 Presenter Interface에 추가하고 구현하였습니다.
화면 회전 시 예매 인원 수에 변화가 없음에 대한 테스트 코드도 작성 완료하였습니다.
추가로 "count" 키 값 또한 상수화를 진행했습니다..! - [bd338dd](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/bd338dd6b9f3198568b1499c8aa642077136c89c)

### Adapter의 Presenter에 대한 의존성 제거 - [763017c](https://github.com/woowacourse/android-movie-ticket/pull/69/commits/763017cfec68065ddb34e5d29af0569a0f36ee5d)
Adapter가 Presenter를 프로퍼티로 가지고 있을 경우, 다른 화면에서 영화 리스트를 사용할 때 Adapter의 사용이 까다로울 것 같습니다. MainActivity에서의 동작에서만 필요한 Presenter를 필수적으로 넘겨주어야 하므로, 다른 Activity에서는 불필요하게 Presenter를 생성하여 넘겨주어야 합니다. 다른 기능으로 영화 ListView를 활용한다면, 지금의 구현에서는 활용이 더욱 까다로워질 것 같습니다.
Presenter 대신 MovieList와 콜백 이벤트를 넘겨주어, Presenter를 참조하지 않고도 정상적인 구현이 가능하면서 재사용에도 유연해지도록 변경해보았습니다!

2024-04-21 12:41 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/adapter/MovieListAdapter.kt
> +    private val presenter: MainContract.Presenter,
> 어떤 기능이나 동작을 위해 필요한 데이터, 요청들을 하나의 집합으로서 묶어놓은 집합체 또는 틀이라고 생각합니다.

라고 말씀하셨는데, 혹시 참고하신 레퍼런스 Url이나 도서가 있으실까요?

현재는 [Google의 architecture-samples](https://github.com/android/architecture-samples) 에서는 찾을 수 없지만, 해당 [프로젝트를 클론코딩한 레포지토리](https://github.com/taehwandev/AndroidMVPSample)를 보면, Contract 는 View와 Presenter 의 interface 역할로 사용됩니다. 

MVP 는 특정 도메인이나 모델에 종속되지 않은, 정형화된 디자인 패턴입니다.
그리고 저는 Model 을 View, Presenter 와 묶어서 Contract 로 정의한 코드는 본 적이 없습니다.
MVP 패턴에서 Presenter 는 반환을 하지 않습니다. 왜 그럴까요?

`MainContract.Presenter` 를 상속한 `MainPresenterImpl` 의 `fun movieList(): List<Movie>` 안에서,  `MainContract.Model` 를 상속한 `Movies`의 `initMovieList()` 를 호출하고 있습니다. 
Model 과 Presenter 가 뒤섞여있는데, 리뷰에 Model 을 분리해보면 좋겠다고 한 의미는 Presenter 에서 Model 을 분리해 달라는 의미였습니다.

뒷북이 되었지만 오늘 주말 동안 길게 작성하고 있던 리뷰를 남겨봅니다.

@Junyoung-WON

2024-04-21 13:04 UTC, ghojeong commented on app/src/main/java/woowacourse/movie/presentation/contract/MainContract.kt
> +    }
> 어떤 기능이나 동작을 위해 필요한 데이터, 요청들을 하나의 집합으로서 묶어놓은 집합체 또는 틀이라고 생각합니다.

라고 말씀하셨는데, 혹시 참고하신 레퍼런스 Url이나 도서가 있으실까요?

현재는 [Google의 architecture-samples](https://github.com/android/architecture-samples) 에서는 찾을 수 없지만, 해당 [프로젝트를 클론코딩한 레포지토리](https://github.com/taehwandev/AndroidMVPSample)를 보면, Contract 는 View와 Presenter 의 interface 역할로 사용됩니다. 

MVP 는 특정 도메인이나 모델에 종속되지 않은, 정형화된 디자인 패턴입니다.
그리고 저는 Model 을 View, Presenter 와 묶어서 Contract 로 정의한 코드는 본 적이 없습니다.
MVP 패턴에서 Presenter 는 반환을 하지 않습니다. 왜 그럴까요?

`MainContract.Presenter` 를 상속한 `MainPresenterImpl` 의 `fun movieList(): List<Movie>` 안에서,  `MainContract.Model` 를 상속한 `Movies`의 `initMovieList()` 를 호출하고 있습니다. 
Model 과 Presenter 가 뒤섞여있는데, 리뷰에 Model 을 분리해보면 좋겠다고 한 의미는 Presenter 에서 Model 을 분리해 달라는 의미였습니다.

뒷북이 되었지만 오늘 주말 동안 길게 작성하고 있던 리뷰를 남겨봅니다.

@Junyoung-WON

2024-04-21 13:13 UTC, ghojeong commented
> 도메인은 Presenter와 View에 상관없이 독립적으로 그 기능을 수행할 수 있어야 하고, 이를 생각한다면 Model에 대한 Interface를 굳이 정의하지 않는 것이 좋을 것 같다고 생각했습니다.

호두에게 [도메인 모델의 순수성](https://enterprisecraftsmanship.com/posts/domain-model-purity-completeness/)에 대해 보다 잘 설명하고 싶은 욕심에, 주말동안 저도 공부를 하였습니다.

도메인이란 "사용자가 프로그램을 사용하는 주제 영역"을 뜻하고,
도메인 모델이란 도메인이라는 주제 영역 안에서 "문제를 해결하는 것과 관련된 측면을 추상화" 한 것입니다.

현재 우리의 도메인은 "영화 티켓 예매" 입니다.
그리고 도메인 모델은 "영화 티켓 예매" 를 위해 고객이 당면한 문제를 해결해 주어야 합니다.
문제가 해결되지 않았다면 고객은 호두에게 돈을 지불하지 않을 것입니다.
그리고 문제가 정말로 해결되었는지에 대한 확인은 고객이 아니라 테스트 코드를 통해 이루어져야 합니다.
고객이 확인 후 만약 문제가 해결되지 않은 경우가 생긴다면, 고객은 환불을 요구할 테니까요.

반면 MVP 와 같은 디자인패턴이 해결하려고 한 문제는, 도메인 로직이 해결하는 문제와 영역이 전혀 다릅니다.
디자인패턴이 해결한 문제는 특정 도메인에 종속되지 않기에 자주 쓰이는 패턴이 된 것입니다.
만약 디자인패턴이 도메인에 종속적이라면, 영화티켓 예매 앱과 배달주문앱이 전혀 다른 디자인패턴을 사용하겠지요.
하지만 우리는 게임앱이던, 주식앱이던 종류에 상관없이 동일한 디자인패턴을 적용할 수 있습니다.

호두가 Contract 에 Model 을 섞은 일은,
디자인패턴이 해결하는 문제영역과 도메인모델이 해결하려는 문제영역을 섞은 일입니다.
그리고 이 섞음은 각각의 영역이 해결하려고 한 문제가 무엇인지 혼란을 일으키게 됩니다.

지금은 피드백을 통해 분리를 해주셨지만, 도메인 모델이 해결하려고 한 문제가 테스트 코드로 전혀 테스트 되지 않고 있다는 영향이 남아 있습니다.
이번 기회에 제대로 공부를 해보면 좋겠다는 생각이 들어서,
MVP 디자인패턴이 해결하는 문제가 무엇인지, 호두가 설계한 도메인 모델이 해결한 문제가 무엇인지,
이 두 문제가 어떻게 다른지, 명시적으로 코멘트를 통해 작성해주세요!

따끔한 피드백일 수도 있지만, 이 차이를 아는게 굉장히 큰 도움이 되리라 생각되어 강하게 말을 해보았습니다.

@Junyoung-WON

2024-04-21 13:15 UTC, ghojeong requested changes
호두!
도메인과 도메인 모델이 무엇인지,
모델에 대한 설계가 디자인패턴과 어떻게 다른지에 대해 길게 코멘트를 남겨보았습니다.
읽어보시고 호두가 이해한 만큼 정리해서 답변 부탁드립니다!
그리고 정말 깊게 이해하셨다면 도메인 모델과 테스트 코드가 
여태까지와 전혀 다르게 보이게 되리라 생각됩니다!

2024-04-22 13:38 UTC, Junyoung-WON commented
도메인과 도메인 모델, 그리고 디자인 패턴과 모델에 대한 설계가 어떻게 다른지에 대해서  공부해보았습니다.
이미 파이로님께서 자세하고 명료하게 설명을 해주셨지만, 과연 제가 레벨 1에서의 내용을 잘 알고 있는 것인지 확인하고 싶었습니다.
메타 인지가 잘 되어있는지 확인하고, 안되어있다면 다시 공부해서 저만의 표현 방법으로 개념을 설명해보았습니다.

### 도메인과 도메인 모델이란?

> 도메인이란 "사용자가 프로그램을 사용하는 주제 영역"을 뜻하고,
도메인 모델이란 도메인이라는 주제 영역 안에서 "문제를 해결하는 것과 관련된 측면을 추상화" 한 것이다.
>

도메인이란 다른 말로, “사용자가 프로그램을 통해 해결하고자 하는 문제 영역”이며, 쉽게 말하면 “사용자가 원하는 특정 문제, 관심사”를 의미한다.

모델이란 “어떠한 실체를 추상화하여 나타낸(present) 것”으로 볼 수 있다. 완전히 똑같은 것으로 만든 것이 아니라, 목적과 관심사에 따라서 필요하다고 여겨지는 부분을, 간단하게, 추상적으로 표현한 객체이다.
그렇다면, 도메인 모델은 “문제를 해결하기 위해 만든, 관심사에 관련된 객체를 추상적으로 나타낸 것” 으로 설명할 수 있다.

우리가 이제껏 미션에서 구현하려고 했던 기능들(프로그램의 전체적인 기능)이 결국 “도메인”에 관한 기능이다.
로또(로또를 구입한다, 당첨 번호를 비교한다, 당첨 결과를 알고 수익금을 계산한다  등), 블랙잭(카드를 뽑는다, 뽑은 카드의 결과를 확인한다, 승패 여부에 따라 수익금을 계산한다 등)…

이 모든 기능들이 “도메인” 에 속한다. 우리는 이러한 “도메인”을 해결하기 위해 도메인 모델을 설계하고, 모델 간의 협업과 역할을 구성하고 그에 따른 책임을 모델에게 부여했다.

### 지금 해결해야 할 도메인은 무엇인가?

> 현재 우리의 도메인은 "영화 티켓 예매" 입니다.
그리고 도메인 모델은 "영화 티켓 예매" 를 위해 고객이 당면한 문제를 해결해 주어야 합니다.
문제가 해결되지 않았다면 고객은 호두에게 돈을 지불하지 않을 것입니다.
> 

이번 미션에서는 *영화 티켓 예매* 가 도메인이다.

영화 티켓 예매를 위한 도메인 모델이 적절하게 설계되어야 하고, 설계된 모델은 사용자가 해결하고자 하는 문제를 해결해야만 한다.

아래와 같은 기능들이 도메인에서 다루어야 할 문제 영역이라 볼 수 있다.

- 예매할 영화를 선택한다
- 선택한 영화에 대한 정보가 나타난다
- 예매할 영화의 상영 인원 수를 정할 수 있다
- 예매한 영화 티켓을 확인한다

### 그럼 문제가 해결되었는가를 판단하는 것은?

> 그리고 문제가 정말로 해결되었는지에 대한 확인은 고객이 아니라 테스트 코드를 통해 이루어져야 합니다.
고객이 확인 후 만약 문제가 해결되지 않은 경우가 생긴다면, 고객은 환불을 요구할 테니까요.
> 

우리가 열심히, 어설프게 작성해온 테스트 코드는, 도메인 모델이 원하는 대로 잘 동작하는지를 확인하는 것이다.

즉, “도메인을 잘 구현했는가?”, “사용자의 문제를 잘 해결해주는가?” 를 판단하는 척도라고 할 수 있다.

그렇기 때문에 사용자의 문제 해결을 위한 기능이 잘 동작하는가에 대한 테스트는 필수적이라고 할 수 있고, 이에 대한 테스트가 제대로 작성되지 않은 것은 사용자의 문제가 해결되지 않을 지도 모른다는 것을 의미한다.

### 디자인 패턴에서의 문제 영역

> 반면 MVP 와 같은 디자인패턴이 해결하려고 한 문제는, 도메인 로직이 해결하는 문제와 영역이 전혀 다릅니다.
디자인패턴이 해결한 문제는 특정 도메인에 종속되지 않기에 자주 쓰이는 패턴이 된 것입니다.
만약 디자인패턴이 도메인에 종속적이라면, 영화티켓 예매 앱과 배달주문앱이 전혀 다른 디자인패턴을 사용하겠지요.
하지만 우리는 게임앱이던, 주식앱이던 종류에 상관없이 동일한 디자인패턴을 적용할 수 있습니다.
> 

그렇다면 디자인 패턴에서 바라는, 해결되고자 하는 문제 영역은 무엇일까?
왜 디자인 패턴을 사용하게 되는 것일까? 디자인 패턴을 적용함으로써 얻는 이점은 무엇일까?

디자인 패턴이란 것을 사용하기 전에는 어떤 문제가 발생했고, 그 문제를 해결하고자 디자인 패턴을 사용하게 되었는가를 알기 위해서 디자인 패턴 적용의 장점을 알아보자.

디자인 패턴을 사용했을 때의 장점에 대해서는 잘 알고 있다.
코드의 유지보수가 편리해지고, 도메인 로직의 재사용성을 높이고, 가독성이 좋아진다.

그럼 디자인 패턴을 적용하기 전에는, 아래와 같은 문제점들이 발생했을 거라고 추측할 수 있다.

- 유지보수가 어려웠다.
- 반복되는 도메인 로직을 재사용하기 까다로웠다.
- 코드가 클린하지 못하다.

즉 디자인 패턴이 해결하고자 한 문제는, “코드를 어떻게 구성하고 작성하여야 나중에 고치기도 쉽고, 보기에도 쉬우면서, 한번 작성한 코드를 재활용하기 유리할까?” 에 대한 것이다.

객체지향 프로그래밍을 함으로써, 코드의 중복과 의존성을 줄이고 특정 기능의 수정 및 추가를 할 때 들이는 수고를 줄이는 것이 주 목적이다.

> **Software design pattern - Wikipedia**
> 
> 
> In software engineering, a **design pattern** describes a relatively small, well-defined aspect (i.e. functionality) of a computer program in terms of how to write the code.
> 
> Using a pattern is intended to leverage an existing concept rather than re-inventing it. This can decrease the time to develop software and increase the quality of the resulting program.
> 
> 소프트웨어 공학에서 디자인 패턴은, 어떻게 프로그램을 작성하는가에 관한, 상대적으로 작지만 잘 정의된 관점에 대해 묘사한 것입니다. 
> 
> 패턴을 사용한다는 것은 기존에 존재하는 개념을 다시 만들지 않고 최대한 잘 재활용하려는 의도를 가지고 있음을 의미합니다. 이는 소프트웨어를 개발하는 시간을 단축시키고 완성된 프로그램의 품질을 높여줍니다.
> 

이처럼 디자인 패턴에서 해결하고자 하는 문제 영역은, 어떻게 하면 유지 보수가 편하고 코드의 중복을 없애는 프로그래밍을 할 수 있는가에 대한 것이다.

도메인 모델이 바라보는 문제 영역과 분명 다르다. 디자인 패턴은 특정 도메인에 종속되지 않으며, 도메인 외적인 설계와 구조에 대해 관심을 둔다.

영화 예매 도메인을 예시로 들어보자. 영화를 예매하는 것은 영화관 사이트에서도, 스마트폰의 어플리케이션으로도, 영화관의 키오스크에서도 가능하다.
영화 예매 기능이 동작하는 플랫폼이 다르고, 이에 따라 UI 또한 다르다는 것 말고는, 기능에 있어서는 차이점이 없다.
이는 다른 플랫폼에서 실행되는 프로그램이더라도, 동일한 도메인 로직과 도메인 모델 설계를 가지고 있음을 의미할 것이다.

### What I’ve Done

> 호두가 Contract 에 Model 을 섞은 일은,
디자인패턴이 해결하는 문제영역과 도메인모델이 해결하려는 문제영역을 섞은 일입니다.
그리고 이 섞음은 각각의 영역이 해결하려고 한 문제가 무엇인지 혼란을 일으키게 됩니다.
> 

디자인 패턴이 해결하는 문제영역(코드의 재사용성, 유지보수성, 가독성 증가)과 도메인 모델이 해결하는 문제영역(예매할 영화 티켓 구입)은 다르다.

디자인 패턴에서 도메인 모델의 문제 영역을 주입하는 경우, 디자인 패턴으로서의 역할이 퇴색될 수 있다. 도메인을 해결하기 위한 디자인 패턴으로 해석될 수도 있으며, 이는 되려 코드의 유지보수를 어렵게 만들 수 있다.

2024-04-22 14:13 UTC, Junyoung-WON commented
### MVP 패턴이 해결하려는 문제 영역은?
앞서 설명한 디자인 패턴이 해결하려는 기본적인 문제 영역을 포함하고 있으면서, 기존 MVC 패턴에서 View가 Model을 의존하고 있다는 문제점을 없애기 위함입니다.
안드로이드에서는 view의 동작을 담당하는 activity를 구현하는데, 이 activity가 mvc 패턴에서 controller로써의 역할도 함께 담당합니다. 이에 activity가 하는 일이 많아지고, view에 가까운 activity가 model에 대한 참조를 가지게 됩니다.
이러한 결합성을 없애고자 MVP 패턴이 나타났고, view(activity)와 model의 의존성을 presenter를 통해 없애는 구조를 가지고 있습니다.

### 제가 도메인 모델을 통해 해결하고자 한 문제 영역은?
현재 제가 해결해야 할 도메인의 문제 영역은 "영화를 예매하는 것"입니다.
지금 설계한 도메인 모델을 통해 해결할 수 있는 문제 영역 또한 "영화를 예매하는 것"에 관련되어야 할 것입니다.
하지만 이번 피드백을 보면서, 영화 예매에 관한 기능과 모델의 설계가 조금 부족하다고 느꼈습니다.
이를테면 예매한 결과(고유한 예매 결과를 나타내는 id, 예매 후 티켓의 총 가격 등)를 나타내는 모델이 존재하지 않고 MovieTicket으로만 결과를 나타내고 있습니다.
그리고 추후에 추가될 기능(영화 상영일 및 시간 선택, 좌석 선택)을 생각한다면, 모델의 설계에 많은 수정이 이루어져야 할 것으로 보입니다.(상영일 정보에 관한 로직은 어느 모델에서 나타내야 하는가? 좌석에 따라 상이한 금액은 어디에서 구현되어야 하는가? 등)
그리고 전체적으로 view를 그려내기 위한 모델의 설계라는 느낌을 지울 수가 없었습니다. 

모델에 대한 테스트 코드가 부족하다 느낀 이유도 이러한 요인들로부터 나온 것 같습니다.
도메인과 도메인 모델의 문제영역에 대해 깊게 고민하지 않고 설계를 한데서 나타난 문제점이라고 생각합니다.

2024-04-23 11:59 UTC, ghojeong approved these changes
호두!
이미 피드백 잘 반영해주셨었지만, 추가로 생각해볼만한 내용을 드렸었는데,
그에 대한 답변까지도 무척 훌륭하게 답해주셨습니다!
앞으로도 도메인 모델을 생각하시며 개발해주시면 좋겠습니다.
다음 Step 도 화이팅입니다!

2024-04-23 12:00 UTC, merged