[영화 티켓 예매] 서기 1, 2단계 미션 제출합니다.
woowacourse/android-movie-ticket pull request #73
Opened 2024-04-18 08:27 UTC by Namyunsuk

안녕하세요 페로로! 이번 미션에 리뷰이로 매칭된 서기입니다.
잘 부탁드립니다😘

2024-04-18 16:20 UTC, laco-dev requested changes
1, 2단계 미션 고생하셨습니다.

어느정도 MVP 패턴 및 안드로이드 구현을 이해하고 계신 것 같습니다.
다만 지금 구현에서는 도메인과 데이터에 대한 흐름이 굉장히 어색하게 느껴집니다.

무언가 데이터를 제공하기 위해 억지로 구조가 만들어진 것 같은 느낌?
일관된 흐름으로 각 구현을 나눌수는 없을까? 라는 고민이 필요해 보입니다.

2024-04-18 16:20 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/presenter/MovieReservationCompletePresenter.kt
> +        val movieContent = MovieContentsImpl.find(movieContentId)
MovieContent라는 인터페이스가 만들어졌는데 직접 구현체를 가져다 쓰는 거라면 인터페이스가 왜 만들어졌나요?

레벨 1에서 인터페이스를 만들때에도 동일하게 구현체를 직접 사용하는 방식을 사용했을까요?
```kotlin
class MovieReservationCompletePresenter(
  val view: View,
  val content: Content
) { ... }
``

2024-04-18 16:20 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/presenter/MovieReservationPresenter.kt
> +    private lateinit var reservationCount: ReservationCount
ReservationCount를 latetinit으로 만든 이유가 있나요?

2024-04-18 16:20 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/view/activity/BaseActivity.kt
> +        initializePresenter()
제네릭과 추상 타입을 어떠한 이유로 적용하게 되었는지 모르겠지만, 제네릭이 전혀 활용되고 있지 않아요.

충분히 이해하고 사용하는 것이 아니라면 정말 의미있는 코드인가 라는 생각을 해보셨으면 좋겠습니다.
```kotlin
<P: BaseContract.Presenter>

abstract fun initializePresenter(): P

private val presenter: P
...
```

2024-04-18 16:20 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/model/data/MovieContentsImpl.kt
> +    }
null 대신에 데이터를 찾지 못했을 때 의미를 알 수 없는 더미 데이터를 반환하는게 좋은 방법일까요?

2024-04-19 05:15 UTC, Namyunsuk commented on app/src/androidTest/java/woowacourse/movie/view/activity/MovieReservationActivityTest.kt
> +package woowacourse.movie.view.activity
화면별로 패키지를 분리하지 않을 경우 특정 화면에 대한 코드를 찾고싶은 경우 각 패키지에서 해당 기능에 대한 코드를 일일이 찾아야해서 안좋지 않은 방법 인것 같습니다.
(시간복잡도로 보자면 기존 방식은 O(n^2) 이라면 화면별로 모아두는 경우 O(n)..? 이렇게 생각이 들었습니당(적당한 비유인지는 모르겠네요..😅))

2024-04-19 05:50 UTC, Namyunsuk commented on app/src/androidTest/java/woowacourse/movie/view/activity/MovieReservationActivityTest.kt
> +    }
MovieContentsImpl의 find를 활용하여 러닝타임 테스트의 경우 runningTime을 가져와서 

`check(matches(withText(runningTime)))` 이렇게 테스트를 할 수 도 있을 것 같네요!

즉 테스트를 위해 넣어준 값을 그대로 가져와서 해당 값이 ui에 들어있는 값과 같은지 테스트를 하면 될 것 같습니다😀
그렇다면 러닝테스트 뿐만 아니라 다른 테스트들도 그렇게 수정할 수 있겠네요

2024-04-19 06:11 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/view/activity/MovieReservationActivity.kt
> +        }
아하 이런 방법도 있군요 감사합니다 👍🏼👍🏼🚀

2024-04-19 06:14 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/view/activity/MovieReservationActivity.kt
> +    override fun setUpMovieContentUi(movieContent: MovieContent) {
화면 시작 시 초기에 들어가는 값에 대한 경우 setUp을 사용하였고 이후에 바뀌는 값에 대해서는 updateXXX로 네이밍을 하여 구분해주었습니다!😊

2024-04-19 06:17 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/conrtract/MovieReservationContract.kt
> +        fun clickReservationButton()
이해했습니다!! 수정하겠습니당🙂

2024-04-19 06:29 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/constants/MovieContentKey.kt
> +}
앗,, 그렇네요..
말씀해 주신 리뷰를 보고 고민했을 때  두 가지 방법이 생각났습니다.

1. 각 클래스에 동반객체에 키값을 상수화하는 방법
2. 화면별로 구조를 분리(패키지)했을 때 키값을 사용하는 패키지 내에 상수클래스를 만들어 관리

둘 중 어떤 방식이 좋을지도 고민이지만 두 방법 모두 중복된 상수(키값)이 존재하게 되어서 과연 좋은 방법인가도 확신이 잘 서지 않네요..🥲(물론 처음 방식보다는 더 좋다고 생각됩니다!)

2024-04-19 06:57 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/presenter/MainPresenter.kt
> +    }
첫 화면이 보일 때 미리 저장된 데이터(이번 미션의 경우 영화 정보)를 불러와서 화면에 표시해주어야 하는데 지금은 그렇지 않은 상황이어서 처음 화면에 진입했을 때 미리 데이터를 넣어주어서 위와 같이 코드를 작성하였습니다..🥲 화면에서 아무 동작도 하지않는데 save를 하는 것은 이상한 것 같습니다. 그래서 아래와 같이 미리 값을 넣어주는 방식으로 수정하려고 합니다!

```
object MovieContentsImpl : MovieContents {
    private var id: Long = 0
    private val movieContents = mutableMapOf<Long, MovieContent>()

    init {
        save(
            MovieContent(
                R.drawable.movie_poster,
                "해리 포터와 마법사의 돌",
                Date(2024, 3, 1),
                152,
                "《해리 포터와 마법사의 돌》은 2001년 J. K. 롤링의 동명 소설을 원작으로 하여 만든, 영국과 미국 합작, " +

                        "판타지 영화이다. 해리포터 시리즈 영화 8부작 중 첫 번째에 해당하는 작품이다. 크리스 콜럼버스가 감독을 맡았다. ",
            )
        )
    }
```

2024-04-19 07:27 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/view/adapter/MovieContentListAdapter.kt
> +    private val presenter: MovieContentListContract.Presenter = MovieContentListPresenter(this)
이번에 처음 어댑터를 사용해보면서 어댑터의 역할이 화면을 렌더링하는 것이라 생각했습니다. 따라서 질문해주신것에 대한 답을 드리자면 어댑터가 MVP 패턴에서 말하는 View의 역할을 한다고 판단하였습니다. 그렇게 판단해서인지 혹은 아직 mvp에 익숙하지 않아서인지는 모르겠지만 어댑터가 인터페이스와 호출하는 것이 불편하게 느껴지지 않았습니다,,🙂‍↕️  

그리고 마지막으로 해주신 질문에서 안드로이드 플랫폼과 관련한 코드를 호출하고 화면을 실행하는 등의 동작을 저는 “리스너를 설정, 인텐트 동작”이라 해석하였습니다. 그리고 이 동작들을 어댑터에서 하는 것은 옳다고 생각합니다🧐

2024-04-19 08:30 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/presenter/MovieReservationCompletePresenter.kt
> +        val movieContent = MovieContentsImpl.find(movieContentId)
지금은 데이터베이스를 사용하고 있지 않지만 만약 추가될 경우 MovieContentsImpl을 dao로 바꿀 수 있을 것 같아서 인터페이스로 추상화를 해주었습니다.  코드를 작성하면서도 추상화를 전혀 이용하지 않고 있는것을 인지하면서도 지금은 다른 방법이 없다고 생각해서 구현체만을 사용하여서 위와같이 코드가 작성됐습니다..  그런데 리뷰를 보면서 왜 생성자를 통해서 주입을 안해주었나라는 생각이 드네요🫣
(레벨1때에서는 주입등을 통해서 인터페이스를 활용해주었습니다.. 그때도 구현체는 사용안했는데 왜 그랬나 모르겠네요,,😹😹)

2024-04-19 08:44 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/presenter/MovieReservationPresenter.kt
> +    private lateinit var reservationCount: ReservationCount
`MovieReservationActivity` 화면이 실행될 때마다 예매인원을 초기값으로 설정해주기 위해서 lateinit으로 선언해주었습니다.
```
override fun setUpReservationCount() {
        reservationCount = ReservationCount()
        view.updateReservationCountUi(reservationCount.count)
    }
```

2024-04-19 10:14 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/model/data/MovieContentsImpl.kt
> +    }
더미 데이터를 넘기는 방식은 나중에 첫 화면에 넣을 데이터(영화정보)를 가져올 때 만약 데이터가 없다면 앱을 종료시키기 보다는 빈값이라도 반환하는게 좋다고 당시에 판단하여서 위와 같이 작성하였습니다. 지금 생각해보니 빈값을 넘기는 것 자체가 해당 상황을 오류상황이라고 보지 않는 것인데 그것보다는 예를 들어 null을 반환하여 다음 동작을 수행하지 않는 것이(ex. 화면에 표시) 차라리 낫다는 생각도 드네요,, 혹은 결제와 같은 일이 생기는 것을 아예 방지하기 위해 아예 예외를 던져 앱을 종료시키는 것도 좋은 방법일 것 같다는 생각도 듭니다.. 일단 더 나은 방법을 더 고민해보고 수정해보겠습니다!

2024-04-21 15:15 UTC, Namyunsuk commented
https://github.com/woowacourse/android-movie-ticket/pull/73#discussion_r1571022120 에 해주신 질문에  답변한 것 처럼 저는 어댑터를 뷰라고 판단하여서 일단은  mvp를 계속 적용하였습니다. 

그런데 어댑터에 뷰홀더를 구현해주고 그에 따른 presenter를 리팩토링해주면서 이때 해주신 말씀처럼 뭔가 인터페이스를 호출하는 것이 어색하다고 느껴졌습니다. 뭔가 mvp패턴의 이점을 활용하기 위해 적용했다기 보다 mvp라는 틀에 코드를 맞춘느낌(?)이 들었습니다. 

그렇다는 것은 어댑터가 mvp에서 말하는 View의 역할이 아닌걸까요..? 뭔가 명확한 근거가 떠오르지 않아 계속 갈팡질팡하게 되네요🥲

2024-04-22 01:24 UTC, laco-dev requested changes
피드백 잘 반영 해주셨습니다.

MVP에서 각 컴포넌트에게 필요한 행동을 요청하는 것 만큼.
각각의 컴포넌트도 자율적으로 행동할 수 있는 것들이 있을거에요.

관련해서 의견 같이 남겨드렸으니 충분히 고민 해보세요.

2024-04-22 01:24 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/reservation/MovieReservationContract.kt
> +        fun updateReservationCountUi(reservationCount: Int)
> 화면 시작 시 초기에 들어가는 값에 대한 경우 setUp을 사용하였고 이후에 바뀌는 값에 대해서는 updateXXX로 네이밍을 하여 구분해주었습니다😊

Presenter가 초기에 들어가는 것과 이후에 바뀌는 것을 알 필요가 있나요?
만약 contentUi는 초기에도 바뀌고 나중에도 바뀌면 setUpAndUpdateMovieContentUi()가 되나요?

2024-04-22 01:24 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/reservation/MovieReservationContract.kt
> +        fun setReservationCount(count: Int)
프레젠터도 마찬가지로 setup이라는 의미가 무엇을 나타내는지 예측이 어렵게 됩니다.

예를 들어 예약 번호를 셋업해라 라는 행위가 뭘 하기를 기대할까요?
예약 번호 더하기? 가져오기? 빼기? 제거하기?

필요한 행동을 명확하게 드러나도록 작성하는 것이 더욱 중요합니다.

2024-04-22 01:24 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/reservation/MovieReservationContract.kt
> +        fun moveMovieReservationComplete()
moveMovieReservationComplete() 함수도 이동 영화예약완료 라는 의미가 잘 이해가 되지 않아요.

`reserve()` 라는 이름으로 두는 것과 어떤 차이가 있나요?

2024-04-22 01:24 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/reservation/MovieReservationPresenter.kt
> +    private lateinit var reservationCount: ReservationCount
> MovieReservationActivity 화면이 실행될 때마다 예매인원을 초기값으로 설정해주기 위해서 lateinit으로 선언해주었습니다.

lateinit으로 만든 이유가 될 수 없는 것 같아요. 기본 값은 변수를 선언하면서 생성해도 되지 않나요?

```kotlin
private var reservationCount: ReservationCount = ReservationCount()
```

2024-04-22 01:24 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/reservation/MovieReservationPresenter.kt
> +        val movieContent = movieContents.find(movieContentId)
필요한 MovieContent는 생성자 시점에 직접 찾아도 되지 않을까요?
UI에서 handleError() 검증이 전부 끝난뒤를 보장하기 위해 이러한 설계를 하셨을까요?

만약 그렇다면, 앞으로 만드는 모든 구조에서는 전부 setup() 패턴으로 화면이 그려진 뒤 데이터를 가져오도록 만들어야 한다는 의미가 됩니다.

객체가 협력과 자율적으로 행동하는 것에 아쉬움이 생길 것 같은데요.
아래 코드를 참고 해보세요.

```kotlin

class MovieReservationPresenter(
  val view: View,
  val movieContentId: Long
  ...
) {
   init {
     val movieContent = movieContent.find(movieContnetId)
     if (movieContent == null) { view.notifyMovieNotFound() } else { view.updateMovieContent(movieContent) } 
   }
}
```

2024-04-22 01:24 UTC, laco-dev commented on app/src/main/res/layout-land/activity_movie_reservation_complete.xml
> +        android:layout_height="65dp"
텍스트뷰와 같이 길이에 따라 유동적으로 높이가 달라지는 요소는 기본적으로 height에 고정 값을 사용하지 않습니다.

대신 wrap_content와 padding을 사용해서 크기를 결정하도록 하는데요.
하나의 예로 이 텍스트뷰에 들어가는 문자를 10개 이상의 개행문자를 포함해서 그려보세요. 어떤 현상이 발생할까요?

2024-04-22 01:24 UTC, laco-dev commented on app/src/main/res/layout/activity_movie_reservation.xml
> +            android:layout_height="45dp"
마찬가지로 레이아웃이 가지고 있는 자식들의 크기가 변경될 수 있음을 대비하여 고정 값의 높이 대신 여백을 사용하는 것이 좋습니다.

2024-04-22 01:24 UTC, laco-dev commented on app/src/test/java/woowacourse/movie/model/MovieContentsImplTest.kt
> +package woowacourse.movie.model
테스트 코드 패키지도 모두 맞춰주세요. 🚚

2024-04-22 01:24 UTC, laco-dev commented on app/src/test/java/woowacourse/movie/model/MovieContentsImplTest.kt
> +        assertThat(actual.synopsis).isEqualTo("해리")
다른건 movieContent 데이터가 변경되더라도 문제 없는데, 이 테스트코드는 바로 실패하게 되겠네요.

내부적으로 하드코딩으로 이렇게 저장할지 모르니까, 여러개의 테스트를 해보거나 다른 테스트와 비슷하게 copy 형태로 만들어야 하지 않을까요?

2024-04-22 01:24 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/model/data/MovieContentsImpl.kt
> +    }
> 더미 데이터를 넘기는 방식은 나중에 첫 화면에 넣을 데이터(영화정보)를 가져올 때 만약 데이터가 없다면 앱을 종료시키기 보다는 빈값이라도 반환하는게 좋다고 당시에 판단하여서 위와 같이 작성하였습니다. 지금 생각해보니 빈값을 넘기는 것 자체가 해당 상황을 오류상황이라고 보지 않는 것인데 그것보다는 예를 들어 null을 반환하여 다음 동작을 수행하지 않는 것이(ex. 화면에 표시) 차라리 낫다는 생각도 드네요,, 혹은 결제와 같은 일이 생기는 것을 아예 방지하기 위해 아예 예외를 던져 앱을 종료시키는 것도 좋은 방법일 것 같다는 생각도 듭니다.. 일단 더 나은 방법을 더 고민해보고 수정해보겠습니다!

좋습니다. 👍🏻 
모델을 서버에서 구현한다고 가정하면 데이터가 없다면 404 Not Found 같은 오류가 발생하게 될테니까요.

알 수 없는 데이터 대신 명확하게 오류를 발생하면 사용하는 곳에서도 그에 맞게 대처가 가능해집니다.
트레이드 오프의 영역이지만, nullable 대신 throw를 선택했다면 호출 하는 곳은 매번 이러한 모양이 될지도 모르겠지만요 😓 

```kotlin
try {
   val movieContent = movieContent.find(...)  
} catch (e: NoSuchElementException) {
  view.notifyXXX
} catch (e: Exception) {
  ...
}
```

2024-04-22 06:57 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/model/ReservationCount.kt
> +    }
동일한 인스턴스를 반환하기 위한 의도는 아니었습니다..! 
말씀해주신 메서드를 사용하는 것이 코드를 이해하기 더 좋을 것 같네요🙂 수정하겠습니다!!

2024-04-22 10:37 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/ui/reservation/MovieReservationPresenter.kt
> +    private lateinit var reservationCount: ReservationCount
기존에  `setUpReservationCount` 와`setReservationCount`메서드를 하나의 메서드로 합치면서

```
private lateinit var reservationCount: ReservationCount

    override fun updateReservationCount(count: Int) {
        reservationCount = ReservationCount(count)
        view.updateReservationCountUi(count)
    }
```
위와 같이 리팩토링을 하여서 생성과 동시에 선언하는 것이 힘들어져서  우선 lateinit으로 유지하려고 합니다!(그전에는 페로로 말씀처럼 굳이 lateinit을 쓸 필요가 없다 생각되어서 생성과 할당을 동시에 하도록 수정했었습니다.)

2024-04-22 11:23 UTC, Namyunsuk commented on app/src/main/res/layout-land/activity_movie_reservation_complete.xml
> +        android:layout_height="65dp"
잘리는 군요,,ㅎ 수정하겠습니다😶‍🌫️

2024-04-23 06:39 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/ui/base/BaseView.kt
> +}
BaseView를 생성한 것이 BaseActivity와 어떤 상호작용을 하는 것이 아니라  몇 액티비티에서 공통적으로 사용되는 로직을 추상화해주기 위함이었습니다. BaseView라는 인터페이스명이 부적절 한 것 같네요. 그리고 Contract의 View에 상속시켜줄 필요도 없을 것 같고요. 수정해보겠습니다!

2024-04-23 07:15 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/ui/reservation/MovieReservationPresenter.kt
> +        val movieContent = movieContents.find(movieContentId)
달아주신 리뷰에 대해서 저는 리뷰와 예시로 주신 코드처럼 리팩토링 할 경우 Activity에서 초기에 불러오는 setUp을 직접 호출하는 것이 아니고 presenter가 생성될 때 presenter가 스스로 수행하는 점에서 이점이 있다고 생각이 들었습니다.
그래서 만약 위와 같은 방식으로 리팩토링을 진행 할 경우 아래와 같이 리팩토링이 진행됩니다.
```
class MovieReservationCompletePresenter(
    view: MovieReservationCompleteContract.View,
    movieContents: MovieContents,
    movieContentId: Long,
    reservationCount: Int
) :
    MovieReservationCompleteContract.Presenter {
        init {
            try {
                val movieContent = movieContents.find(movieContentId)
                view.showMovieContentUi(movieContent)
            } catch (e: NoSuchElementException) {
                view.showError(e)
            }
            val ticket = Ticket(ReservationCount(reservationCount))
            view.updateTicketUi(ticket)
        }
}
```

위와 같이 리팩토링을 진행했을 때 객체의 협력과 자율이 크게 와닿지 않네요..😹 
"presenter가 스스로 수행" 이것 만으로도 큰 의미가 있는 것인지 혹은 제가 페로로께서 말씀해주신 리뷰를 잘못된 방향으로 해석한 것인지 모르겠습니다.. 그래서 일단은 리팩토링은 하지않고 이렇게 답글을 남겨봅니다🙂‍↕️

2024-04-23 12:37 UTC, laco-dev approved these changes
좋습니당 💪🏻 

여러가지 시도하고 고민하신 흔적이 있네요.
아직 안드로이드도 아키텍처도 많이 어려운게 당연해요. 학습하는데 있어 자연스러운 과정입니다.

이러한 과정이 1단계 미션에서 어떠한 것과 연결되는지를 찾아보는 것도 한 가지 즐거움입니다.

몇가지 남겨드린 의견은 다음 미션 진행하시면서 같이 확인 해 주시면 됩니다.

2024-04-23 12:37 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/ui/reservation/MovieReservationActivityTest.kt
> +            .check(matches(withText("러닝타임: ${MovieContentsImpl.find(0L).runningTime}분")))
아이템을 준비하는 과정의 코드가 다소 복잡해 보일 수 있고 반복될 수 있으니, 별도 변수로 만들어서 테스트 하는 것도 좋아요.

```kotlin
val movieContent: MovieContent = ...
```

2024-04-23 12:37 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/movie/ui/reservation/MovieReservationActivityTest.kt
> +    }
테스트코드에 로직을 포함하는 것보다. 임의로 하드코딩을 하는것이 더 좋아보여요.
dateFormatter같은 것들이 잘 동작하는지를 확인하고 싶은게 아니니까요!

2024-04-23 12:37 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/complete/MovieReservationCompleteActivity.kt
> +    HandleError {
지금은 HandleError 인터페이스를 Activity가 직접 구현하고 있지만, Contract.View가 이를 구현하게 한다면 프레젠터에서도 이 인터페이스를 통해 협력이 가능해집니다.

```kotlin
interface View: Contract, HandleError { ... }

// Presenter
val view: View

fun foo() {
  view.handleError(throwable)
}
```

2024-04-23 12:37 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/HandleError.kt
> +}
handleError라는 함수만 봤을 때 어떤 오류가 발생했는지 확인이 어려워보이네요.
일반적으로는 예외 타입을 넘겨주고는 합니다.

```kotlin
fun handleError(throwable: Throwable) 
```

2024-04-23 12:37 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/complete/MovieReservationCompleteActivity.kt
> +        presenter.updateTicket(reservationCount)
프레젠터에 호출하는 행위가. setupUi와는 잘 어울리지 않아보이는데요?
Ui를 초기화 하기 위해 필요한 과정일까요?

2024-04-23 12:37 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/complete/MovieReservationCompleteContract.kt
> +        fun updateTicketUi(ticket: Ticket)
함수 이름 뒤에 Ui가 붙는 이유가 있을까여? 없어도 차이가 보이지 않아서요 🤔

2024-04-23 12:37 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/home/MovieHomeActivity.kt
> +        movieContentList.adapter = MovieContentListAdapter(this, movieContents)
어댑터를 매번 생성할 필요가 있을까요!?

어댑터가 제공해주는 notifyXXX() 함수는 어떤 목적을 가질까요?

2024-04-23 12:37 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/home/adapter/MovieContentListAdapter.kt
> +        }
리스너를 등록하는 것은 setup에서 해도 되지 않을까요? 따로 분리가 된 이유가 있을까요?

2024-04-23 12:37 UTC, laco-dev commented on app/src/main/res/values/strings.xml
> +    <string name="date">%s</string>
이 포맷은...어떤 목적으로 사용되는 것일까요?

2024-04-23 12:37 UTC, laco-dev commented on app/src/main/java/woowacourse/movie/ui/complete/MovieReservationCompletePresenter.kt
> +        }
> 위와 같이 리팩토링을 진행했을 때 객체의 협력과 자율이 크게 와닿지 않네요..😹
"presenter가 스스로 수행" 이것 만으로도 큰 의미가 있는 것인지 혹은 제가 페로로께서 말씀해주신 리뷰를 잘못된 방향으로 해석한 것인지 모르겠습니다.. 그래서 일단은 리팩토링은 하지않고 이렇게 답글을 남겨봅니다🙂‍↕️

MovieContent를 가져오는 것은 누구의 역할인가? 로 접근을 해 볼 수 있는데요.
지금은 화면을 이동할 때 데이터를 무조건 넘겨주고 있지만 만약 필요한 데이터를 서버에서 가져온다거나 하면, 이러한 구조는 더이상 사용할 수 없게 됩니다.

예를 들어서 배달의민족 앱에서 식당 상세보기를 클릭한 경우, 상세보기 화면에서 그려야 할 모든 데이터를 미리 불러와서 화면에 넘기고 있을까요?
아니면 식당에 해당하는 ID 값을 넘겨주고, 상세 화면에서 다시 데이터를 불러오고 있을까요?

이러한 개념은 안드로이드 구현에 있어서 자연스러운 흐름으로 학습하게 되시기 때문에, 지금은 우선 이정도로 진행해도 좋을 것 같습니다.

나중에 여러가지 더 미션을 경험하신 뒤에 이 내용이 어떠한 의미를 가지는지 다시 찾아보셔도 좋을 것 같아요.

2024-04-23 12:37 UTC, merged

2024-04-24 04:48 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/ui/complete/MovieReservationCompleteActivity.kt
> +    HandleError {
아하 프레젠터와 협력을 할 수 있겠네요!! 수정하겠습니다😁

2024-04-24 05:31 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/ui/home/MovieHomeActivity.kt
> +        movieContentList.adapter = MovieContentListAdapter(this, movieContents)
찾아 보았을 때 제가 이해한 바로는 notifyXXX() 함수는 말그대로 특정상황에서 adpater에 들어있는 데이터가 변경되었음을 명시적으로 알려주고 다시 화면을 그리도록 하는 목적을 가집니다. 

현재 미션에서는 추가적인 데이터의 삽입, 삭제등이 없어서 어떻게 적용할지가 어렵습니다..ㅜ 

그리고 또 질문드리고 싶은 것은 만약 어댑터 사용시에 데이터를 한번에 불러오기만 하면 되는 기능만 필요한 상황에서도 나중에 확장을 위해서 notifyXXX기능을 같이 구현하는 것이 좋은가요?🥺

2024-04-24 05:33 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/ui/home/adapter/MovieContentListAdapter.kt
> +        }
값을 할당하는 것과 이벤트 리스너를 달아주는 것을 구분지어주고 싶어서 분리를 해주었습니다. 그런데 지금 상황에서는 굳이 분리할 필요는 없을 것 같네요,, 수정하겠습니당

2024-04-24 05:40 UTC, Namyunsuk commented on app/src/main/res/values/strings.xml
> +    <string name="date">%s</string>
앗...... 🙈 삭제하겠습니다..ㅎ

2024-04-24 05:58 UTC, Namyunsuk commented on app/src/main/java/woowacourse/movie/ui/complete/MovieReservationCompleteActivity.kt
> +        presenter.updateTicket(reservationCount)
이전에 메서드 명으로 `loadMovieContent`, `updateTicket` 대신 `setupXXX`사용했을 때 setupUi로 묶어놓았던 것이 메서드명을 수정하면서 presenter가 하는 행위와 어울리지 않게 된 것 같습니다. setUpUi메서드를 없애는 것이 자연스러울것 같네요!