[영화 티켓 예매] 벼리 1, 2단계 미션 제출합니다
woowacourse/android-movie-ticket pull request #75
Opened 2024-04-18 08:51 UTC by gaeun5744

안녕하세요! 안드로이드 6기 크루 벼리입니다 🥰
이번에 여러가지로 욕심을 내다가 시간 분배를 착각해서 코드에 부족한 부분이 많습니다ㅠ 다음 리뷰 요청때는 꼭 다듬겠습니다..! 
이번 미션 부족한 점이 많지만 잘 부탁드립니다 🙇🏻‍♀️

2024-04-19 02:00 UTC, Gyuil-Hwnag requested changes
벼리 안녕하세요!
이번 미션을 함께하게 된 두루라고 합니다. 잘부탁드립니다!

레벨2 안드로이드 첫 미션 구현 고생 많으셨습니다!
미션 구현을 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-04-22 13:19 UTC, gaeun5744 commented on app/src/androidTest/java/woowacourse/movie/MovieReservationActivityTest.kt
> +    }
생각해보니깐 단순히 결과만 코드를 나열하여 이 테스트코드가 무엇을 의미하는지 모호하다는 생각이 드네요ㅠㅠ 최대한 의도를 전달할 수 있도록 메서드를 수정했습니다!

2024-04-22 13:23 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/MovieReservationActivity.kt
> +    }
해당 코드에 관련하여 질문이 있습니다! 
어떤 id와 데이터를 넣어야할지 정하는 것은 `전달 받는 activity`가 가져야할 책임이라 생각합니다. 하지만 `startActivity`를 실행하는 것은 `전달해주는 activity`가 가져야할 책임이라 생각합니다! 
다른 뷰의 `context`를 가져와서 startActivity를 실행하는 부분이 어색하게 느껴져서 메서드를 `getIntent`로 구현했는데, 혹시 이에 대한 두루의 생각은 어떠신가요??

2024-04-22 13:24 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/ScreeningMovieActivity.kt
> +    override fun onClickReservationButton(screenMovieId: Long) {
코드를 일관성있게 구현하지 못했네요...! 조언 감사합니다!!

2024-04-22 13:28 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/data/StubMovieRepository.kt
> +            "$id : id에 해당 하는 영화가 없습니다.",
이 부분에 관해 질문이 있습니다! **혹시 해당 메시지를 상수화 하는 이유가 무엇일까요?**

매직넘버의 경우, 숫자만을 보고 의미를 유추하기 어렵기 때문에 상수화가 필수적이라 생각합니다. 하지만 에러 메시지는 문자를 그대로 읽으면 되기 때문에 의미를 알 수 있을 뿐더러, 오히려 상수화를 하면 해당 메시지의 정확한 의미를 찾기 위해 다른 위치로 이동해서 읽어야하는 번거로움이 생긴다고 생각합니다.

반복되는 에러메시지는 상수화를 하면 간편해지지만, 이렇게 단 한번 나타나는 에러메시지에 대해서도 상수화를 하는 이유가 궁금합니다!

2024-04-22 13:35 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/presenter/MovieMapper.kt
> +fun ScreeningMovie.toScreenMovieUiModel(): ScreenMovieUiModel {
패키지 위치에 대해 고민하다가, 뷰의 개수가 많아져도 Model, View, Presenter 이렇게 3가지로 고정된다는 생각이 들어서 각 페이지별로 패키지를 만들었습니다..!

다만 저는 여전히 Mapper가 `Persenter` 레이어에 속한다고 생각합니다. 왜냐하면 해당 미션에서 가장 중요한 지점은 `view와 Model의 완전한 분리`라고 생각하며, 해당 Mapper은 이를 위한 수단이라 여겼습니다. 

Mapper는 `view`와 `model`을 둘다 알아야 한다는 점에서 `Persenter` 레이어라 생각했는데, 혹시 두루의 생각은 어떠한가요?

2024-04-22 13:36 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/presenter/MovieReservationPresenter.kt
> +    }
뷰의 초기화를 persernter 에서 하는 것이 이상하다고 느껴져서 로직을 옮기고 id에 대한 의존성을 없애봤습니다!!

2024-04-22 13:39 UTC, gaeun5744 commented on domain/src/test/java/woowacourse/movie/study/LocalDateTest.kt
> +        // then
아 해당 부분은 단순히 LocalDate가 어떻게 동작하는지 공부하기 위한 test라서 study 패키지로 분리한 것입니다!! testFixture는 다른 domain과 UITest를 위한 도구라 여겼었는데, 혹시 단순한 라이브러리 공부도 testFixture에 포함되나요?

2024-04-22 13:49 UTC, gaeun5744 commented on domain/src/test/java/woowacourse/movie/model/HeadCountTest.kt
> +class HeadCountTest {
버튼 클릭에 따른 HeadCount 테스트또한 추가했습니다!

2024-04-23 08:16 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationActivity.kt
> +    }
해당 부분과 `ListVIew`의 `viewHolder`를 수업에서 배웠어서 한번 적용해 보았습니다...!

2024-04-23 11:11 UTC, Gyuil-Hwnag approved these changes
벼리 안녕하세요!!
레벨 2 안드로이드 첫 미션 너무 고생 많으셨습니다! 
리뷰 반영 정말 잘 해주셨네요💯

해당 미션은 다음 미션 진행을 위하여 머지하도록 하겠습니다.
도움이 될만한 코멘트 달았으니 확인하여 다음 미션에서 반영해주셔도 좋을 것 같습니다.

추가적으로 DM으로 질문 주셨던 아키텍처와 디자인 패턴에 대해서는 현재 단계보다는 레벨2가 종료되고 나서 살펴보면 더욱더 공감가는 내용이 많으실 것 같아서 추후에 한번 더 살펴보셔도 좋을 것 같다는 생각이 듭니다!!

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
다음 미션도 화이팅입니다💪

2024-04-23 11:11 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationActivity.kt
> +    }
getIntent() 의 활용 정말 좋습니다~👍

2024-04-23 11:11 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/MovieReservationActivity.kt
> +    }
정해진 네이밍 규칙은 따로 없습니다!!
관습적으로 `startActivity` 등의 키워드를 사용하기는 하는데, 벼리만의 기준만 잡는다면 괜찮을 것 같습니다~👍

2024-04-23 11:11 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationPresenter.kt
> +) {
View와 Presenter의 기능별 분리 너무 잘해주셨네요~👍
Presenter도 interface로 만들어 상속받도록 해보는 것은 어떨까 합니다!!
요구사항에도 아래와 같은 내용이 있어서요!
- View와 Presenter를 위한 Contract 인터페이스를 추가한다.

2024-04-23 11:11 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationUiModel.kt
> +    @DrawableRes val imageRes: Int = R.drawable.img_movie_poster,
@DrawableRes 의 활용 정말 좋습니다~👍

2024-04-23 11:11 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_detail_movie.xml
> +                tools:text="해리 포터와 마법사의 돌" />
tools:text 의 활용 정말 좋습니다~👍

2024-04-23 11:11 UTC, Gyuil-Hwnag commented on domain/src/main/java/woowacourse/movie/model/HeadCount.kt
> +@JvmInline
domain 레이어와 app 레이어를 분리해주셨군요~👍
한번 고민해보면 좋을 것 같아서 코멘트 남겨두었습니다!!
분리함으로서 얻는 이점은 어떤것이 있을까요?? 벼리의 생각을 자유롭게 남겨주세요!💪

2024-04-23 11:11 UTC, Gyuil-Hwnag commented on domain/src/main/java/woowacourse/movie/model/RunningTime.kt
> +value class RunningTime(val time: Duration) {
value class를 사용해주셨군요👍
value class와 data class는 어떤 차이점이 있을까요??
또한 @JvmInline 어노테이션을 추가하면 어떤 기능을 할까요??🤔
벼리의 생각을 자유롭게 남겨주세요~💪

2024-04-23 11:24 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presenter/MovieMapper.kt
> +fun ScreeningMovie.toScreenMovieUiModel(): ScreenMovieUiModel {
해당 내용 DM으로 이야기 나누면서 각 패키지별로 바뀌도록 수정되었군요!!👍

2024-04-23 11:24 UTC, merged

2024-04-23 13:21 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/presenter/MovieMapper.kt
> +fun ScreeningMovie.toScreenMovieUiModel(): ScreenMovieUiModel {
혹시 해당 부분에 대해 다시 설명해 주실 수 있으실까요..?
저는 data와 domain의 관계에 대해서 질문했었는데, 의존관계에 대해서는 이해했지만 `Mapper`자체가 어디에 속하는지에 대해서는 DM으로 나눈 기록이 안 보입니다. ㅠㅠ

2024-04-23 13:23 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationActivity.kt
> +    }
넵!! 직렬화에 대해서도 한번 공부해보겠습니다!

2024-04-23 13:23 UTC, gaeun5744 commented on app/src/androidTest/java/woowacourse/movie/MovieReservationActivityTest.kt
> +    }
후자가 더 정확해 보여서 수정하도록 하겠습니다!

2024-04-23 13:27 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/data/StubMovieRepository.kt
> +object StubMovieRepository : MovieRepository {
`repository`의 구현체 중 하나를 `dummy`로 만든 것이 더 알맞겠네요..! 해당 내용에 대해서도 수정하겠습니다!!

2024-04-23 13:34 UTC, Gyuil-Hwnag commented on domain/src/test/java/woowacourse/movie/study/LocalDateTest.kt
> +        // then
@gaeun5744 
해당 내용은 `DateTimeFormatter.ofPattern("yyyy.MM.dd")`으로 포맷을 하는 부분을 함수로 뽑거나 한다면 추후에 날짜 테스트에서도 유용하게 사용할 수 있을 것 같다는 생각이 들어서 남겨두었습니다~

2024-04-23 14:06 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/data/StubMovieRepository.kt
> +            "$id : id에 해당 하는 영화가 없습니다.",
@gaeun5744 
벼리 안녕하세요~
해당 내용에 대해서 상수화를 하도록 요구를 한 내용은 아래와 같습니다! 물론 에러문구에 대해서 위와 같이 하드코딩으로 해서 직접 넣어줘도 되기는 합니다! 
서비스의 규모가 커지고 무수히 많은 객체들이 존재하게 되었을 때 에러 문구에 대해서 수정을 하거나 팝업등으로 디자인 시스템이 바뀌었을 때 어떤 경우가 좀 더 수월할까요?? 만약 문구를 재사용 하게 되는 경우에는 어떠한 경우가 좀 더 나을까요??🤔
1. 위에처럼 각 객체마다 에러 문구가 하드코딩 되어 있는 경우
2. 에러에 대해서 상수화를 하여, 하나의 객체 또는 파일에 모와둔 경우 두가지가 있을 때

서비스를 고도화 하다보면 이러한 시스템 가이드가 바뀌는 일은 생각보다 많이 발생하는 것 같습니다 😥
물론 과하게 상수화를 하는 것은 오히려 독이 되는 경우도 많기는 합니다.. 때로는 과도한 상수화로 인하여 가독성을 해치거나 보일러 플레이트 코드도 생기기도 하고요..
그렇지만, 시스템의 에러 발생시 좀 더 빠르게 대처할 수 있도록 에러 관련해서는 상수화를 하여 좀 더 유의미한 값을 부여해 재사용이나 핸들링을 좀 더 편하게 해볼 수 있도록 상수화를 하는 것은 어떤가 해서 남겨둔 코멘트 였습니다!

2024-04-24 02:52 UTC, gaeun5744 commented on domain/src/test/java/woowacourse/movie/study/LocalDateTest.kt
> +        // then
아하..! 조언 감사합니다!!!

2024-04-24 04:26 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationActivity.kt
> +    private lateinit var minusButton: Button
lateinit은 반드시 초기화 되어야 하며, 재할당을 할 수 있습니다.
by lazy는 어떤 속성이 필요할 때까지 해당 속성의 초기화를 지연시킬 수 있으며, 재할당을 할 수 없습니다. 

저는 View는 초기화 시점을 제어해 onCreate때 반드시 초기화 시켜줘야 한다고 생각했기  때문에 lateinit을 사용했습니다!

2024-04-24 04:30 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationPresenter.kt
> +) {
아 추가하는걸 놓쳤네요..!! 알려주셔서 감사합니다!!

2024-04-24 04:38 UTC, gaeun5744 commented on domain/src/main/java/woowacourse/movie/model/HeadCount.kt
> +@JvmInline
서로 독립된 프로젝트 단위에서 시스템의 중심 domain이 가져야할 구조와 규칙 등을 동일하게 보장해 줄 수 있다는 장점이 있습니다! 기존에는 공통된 domain을 쓸려면 코드를 직접 옮기면서 관리했어야하는데, 이러한 번거로움을 덜어주기 때문에 멀티 모듈로 나누었습니다!

2024-04-24 04:46 UTC, gaeun5744 commented on domain/src/main/java/woowacourse/movie/model/RunningTime.kt
> +value class RunningTime(val time: Duration) {
경우에  따라 다르지만, 객체를 생성하는데 드는 시간과 메모리를 줄일 수 있다는 장점이 있습니다!