[영화 티켓 예매] 꼬상 3, 4단계 미션 제출합니다.
woowacourse/android-movie-ticket pull request #91
Opened 2024-04-28 18:38 UTC by kkosang

안녕하세요 두루 🙇🏻‍♂️

2024-04-29 04:15 UTC, Gyuil-Hwnag requested changes
꼬상 안녕하세요!

해당 미션 구현 고생 많으셨습니다!
미션 구현을 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다~

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-04-29 04:15 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +                .show()
Dialog에 대한 내용을 함수로 분리해보도록 하는 것은 어떨까 라는 생각이 듭니다~💪

2024-04-29 04:15 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +    }
함수별로 너무 잘 분리해주셨네요~👍

2024-04-29 04:15 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +    }
configuration change 에 대한 대응 정말 좋습니다~👍

2024-04-29 04:15 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/screen/detail/MovieDetailPresenter.kt
> +class MovieDetailPresenter(
Presenter에 대한 전반적인 코멘트 입니다~
이번 단계에서 mockK에 대해서 배웠으니, 이를 활용하여 Presenter에 대한 테스트 코드를 작성해보는 것도 좋을 것 같습니다!💪

2024-04-29 05:11 UTC, kkosang commented on app/src/androidTest/java/woowacourse/movie/view/MovieDetailActivityTest.kt
> +class MovieDetailActivityTest {
> 아래의 부분에서 movie의 정보를 활용해보는 것은 어떨까요??🤔 movie의 정보가 재대로 보이는지 테스트 이니까요~
> 
> ```kotlin
>     @Test
>     fun 액티비티가_시작하면_title이_보인다() {
>         onView(withId(R.id.reservation_title_textview))
>             .check(matches(withText("해리포터와 마법사의 돌")))
>     }
> 
> "해리포터와 마법사의 돌" -> movie.title
> ```

기존에 피드백 주셨던 내용인데 이부분은 놓쳤네요 🥲 movie의 정보로 테스트하도록 수정하겠습니다 !!

2024-04-29 07:36 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/reservation/result/ReservationResultPresenter.kt
> +        val ticket = intent.getSerializableExtra("ticket") as? Ticket ?: Ticket()
> `getSerializableExtra()`는 SDK 33부터 Deprecated 되었다고 나오는데, 해당 부분을 버전별 분기처리를 해보는 것은 어떨까 라는 생각이 듭니다~💪

넵 감사합니다 :)  분기처리 하는 부분을 util 패키지에 넣었습니다 !

2024-04-29 08:20 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/screen/detail/MovieDetailActivity.kt
> +    }
> 해당 부분은 `bind`라는 네이밍과 이전처럼 `addClickListener`중에 어떤 네이밍이 좀 더 어울릴까요~🤔

bind라는 네이밍보다 `addClickListener`가 더 잘 어울리는 것 같아서 수정하였습니다 !

2024-04-29 08:24 UTC, kkosang commented on app/src/main/res/layout/activity_reservation_result.xml
>                  android:textSize="20sp" />
> textSize 에는 `sp`와 `dp`가 존재를 하는데 서로 어떤 차이점을 가지고 있을까요??🤔 꼬상의 자유로운 의견을 남겨주세요~

dp는 디바이스의 종류와 화면의 해상도와 무관하게 일정하고
sp는 사용자가 디바이스에서 (글씨)크기를 늘리면, 늘린만큼 반영해주는걸로 알고 있습니다 !

2024-04-29 09:02 UTC, kkosang commented on app/src/main/res/layout/activity_reservation_seat.xml
> +        android:layout_height="50dp"
> dp로 하드코딩된 부분들은 android resource의 dimens.xml 이라는 파일을 활용할 수 있습니다!! (width, height, margin, padding 등등) 이를 활용하도록 해보는 것도 한번 고민해보면 좋을 것 같다는 생각이 듭니다~💪

dp 같은 경우도 android resource의 dimens.xml 파일로 관리할 수 있군요 ! dimens파일 만들었습니다 !

2024-04-29 16:02 UTC, Gyuil-Hwnag requested changes
꼬상 안녕하세요!
해당 미션 구현 고생 많으셨습니다!
리뷰 반영하면서 구현한 내용 수정 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.
DM으로 연락주신대로, 리뷰 추가 반영한 내용들 다음 요청에서 반영해주시면 살펴보도록 하겠습니다!
추가적으로 꼬상의 생각에 애매한 부분이 있거나 수정하고 싶으신 내용이 있다면 수정하고 요청주세요!!

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-04-30 15:51 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +    }
> 해당 함수로 분리를 함으로서 해당 Activity 내에서 여러 Dialog 에 대해서 이 함수로 대체가 가능해질 것 같네요~ 확장성을 고려하여 아래와 같이도 작성해볼 수 있겠네요!💪

예시코드 감사합니다 :) title이랑 message 뿐만 아니라 전부 다 추상화하여 사용하도록 하겠습니다 !

2024-04-30 16:02 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +    }
> Android로 넘어온만큼 Android Resource를 활용해보는 것도 좋을 것 같다는 생각이 듭니다~💪

intent에 넘겨주는 key값 같은 경우에 Android Resource에서 관리하는 방법과,  companion object로 해당 클래스에서 명시적으로 선언해주는 방식중 어떤 방식을 많이 사용하나요? 🤔

2024-04-30 16:49 UTC, kkosang commented on app/src/main/java/woowacourse/movie/presentation/screen/detail/MovieDetailPresenter.kt
> +        private set
> private set을 통한 외부에서의 setter 접근 제어 정말 좋습니다!!👍 다만, 해당 내용을 외부에서 알 수 있도록 열어두신 이유가 있을까요??🤔

presenter의 model을 외부에서 직접적으로 접근할 상황이 없는데 잠시 착각한 것 같습니다..😂 private var로 수정하겠습니다 !

2024-04-30 17:21 UTC, kkosang commented on app/src/main/res/values/dimens.xml
> +
> dimen을 너무 잘 적용해주셨습니다~ 한번 고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다! 해당 내용을 보면 단순히 dp를 dimen으로 밖에 변환한 거로 밖에 생각이 들 수 있는데, 좀 더 의미있는 값들로 지정을 하려면 어떻게 해야 할까요??🤔
> 
> 코멘트 반영보다 어떤 경우에 dimen등으로 묶는 것이 좋을지에 대한 꼬상의 의견이 궁금해서요!

dimen을 통해서 size를 재사용할 수 있는데 현재는 weight,height,margin,padding 전부 따로 만들어놔서 제대로 재활용을 못하고 있다고 생각합니다.. 😂 dimen을 크게 둘로 나눠서 dp와 sp의 사이즈를 정의해주면 좀 더 재사용하는데 용이하다고 생각하여 수정하였습니다 !

2024-04-30 17:23 UTC, kkosang commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_height">48dp</dimen>
> 해당 내용도 위의 dimen에 남긴 내용과 같은 의미로 text_sp를 좀 더 의미있는 값들로 지정을 하려면 어떻게 해야 할까요??🤔 그리고 dimen으로 묶음으로서 어떤 이점을 얻어갈 수 있을까요?? (어떤 상황에서 유용하게 쓸 수 있을지 고민해보면 좋을 것 같습니다!)

재사용 할 수 있도록, 크게 size_dp, size_sp로 구분하였습니다 !

2024-04-30 17:24 UTC, kkosang commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_height">48dp</dimen>
> 해당 내용도 위의 dimen에 남긴 내용과 같은 의미로 text_sp를 좀 더 의미있는 값들로 지정을 하려면 어떻게 해야 할까요??🤔 그리고 dimen으로 묶음으로서 어떤 이점을 얻어갈 수 있을까요?? (어떤 상황에서 유용하게 쓸 수 있을지 고민해보면 좋을 것 같습니다!)
> 
크기가 중복되는 경우, 재사용 할 수 있도록 크게 size_dp, size_sp로 구분하였습니다 !

2024-04-30 17:31 UTC, kkosang commented on app/src/main/res/layout/activity_reservation_result.xml
> +            android:textSize="@dimen/text_24sp"
> 꼬상의 생각에 어떤 부분은 `dp` 어떤 부분은 `sp`가 들어가는 것이 좋을 것 같나요??🤔 꼬상의 자유로운 의견을 남겨주세요~ 아래의 코멘트와 관련된 내용 입니다! [#91 (comment)](https://github.com/woowacourse/android-movie-ticket/pull/91#discussion_r1582695718)
 
 dp는 화면의 크기가 달라도 동일한 비율로 보여주고, sp는 시스템설정의 영향을 받는걸로 알고 있습니다 !
 따라서 화면의 요소같은 경우에는 dp로, 글씨 크기 같은경우에는 sp가 들어가는 것이 좋다고 생각합니다 :)

2024-05-03 09:57 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_reservation_result.xml
> +            android:textSize="@dimen/text_24sp"
좋습니다!👍
`sp`, `dp` 설정시 사용자의 설정에 영향을 많이 받으므로, 이를 유의하면서 한다면 디자인팀한테 욕먹는 것을 줄일 수 있을 겁니다😅

2024-05-03 09:59 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +    }
presenter 에서 int (R.string.xxx) 로 넘기고 Activity 에서 그것을 통해서 android resource를 가져오는 방법으로도 해볼 수 있습니다~💪

2024-05-03 10:23 UTC, Gyuil-Hwnag approved these changes
꼬상 안녕하세요!
이번 레벨2 안드로이드 첫 미션이어서 처음 알게된 개념들이 많아서 많이 어려우셨을텐데 너무 고생 많으셨습니다!👏


리뷰 반영 정말 잘 해주셨어요💯
구현을 하시면서 여러가지 고민을 하셨을 텐데 다음번 미션에서도 작 적용을 하면서 발전해 나가시길 바라겠습니다😆

다음 미션 진행을 위하여 해당 미션은 여기서 머지하도록 하겠습니다.
도움이 될만한 내용들 코멘트 달았으니 확인해보셔도 좋을 것 같습니다!

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
앞으로도 응원하겠습니다 💪

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +            )
아래와 같이 Kotlin 에서 named arguments 라는 키워드가 존재합니다~💪
해당 내용을 살펴보는 것도 추후 개발에 도움이 될 것 같다는 생각이 듭니다!
추가로 도움이 될만한 내용인 것 같아서 첨부합니다!

(파라미터가 무수히 많아지고 타입이 같다면 named arguments를 작성하지 않으면, 본인이 작성했는데도 헷갈릴 수 있는데 다른 분들이 보면 더욱더 헷갈릴 수 있겠네요😆)

~~~kotlin
            showDialog(
                title = getString(R.string.dialog_title),
                message = getString(R.string.dialog_message),
                positiveLabel = getString(R.string.dialog_positive),
                negativeLabel = getString(R.string.dialog_negative),
                onPositiveButtonClicked = { presenter.loadReservationInfo() },
                onNegativeButtonClicked = { },
            )
~~~

https://kotlinlang.org/docs/functions.html#named-arguments
https://medium.com/@ivorobioff/named-parameters-in-java-9072862cfc8c

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +    }
ToastMessage 함수 정말 좋습니다~👍

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +    }
다이얼로그가 여러개가 되는 경우에는 어떻게 네이밍을 지어볼 수 있을까요??🤔
아래의 네이밍중에 어떤 것이 좋을 것 같은지, 꼬상의 기준을 세워봐도 좋을 것 같습니다!
`showDialog()`, `showReservationConfirmDialog()`

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/reservation/seat/ReservationSeatActivity.kt
> +                { presenter.loadReservationInfo() },
Android Resource의 활용 좋습니다~👍

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_reservation_result.xml
> +        android:paddingHorizontal="@dimen/size_80_dp"
해당 처럼 dimen을 사용한다면, 사실상 하드 코딩을 하는 것이랑 별다른 차이점을 못 가질 것 같다는 생각이 듭니다!
아래와 같은 네이밍등으로 좀 더 유의미한 값을 가지도록 해보는 것은 어떨까요?🤔
해당 부분은 무조건적으로 dimen으로 뽑으면 오히려 가독성을 해칠 수 있으니, 꼬상의 기준을 세우는 것이 좋을 것 같습니다!

(꼬상이 회사에 갔는데 어떻게 구현되어 있어야, 꼬상이 좀 더 유지보수가 쉬울 것 같은지를 생각하면서 하면 좀 더 의미있게 와닿을 것 같다는 생각이 듭니다!💪)
~~~kotlin
 <dimen name="notification_linear_layout_height">130dp</dimen>

android:layout_height="@dimen/notification_linear_layout_height"
~~~

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/res/values/styles.xml
> +    </style>
Style의 활용 정말 좋습니다!!👍

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/screen/movie/adapter/MovieAdapter.kt
> +    ListAdapter<ScreenView, ScreenViewHolder>(movieViewComparator) {
아래의 키워드도 추후에 시간이 날때 한번 찾아보셔도 좋을 것 같다는 생각이 듭니다!💪

1. ListAdapter 와 RecyclerView는 어떤 차이점이 있을지?
2. RecyclerView 에서는 어떻게 View를 재사용할까? (ViewHolder, RecyclerView Pool, Cache 등등)
3. RecyclerView 의 아이템 수정 -> 어떠한 단점 -> ListAdapter + DiffUtils

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/screen/movie/adapter/MovieViewHolder.kt
> +}
리뷰 반영 너무 잘해주셨습니다~👍

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/presentation/screen/movie/adapter/ScreenView.kt
> +}
@DrawableRes 의 활용 정말 좋습니다!👍
해당 어노테이션이 있음으로서 어떤 동작을 하는지도 살펴봐도 좋을 것 같습니다!💪

2024-05-03 10:23 UTC, Gyuil-Hwnag commented on app/src/test/java/woowacourse/movie/presentation/screen/detail/MovieDetailPresenterTest.kt
> +    }
Presenter 에 대한 테스트 좋습니다~👍

2024-05-03 10:23 UTC, merged