[영화 티켓 예매] 벼리 3, 4단계 미션 제출합니다.
woowacourse/android-movie-ticket pull request #92
Opened 2024-04-28 18:57 UTC by gaeun5744

안녕하세요 두루! 주말 잘 보내셨나요? 😊😊

처음 적용한 mvp에서 model 이 과연 무엇인가에 대해 다시 고민하다가 늦게 제출했습니다...
테스트코드도 전부 완성하지 못했는데, 다음 리뷰 요청때 마무리 해보겠습니다. 😂 (ScreeningMovieActivityTest 쪽도 나중에 꼭 수정하겠습니다..!)
이번 미션도 잘 부탁드립니다!

그리고 이번에 제가 `view`와 `domain`을 나누는 기준에 대해서 슬럼프를 많이 겪었습니다., 객체를 나누고 mvp 패턴을 적용하는 부분에 집중적으로 코멘트를 달아주시면 감사하겠습니다..!!

2024-04-28 19:32 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/MovieReservationUiModel.kt
> +        runningTime = "러닝타임: ${runningTime.inWholeMinutes}",
Acitivity 외부에서 getString을 호출하는 방법을 찾아보다가 실패해서 이렇게 하드코딩으로 박아놓았습니다 😂😂 혹시 외부에서 R.string에 접근하는 방법이 있을까요...?

2024-04-29 06:31 UTC, Gyuil-Hwnag requested changes
벼리 안녕하세요!

해당 미션 구현 고생 많으셨습니다!
미션 구현을 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다~

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingInfoUiModel.kt
> +data class BookingInfoUiModel(
@gaeun5744 
벼리 안녕하세요!
남겨주신 코멘트 관련해서 해당 내용에 남겨두었습니다!
현재 구현을 보면 UiModel로 이 Model을 대체하고 있다는 생각이 드네요🥲

`MovieReservationUiModel`등을 살펴보면 Model 에서 Android 에 대한 의존성을 가지고 있는 것으로 보입니다!
UiModel 로 정의를 할 필요가 있을까 라는 생각이 듭니다!
UiModel 대신 Model 로 각 객체로 가지고 있어서 Model (객체) <-> Presenter <-> View 형태로 가지도록 해보는 것은 어떨까 라는 생각이 듭니다!
UiModel 이라는 네이밍 대신 기존 처럼 객체처럼 (Booking, MovieReservation, 등등) 으로 정의를 해보는 것을 어떨까 라는 생각이 듭니다!

UiModel 은 Ui를 보여주기 위한 Model 이지, 지금처럼 Ui뿐만 아니라, 객체와 비즈니스 로직까지 담당하고 있는 것은 아닐 것 같다는 생각이 듭니다🤔

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingInfoUiModel.kt
> +    fun updateDate(updatedDate: SelectedDateUiModel): BookingInfoUiModel = BookingInfoUiModel(movieId, count, updatedDate, time)
사용을 안하는 함수들이 있습니다🥲

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingInfoUiModel.kt
> +@Parcelize
Parcelable 의 활용 정말 좋습니다~👍

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/HeadCountUiModel.kt
> +}
객체별로 분리를 해주신 내용 정말 좋습니다~
객체를 모두 분리를 해주시는 것도 정말 좋지만, 과도한 분리로 인하여 개발자들은 하나의 객체및 로직을 개발할 때 여러 파일을 탐방해야 한다는 담점도 존재합니다🥲
Count 의 경우 별다른 기능을 담당하고 있지 않은 객체같아보입니다!
이를 따로 분리를 하는 것이 과연 어떤 장점을 가져다 줄지에 대해서 한번 고민해봐도 좋을 것 같다는 생각이 듭니다!💪

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/MovieReservationUiModel.kt
> +    @DrawableRes val imageRes: Int = R.drawable.img_movie_poster,
DrawableRes의 활용 정말 좋습니다~👍
위의 남겨둔 코멘트대로 Ui 전용 Model 과 로직을 담당하고 있는 Model 객체를 분리해보도록 하는 것도 좋을 것 같습니다!💪
(불피요한 UiModel은 없애보는 것도 가독성 측면에서 상당히 좋아질 수 있겠다는 생각이 듭니다!)

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/ScreeningDateTimeUiModel.kt
> +    }
format에 대한 상수화 정말 좋습니다~👍

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/reservationresult/ReservationResultActivity.kt
>      }
해당 내용에서는 findViewById로 넣어주는 부분이 많네요~
findViewById는 Android 내에서는 모든 View를 순회하면서 찾는 상당히 무거운 작업이라서요!
tv_result_title 등을 사용할 때마다 findViewById 함수를 실행시키면 성능적, 가독성 측면에서 상당히 안좋습니다🥲

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/MovieReservationUiModel.kt
> +        runningTime = "러닝타임: ${runningTime.inWholeMinutes}",
Android 의존성이 없는 객체에서 따로 접근하는 방법은 없지만 Android String Resource를 활용하도록 @StringRes resId: Int 로도 해볼 수 있을 것 같다는 생각이 듭니다~

UiModel 이니, Activity 에서 StringRes를 받아서 처리해보도록 startDate, endDate를 객체에서 넘겨주고, 이를 Activity 내부에서 stringResource를 사용해서 변형하도록 입니다!💪

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/screeningmovie/MovieAdapter.kt
> +) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
RecyclerView의 활용 정말 좋습니다~👍
Multiple Adapter 관련해서 한번 고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!

ViewHolder 도 sealed class로 만드는 방법도 있으니 한번 살펴보는 것도 좋을 것 같다는 생각이 듭니다!💪

- 예시입니다!!
~~~kotlin
sealed class ScreenView {
    data class Ads(val poster: Int) : ScreenView()

    data class Screen(
        val id: Int,
        val movie: Movie,
        val startDate: String,
        val endDate: String,
        val selectableDates: List<ScreenDate>,
    ) : ScreenView()
}
~~~
~~~kotlin
class ScreenRecyclerViewAdapter() : RecyclerView.Adapter<ScreenRecyclerViewAdapter.ScreenRecyclerViewViewHolder>() {

...

override fun getItemViewType(position: Int): Int {
  return when (screens[position]) {
      is Screen -> VIEW_TYPE_SCREEN
      is Ads -> VIEW_TYPE_ADS
      else -> VIEW_TYPE_ADS
  }
}

override fun onCreateViewHolder(): ScreenRecyclerViewViewHolder {
        return when (viewType) {
            VIEW_TYPE_SCREEN -> ScreenRecyclerViewViewHolder.ScreenViewHolder()
            VIEW_TYPE_ADS -> ScreenRecyclerViewViewHolder.AdsViewHolder()

...

sealed class ScreenRecyclerViewViewHolder(view: View): RecyclerView.ViewHolder(view) {
        class AdsViewHolder(val view: View) : ScreenRecyclerViewViewHolder(view) {        }
        class ScreenViewHolder(
            val view: View,
            private val screenActionHandler: ScreenActionHandler,
        ) : ScreenRecyclerViewViewHolder(view) {     }
~~~
예시 코드라서 적용을 하시다가 어려운 부분있으면 언제든지 말씀해주세요!!

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/screeningmovie/ScreeningMovieActivity.kt
>      override fun onClickReservationButton(screenMovieId: Long) {
screenMovieId 값은 interface와 비교했을 때 변경으로 인한 별다른 장점이 없어보이는데, 이와 같이 수정하신 이유가 있을까요?🤔

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/screeningmovie/ScreeningMovieItem.kt
> +
고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!!
해당 내용은 Adapter 내부에서 하는 것일까요?? Presenter 내부에서 하는것일까요?? Activity 내부에서 해야하는 것일까요??🤔

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/selectseat/SelectSeatActivity.kt
> +            }.show()
Dialog에 대해서 아래와 같이 함수로 만들어둔다면, 종류가 다양한 Dialog를 사용하려고 했을 때 유의미하게 사용할 수 있겠다는 생각이 듭니다~💪
~~~kotlin
    private fun showAlertDialog(
        title: Int or String, 
        message: Int or String, 
        positiveLabel: Int or String,
        onPositiveButtonClicked: () -> Unit,
        negativeLabel: Int or String,
        onNegativeButtonClicked: () -> Unit
    ) {
        AlertDialog.Builder(this)
            .setTitle(title)
            .setMessage(message)
            .setCancelable(false)
            .setPositiveButton(positiveLabel) { _, _ ->
                onNegativeButtonClicked()
            }
            .setNegativeButton(negativeLabel) { dialog, _ ->
                onNegativeButtonClicked()
            }.show()
    }
~~~

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/selectseat/SelectSeatActivity.kt
> +        }
에러 문구에 대해서 android resource를 활용한다면, 추후 재사용이나 문구등이 수정될 때 유의미하게 사용할 수 있겠다는 생각이 듭니다~💪
또한 if else if else 의 경우 when 등으로 변경을 해볼 수도 있어서 when 과 if 중에서 어떤 것이 좋을지 한번 고민해봐도 좋을 것 같다는 생각이 듭니다!

코틀린 공식 컨벤션에 따르면 if문과 when문은 2줄 이상이면 중괄호를 사용합니다!
https://kotlinlang.org/docs/coding-conventions.html#control-flow-statements

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/selectseat/SelectSeatMapper.kt
> +fun List<Seat>.toSeatsUiModel() = this.map { SeatUiModel(it.row, it.col, it.rate) }
대부분의 객체를 UiModel로 변경하려다 보니 모든 패키지에 UiModel 로 변환 하는 Mapper부분이 계속 들어가게 되는군요🥲

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_movie_reservation.xml
> +            android:layout_marginBottom="19dp"
dp로 하드코딩된 부분들은 android resource의 dimens.xml 이라는 파일을 활용할 수 있습니다!!
(width, height, margin, padding 등등)
이를 활용하도록 해보는 것도 한번 고민해보면 좋을 것 같다는 생각이 듭니다~💪

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_select_seat.xml
> +                android:background="@drawable/sel_seat_chb"
checkBox 를 통해서 해주셨군요~👍

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_select_seat.xml
> +                android:gravity="center" />
Android Resource 의 Style이 있으니, 이를 활용하면 같인 Ui에 대한 중복적인 코드를 없애볼 수도 있겠다는 생각이 듭니다!

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_select_seat.xml
> +            android:textSize="18sp"
textSize 에는 `dp` 와 `sp`가 있습니다!
이는 어떤 차이점이 존재할까요??🤔

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on app/src/test/kotlin/MovieReservationPresenterTest.kt
> +    @DisplayName("영화 정보를 불러오면 화면에 나타난다")
DisplayName을 통해서 테스트 함수명 너무 잘 작성해주셨네요~👍

2024-04-29 06:31 UTC, Gyuil-Hwnag commented on README.md
>  ## 기능 목록
./gradlew clean ktlintCheck 을 돌렸을 때 실패하는 부분들이 있어서 한번 확인해보셔두 좋을 것 같습니다🥲
<img width="1431" alt="스크린샷 2024-04-29 15 29 38" src="https://github.com/woowacourse/android-movie-ticket/assets/84956038/2dea3cfa-9ec0-4fae-93e9-97bec93d4f92">

2024-04-29 06:36 UTC, Gyuil-Hwnag commented
> 안녕하세요 두루! 주말 잘 보내셨나요? 😊😊
> 
> 처음 적용한 mvp에서 model 이 과연 무엇인가에 대해 다시 고민하다가 늦게 제출했습니다... 테스트코드도 전부 완성하지 못했는데, 다음 리뷰 요청때 마무리 해보겠습니다. 😂 (ScreeningMovieActivityTest 쪽도 나중에 꼭 수정하겠습니다..!) 이번 미션도 잘 부탁드립니다!
> 
> 그리고 이번에 제가 `view`와 `domain`을 나누는 기준에 대해서 슬럼프를 많이 겪었습니다., 객체를 나누고 mvp 패턴을 적용하는 부분에 집중적으로 코멘트를 달아주시면 감사하겠습니다..!!

@gaeun5744 
벼리 안녕하세요!
이번 미션을 진행하면서 View의 분리와 Domain의 분리등 디자인 패턴및 아키텍처에 대해서 어떻게 객체를 분리해야 하는지 고민이 많으셨군요🥲

해당을 고민하는 것은 정말 좋은 내용이기는 하지만, 현재는 안드로이드 레벨2 첫 미션이기도 하고 해당 내용은 단계를 진행하면서 각 디자인 패턴등에 대해서 장단점을 느껴보고, 이를 통해서 분리를 한다면 지금 보다 수월하게 분리를 할 수 있지 않을까 라는 생각이 듭니다!💪
레벨2 첫 미션이어서 Android와 많이 친해져 보는 것도 중요하다고 생각이 들긴 합니다!!

너무 좋은 고민을 해주고 계셔서 이번 미션을 진행하면서 어떤점들에서 어려웠는지를 기록해두고 단계를 진행하면서 습득하고 체감한 것들을 토대로 본다면 해결책이 바로 나올 수도 있습니다~

2024-04-29 10:28 UTC, gaeun5744 commented on README.md
> +### step1
아 까먹었네요...! 바로 수정하겠습니다!!

2024-04-29 10:34 UTC, gaeun5744 commented on app/build.gradle.kts
> +    }
아뇨! 테스트를 하다가 애니메이션 관련 에러가 떴습니다!
수업에서 해당 문구를 추가하면 해결할 수 있다고 해서 추가했습니다..!!

2024-04-29 12:03 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/MovieReservationActivity.kt
> +    }
확실히 깜끔해졌습니다..! 자세한 예시를 들어주셔서 감사합니다!!

2024-04-29 12:50 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingInfoUiModel.kt
> +data class BookingInfoUiModel(
@Gyuil-Hwnag 
우선 제가 UiModel을 둔 이유는 다음과 같습니다.

### 1. 화면 회전시에도 데이터를 유지해야하며, 이 데이터를 관리할 객체가 필요

예매 화면의 경우, 1.예매인원 2. 날짜 3. 시간 
이렇게 3가지 데이터를 화면 회전에서도 계속 유지해야 했습니다.

이 데이터들을 전부 그냥 Int나 String으로 관리하면 오히려 가독성이 떨어질 수 있다고 생각하여 이렇게 객체를 분리했습니다. 
또한, 화면을 전환하면서 `@Parcelize`를 이용해 객체를 넘겨줘야 하기 때문에 필요한 부분이라 생각했습니다.


### 2. 데이터를 어떻게 formatting할 지를 결정하는 객체가 필요

처음에는 숫자 앞의 `"상영 시간:" ` 이라는 부연 설명이나, `LocalDate` 객체를 forMatting 하는 것을 전부 Mapper가 처리했습니다. 그러다가 이러한 영역은 `View`가 해야하는 행동이라 생각했습니다. 
만약  `"yyyy-mm-dd" `이  `"yyyy.mm.dd"` 으로 바꾼다면, 뷰 패키지를 가장 먼저 볼 것이라고 생각했습니다.

하지만 Activity에서 model 객체를 받아서 바꾸는 것은 model에 대한 의존성을 강화시킨다고 생각해서, UiModel이 대신 해당 책임을 가지도록 구현했습니다. 그래서 `MovieReservationUiModel` 는 데이터를 `보여주는` 방식을 책임지고 있습니다. 

또한, 이전 Level1에서는 `String`을 한 곳에 모으면, 규모가 큰 프로젝트에서는 한 파일에서 관리해야하는 양이 과도하게 많아지고, 오히려 파편화 될 수 있기 때문에 모든 값들을 한곳에서 관리하지 않았습니다.

그래서 따로 UiModel 객체를 만들어서 관리하는 것이 더 좋다고 생각했습니다.
---
그러다가 다음과 같은 과정을 거치면서 혼란을 겪었습니다.

처음에는 `HeadCount`를 `domain`에 두어서 증가 및 감소 로직을 `domain`에 두었습니다.

그러다가 가로 회전 모드에서도 데이터가 유지되도록 `Activity`에 `HeadCountUiModel`이라는 새로운 객체를 두어서 해당 객체가 view의 예매인원에 대한 정보를 가지도록 했습니다. 

```
fun HeadCount.toHeadCountUiModel(): HeadCountUiModel = HeadCountUiModel(count)
fun HeadCountUiModel.toHeadCount(): HeadCount = HeadCount(count.toInt())
```

그렇게 로직을 두었더니, 양방향으로 데이터를 전환하는 코드를 만들게 되었습니다. 이와 비슷한 코드가 반복되면서, 오히려 도메인을 나눴기 때문에 불필요한 보일러플레이트 코드가 발생한다는 생각을 지울 수 없었습니다.

그래서 `SeatsUiModel`을 만들면서 어디까지가 `view`이며 `domain`의 역할로 두어야할지 혼란을 겪었습니다. 


제 나름대로 level1에서 배운 내용들을 적용하려다 보니 기존의 방식과 많이 다른 결과물이 나왔습니다. 혹시 위의 과정에서, 제가 잘못 적용한 부분이 어디인지 조언을 구하고 싶습니다. 😢😢

2024-04-29 13:01 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingInfoUiModel.kt
> +    fun updateDate(updatedDate: SelectedDateUiModel): BookingInfoUiModel = BookingInfoUiModel(movieId, count, updatedDate, time)
아 이부분은 편리성과 확장성을 위해 추가로 만들었습니다!

현재 사용하고 있는 메서드를 보면, `updateDate`과 `updateTime`은 primitive type 의 값을 받지만 `updateCount`만 UiModel를 파라미터로 받고 있습니다. 이러한 모습이 통일성 없고 어색해 보여서 추가한 것도 있습니다.

혹시 두루는 혼란이 생길 수 있어서 사용하지 않는 함수들은 지우는 편인가요?

2024-04-29 13:07 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/HeadCountUiModel.kt
> +}
이 부분도 [위의 코멘트](https://github.com/woowacourse/android-movie-ticket/pull/92#discussion_r1583038240)와 맥락이 같습니다! 

지금 예매 인원은 숫자만을 보여주고 있지만, 추후 `2명` 이렇게 보여주는 방식이 바뀔 수 있다고 생각해서 추가해둔 것입니다..! 
물론 위의 이유로 해당 객체를 만들었지만, `string.xml` 파일에서 전부 이러한 형식을 관리하는게 아닌지, 그렇다면 `string.xml`에 과도하게 데이터가 많아지면서 오히려 가독성이 떨어지지 않을지 등등 아직도 고민이 많아서 해당 부분에 대해 확신이 없네요😂

2024-04-29 13:15 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/screeningmovie/MovieAdapter.kt
> +) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
아 viewHolder 또한 sealed class를 적용할 생각을 못했었네요...!! 덕분에 배우고 갑니다!!😄😄

2024-04-30 11:43 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingInfoUiModel.kt
> +data class BookingInfoUiModel(
@Gyuil-Hwnag 
안녕하세요 두루! 자세한 설명 감사합니다!! 다만 이해가 가지 않는 부분이 있습니다. 

**Android에 대한 의존성을 가지는 것이 해당 문제와 어떤 관계가 있는지 궁금합니다..!** 혹시 view를 다른 view로 교체하려고 할 때 Android에 대한 의존성이 유연한 교체를 방해하기 때문일까요???

2024-04-30 11:46 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/HeadCountUiModel.kt
> +}
해당 부분에 대해서는 객체를 좀 더 줄여보겠습니다...!!😂😂😂

2024-04-30 11:52 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/MovieReservationUiModel.kt
> +    @DrawableRes val imageRes: Int = R.drawable.img_movie_poster,
해당 ` MovieReservationUiModel` 의 역할은 model의 데이터를 어떻게 표현할지 formatting 해주는 것입니다..! 혹시 이러한 로직도 view가 아닌 presenter(Mapper)가 해주는 것이 좋을까요..??

2024-04-30 13:08 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/selectseat/SelectSeatActivity.kt
> +        }
넵! when 문으로 수정했습니다!!!😄

2024-04-30 13:15 UTC, gaeun5744 commented on app/src/main/java/woowacourse/movie/selectseat/SelectSeatMapper.kt
> +fun List<Seat>.toSeatsUiModel() = this.map { SeatUiModel(it.row, it.col, it.rate) }
리뷰를 반영하면서 고쳐가보니, 우선 제가 해야할 일은 필수적인 UiModel과 필수가 아닌 UiModel을 구분하는 것이 우선이라는 생각이 드네요.... 이 부분에 대해서는 저만의 기준을 찾도록 노력하겠습니다😂

2024-04-30 13:25 UTC, gaeun5744 commented on app/src/main/res/layout/activity_select_seat.xml
> +                android:gravity="center" />
확실히 style을 적용하니 중복코드가 사라져서 가독성이 좋아진 것 같습니다..!

2024-04-30 13:26 UTC, gaeun5744 commented on app/src/main/res/layout/activity_select_seat.xml
> +            android:textSize="18sp"
`dp`는 큰 화면, 작은 화면에 상관없이 같은 크기로 나타납니다.
`sp`는 안드로이드 시스템의 텍스트 크기 설정에 영향을 받기 때문에 좀 더 유저 친화적이라 생각해서 적용했습니다..!

2024-04-30 13:27 UTC, gaeun5744 commented on README.md
>  ## 기능 목록
정말 죄송합니다😱😱 한번 더 확인했어야 했는데 실수했네요ㅠ

2024-05-01 00:56 UTC, gaeun5744 commented
안녕하세요 두루! 
제가 처음 적용한 mvp 에서 정말 많이 헤맸었는데 어떤 방향으로 나아가야할지 짚어주셔서 정말 감사했습니다..! 그리고 좋은 코멘트를 많이 달아주신 덕분에 많이 배우고 갑니다! 
미션을 다 수행하고 나서 뒤를 돌아보니, 제가 집중해야 할 것을 제대로 보지 못하고 한가지에 매몰되어 있다는 생각이 들어 두루에게는 죄송했습니다🤣
뒤늦게 mvp 패턴에서의 model을 제외한 모든 부분을 빨리 마무리 하는 것이 중요하다는 느꼈습니다. 그리고 다음 미션으로 넘어온 시점에서 model 부분을 리팩터링 하는것은 정말 많은 시간이 소요될 것 같아 부득이하게 부족한 코드로 리뷰 요청 드립니다🥹
두루에게 배운것을 토대로 mvp 더불어 많은 부분을 다음  미션에서 꼭 적용하도록 노력하겠습니다
이번 미션에서 정말 감사합니다!!

2024-05-01 04:33 UTC, Gyuil-Hwnag commented
@gaeun5744 
벼리 안녕하세요~
전혀 죄송해 안하셔도 됩니다ㅎㅎ
오히려, 궁금한 것들이나 이번 미션을 진행하면서 벼리의 생각을 다잡고 갈 수 있다면 얼마든지 좋은 과정이라고 생각합니다🥰

DM으로도 남겨두긴 했지만, 추후 벼리가 이번 미션을 진행하면서 얻어가셨던 내용들 한번더 살펴보실 수 있게 코멘트로 남겨둘게요!

- UiModel에 대한 생각

1. 화면 회전시에도 데이터를 유지해야하며, 이 데이터를 관리할 객체가 필요
2. 데이터를 어떻게 formatting할 지를 결정하는 객체가 필요
하여 UiModel을 만들게 되었다는 벼리의 생각은 이해가 되었습니다!
Configuration Change나 데이터를 넘길 때, 저도 여러가지 객체들이 섞여있는 경우에는 이렇게 만들기는 합니다!

~~~kotlin
fun HeadCount.toHeadCountUiModel(): HeadCountUiModel = HeadCountUiModel(count)
fun HeadCountUiModel.toHeadCount(): HeadCount = HeadCount(count.toInt())
~~~

하지만 위의 내용에서 사실상 HeadCountUiModel 와 HeadCount 는 같은 객체라고 생각이 들며, HeadCountUiModel 이 없이 HeadCount 객체를 사용해도 괜찮지 않나 라는 생각이 듭니다!
모든 Ui 마다 UiModel 을 만들려고 하다보니 보일러 플레이트 코드가 생기게 된 것이 아닌가 라는 생각이 듭니다!

> 그렇게 로직을 두었더니, 양방향으로 데이터를 전환하는 코드를 만들게 되었습니다. 이와 비슷한 코드가 반복되면서, 오히려 도메인을 나눴기 때문에 불필요한 보일러플레이트 코드가 발생한다는 생각을 지울 수 없었습니다.
> 그래서 SeatsUiModel을 만들면서 어디까지가 view이며 domain의 역할로 두어야할지 혼란을 겪었습니다.

이 질문을 같이 살펴보면, View 에서는 정말 Model을 알아서는 안되는 것일까요??

MVP, MVC등등에서 정의하고 있는 Model 의 범위는 무수하게 광범위하다는 생각이 듭니다!
객체나 그 객체의 세부적인 로직, 상수등 모두등이 모두 Model 이라는 큰 범주안에 포함되어 있다고 생각이 듭니다~
개인적인 생각으로는 View 에서 Model 참조하는 것 자체는 큰 문제가 되지는 않는다고 생각이 들긴 합니다!
(참조하는 것이 문제가 안된다는 것이지 내부 로직을 알고 있어야 한다는 아닙니다!)

View 와 Model 간의 참조를 억지로 끊기 위한 작업을 하다보니 오히려 양방향 Mapper가 존재하는 UiModel (위에서 언급했듯 필요한 부분도 있지만요!) 등 불필요한 보일러플레이트 코드를 만들어 내고 있다는 생각이 드네요🥲

MVP 프로그래밍 요구사항 및 MVP에 대해서 살펴보면,  `View와 Model 을 최소화한다` 이는 View 에서 Model 에 대해서 아예 몰라야 한다는 뜻일까요?
개인적으로 위의 내용을 풀어보자면 `View 에서 Model 에 대한 참조는 가능하다. 그러나 Model 의 로직에 대해서는 알아서는 안된다.` 이와 같은 내용이라고 생각이 듭니다!

긴글일 것 같아서 결론입니다!
1. View 에서 Model 에 대한 참조는 가능하다!
2. 다만 이는 View 에서 Model 의 내부 비즈니스 로직등 로직에 대해서도 알 수 있다는 말은 아니다! (이를 대신 처리해주기 위해서 Presenter 가 존재를 하며, View는 Presenter 에서 처리한 로직의 결과를 보여주면 된다.)
3. UiModel 의 경우 여러 객체를 전달하여 (Configuration Change 등에 대한 화면 갱신)  Ui 에 보여주기 위한 UiModel 의 경우 생성을 해도 좋은 것 같다!
4. 객체의 참조로 대체가 가능한 상황에서 객체를 그대로 UiModel 로 만들어 두는 보일러 플레이트 코드는 필요 없을 것 같다.(이로 인하여 생기는 양방향 Mapper등) UiModel 이 존재를 하는 큰의미가 없다.

2024-05-01 04:38 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingInfoUiModel.kt
> +    fun updateDate(updatedDate: SelectedDateUiModel): BookingInfoUiModel = BookingInfoUiModel(movieId, count, updatedDate, time)
추후에 사용하려고 하는 경우 남겨두기도 합니다~
따로 사용을 안하고 있는 것 같은 함수들 이었는데, 추후의 확장성 위해 남겨둔 함수들이면 괜찮을 것 같습니다!

2024-05-01 04:40 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/BookingInfoUiModel.kt
> +data class BookingInfoUiModel(
@gaeun5744 
벼리 안녕하세요~
1. BookingInfoUiModel 이라는 네이밍이 살짝 걸리는 것 같습니다! 해당 객체가 정말 Ui 를 보여주기 위한 객체인지, 로직을 담고 있는 객체인지에 대해서 궁금증이 생깁니다!🤔

2024-05-01 04:42 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/moviereservation/uimodel/MovieReservationUiModel.kt
> +    @DrawableRes val imageRes: Int = R.drawable.img_movie_poster,
Presenter 에서 내부적으로 로직을 처리한 후에 View에 `내가 로직을 처리한 결과만 View 에서 보여줘`라고 던지도록 해보면 좋을 것 같습니다💪

2024-05-01 04:43 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/selectseat/SelectSeatMapper.kt
> +fun List<Seat>.toSeatsUiModel() = this.map { SeatUiModel(it.row, it.col, it.rate) }
@gaeun5744 
정말 좋습니다!!
벼리만의 기준을 세우는 것이 제일 중요하고, 그 기준을 가지고 앞으로의 단계를 진행하면서 갱신을 한다면 추후에 정말 많은 발전이 있을 것 같다는 생각이 듭니다ㅎㅎ💪

2024-05-01 04:44 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_select_seat.xml
> +            android:textSize="18sp"
@gaeun5744 
어떠한 경우에 `sp`, 어떠한 경우에 `dp`를 사용할지 벼리의 기준을 세워보는 것도 정말 추후에 큰 도움이 될 것 같다는 생각이 듭니다!💪

2024-05-01 05:16 UTC, Gyuil-Hwnag approved these changes
벼리 안녕하세요!
미션 너무 고생 많으셨습니다! 👏

리뷰 반영 정말 잘 해주셨어요💯
구현을 하시면서 여러가지 고민을 하셨을 텐데 다음번 미션 에서도 작 적용을 하면서 발전해 나가실 모습이 기대가 되네요😆
특히나 이번 미션을 진행하면서 많은 고민을 가졌던 UiModel 의 경우 벼리의 기준을 세워두고 업데이트를 하는 것도 정말 많은 도움이 될 것 같다는 생각이 듭니다!

다음 미션 진행을 위하여 해당 미션은 여기서 머지하도록 하겠습니다.
도움이 될만한 내용들 코멘트 달았으니 확인해보셔도 좋을 것 같습니다!

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
앞으로도 응원하겠습니다 💪

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/reservationresult/ReservationResultActivity.kt
> +    }
함수별 기능분리 정말 좋습니다~👍

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/reservationresult/uimodel/HeadCountUiModel.kt
> +}
수정이 필요한 것은 아니며, 고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!
과연 반드시 필요한 UiModel 인가하는 생각이 들어서 벼리의 의견을 자유롭게 남겨주시면 좋을 것 같습니다!
UiModel이 없이 View에서 count를 받아서 Android Resource를 활용하여 View에서 보여지도록 할 수도 있겠다는 생각이 듭니다~💪

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/reservationresult/uimodel/PriceUiModel.kt
> +}
수정이 필요한 것은 아니며, 고민해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!
과연 반드시 필요한 UiModel 인가하는 생각이 들어서 벼리의 의견을 자유롭게 남겨주시면 좋을 것 같습니다!
UiModel이 없이 View에서 price를 받아서 Android Resource를 활용하여 View에서 보여지도록 할 수도 있겠다는 생각이 듭니다~💪

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/reservationresult/uimodel/ReservationResultUiModel.kt
> +    }
DateUtils를 만든다면, 위에서 UiModel 에서 상수로 들어간 포맷들을 하나로 묶는 것이 가능해질 것 같다는 생각이 듭니다~💪

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/screeningmovie/AdvertiseUiModel.kt
> +) : ScreeningItem
아래처럼 ScreeningItem 내에서 정의를 한다면, 가독성 측면에서 이점을 가져갈 수 있어 보입니다💪
~~~kotlin
sealed interface ScreeningItem {
    data class AdvertiseUiModel(
        @DrawableRes val image: Int = R.drawable.img_advertisement,
    ) : ScreeningItem

    data class ScreenMovieUiModel(
        val id: Long,
        val title: String,
        @DrawableRes val imageRes: Int = R.drawable.img_movie_poster,
        val screenDate: String,
        val runningTime: String,
    ) : ScreeningItem
}
~~~

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/screeningmovie/MovieAdapter.kt
> +            else -> throw IllegalArgumentException()
MultiAdapter의 활용 정말 좋습니다~👍

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/screeningmovie/ScreeningViewHolder.kt
> +class AdvertiseViewHolder(itemView: View) : ScreeningViewHolder(itemView)
아래와 같이 작성을 해볼 수도 있겠다는 생각이 듭니다!💪
~~~kotlin
sealed class ScreeningViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
    class MovieViewHolder(
        itemView: View,
        private val onClickReservationButton: (id: Long) -> Unit,
    ) : ScreeningViewHolder(itemView) {
        private val postImageView: ImageView = itemView.findViewById(R.id.iv_movie_post)
        private val title: TextView = itemView.findViewById(R.id.tv_movie_title)
        private val date: TextView = itemView.findViewById(R.id.tv_movie_running_date)
        private val runningTime: TextView = itemView.findViewById(R.id.tv_movie_running_time)
        private val button: Button = itemView.findViewById(R.id.btn_movie_reservation)

        fun onBind(item: ScreenMovieUiModel) {
            postImageView.setImageResource(item.imageRes)
            title.text = item.title
            date.text = item.screenDate
            runningTime.text = item.runningTime
            button.setOnClickListener {
                onClickReservationButton(item.id)
            }
        }
    }

    class AdvertiseViewHolder(itemView: View) : ScreeningViewHolder(itemView)
}
~~~

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/selectseat/SelectSeatContract.kt
> +}
contract의 구현 너무 잘해주셨네요~👍

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/selectseat/SelectSeatPresenter.kt
> +    }
예약이 실패하는 경우에도 유저한테 알려주도록 해보는 것도 좋을 것 같다는 생각이 듭니다~💪

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/selectseat/uimodel/SeatUiModel.kt
> +}
좌석을 선택하고등의 로직을 가지고 있는데 UiModel 인지는 고민이 필요할 것 같습니다!
private fun color()는 오히려 View의 로직인 것 같습니다!
뭔가 View와 Model 의 로직을 모와서 처리한고 있는 객체라는 생각이 듭니다🤔

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/util/ShowDialog.kt
> +    }.show()
Dialog에 대한 Utils 함수를 만들어 주셨군요~👍

2024-05-01 05:16 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/movie/util/ShowErrorToastMessage.kt
> +}
토스트 메시지에 대한 Utils 함수 좋습니다~👍
android resource를 활용하기 위한, resId: Int 등에 대한 함수도 있으면 추후에 유용하게 사용할 수 있을 것 같다는 생각이 듭니다💪

2024-05-01 05:16 UTC, merged